In [3]:
import mysql.connector
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
Airline = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics\Week 10/Assignment 9/airlines.csv')
Airport = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/airports.csv')
Flight = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/flights.csv')
Plane = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/planes.csv')
Weather = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/weather.csv')

#read the original csv files into pandas/jupyter

In [ ]:
#Part A - i

In [5]:
#ensure the files properly loaded into pandas

Airline.head()

   Unnamed: 0 carrier                    name
0           1      9E       Endeavor Air Inc.
1           2      AA  American Airlines Inc.
2           3      AS    Alaska Airlines Inc.
3           4      B6         JetBlue Airways
4           5      DL    Delta Air Lines Inc.

In [6]:
#the following row counts provide information about potentially missing data

Airline.count()

Unnamed: 0    16
carrier       16
name          16
dtype: int64

In [7]:
#the shape function provides a true row count for the dataset for each csv file
        
Airline.shape[0]

16

In [8]:
Airport.count()

Unnamed: 0    1458
faa           1458
name          1458
lat           1458
lon           1458
alt           1458
tz            1458
dst           1458
tzone         1458
dtype: int64

In [9]:
Airport.shape[0]

1458

In [10]:
Flight.count()

Column1           336776
year              336776
month             336776
day               336776
dep_time          328521
sched_dep_time    336776
dep_delay         328521
arr_time          328063
sched_arr_time    336776
arr_delay         327346
carrier           336776
flight            336776
tailnum           334264
origin            336776
dest              336776
air_time          327346
distance          336776
hour              336776
minute            336776
time_hour         336776
dtype: int64

In [11]:
Flight.shape[0]

336776

In [12]:
Plane.count()

Unnamed: 0      3322
tailnum         3322
year            3252
type            3322
manufacturer    3322
model           3322
engines         3322
seats           3322
speed             23
engine          3322
dtype: int64

In [13]:
Plane.shape[0]

3322

In [14]:
Weather.count()

Column1       26130
origin        26130
year          26130
month         26130
day           26130
hour          26130
temp          26129
dewp          26129
humid         26129
wind_dir      25712
wind_speed    26127
wind_gust     26127
precip        26130
pressure      23400
visib         26130
time_hour     26130
dtype: int64

In [15]:
Weather.shape[0]

26130

In [ ]:
#the count and shape functions show that the Airline and Airport csv files do not have any missing data, so these are good to use as presented.
#the Plane dataset has only one column showing missing values and this column is not required to complete the analysis, so I will remove this column.
#the Flight and Weather dataset shows several instances of missing values, so these two datasets require further cleaning.

In [63]:
#clean the Plane csv by removing the Speed variable because it contains an excessive amount of NaNs (missing values)
#the csv to use for the Plane data is known as PlaneC

PlaneC = Plane[['tailnum', 'year', 'type', 'manufacturer', 'model', 'engines', 'seats', 'engine']]
print(PlaneC)

     tailnum    year                     type                   manufacturer  \
0     N10156  2004.0  Fixed wing multi engine                        EMBRAER
1     N102UW  1998.0  Fixed wing multi engine               AIRBUS INDUSTRIE
2     N103US  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
3     N104UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
4     N10575  2002.0  Fixed wing multi engine                        EMBRAER
5     N105UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
6     N107US  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
7     N108UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
8     N109UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
9     N110UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
10    N11106  2002.0  Fixed wing multi engine                        EMBRAER
11    N11107  2002.0  Fixed wing multi engine                        EMBRAER
12    N11109  2002.0  Fixed wing multi engine                        EMBRAER
13    N11113  2002.0  Fixed wing multi engine                        EMBRAER
14    N11119  2002.0  Fixed wing multi engine                        EMBRAER
15    N11121  2003.0  Fixed wing multi engine                        EMBRAER
16    N11127  2003.0  Fixed wing multi engine                        EMBRAER
17    N11137  2003.0  Fixed wing multi engine                        EMBRAER
18    N11140  2003.0  Fixed wing multi engine                        EMBRAER
19    N11150  2003.0  Fixed wing multi engine                        EMBRAER
20    N11155  2004.0  Fixed wing multi engine                        EMBRAER
21    N11164  2004.0  Fixed wing multi engine                        EMBRAER
22    N11165  2004.0  Fixed wing multi engine                        EMBRAER
23    N11176  2004.0  Fixed wing multi engine                        EMBRAER
24    N11181  2005.0  Fixed wing multi engine                        EMBRAER
25    N11184  2005.0  Fixed wing multi engine                        EMBRAER
26    N11187  2005.0  Fixed wing multi engine                        EMBRAER
27    N11189  2005.0  Fixed wing multi engine                        EMBRAER
28    N11191  2005.0  Fixed wing multi engine                        EMBRAER
29    N11192  2005.0  Fixed wing multi engine                        EMBRAER
...      ...     ...                      ...                            ...
3292  N984DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3293  N985AT  2001.0  Fixed wing multi engine                         BOEING
3294  N985DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3295  N986AT  2001.0  Fixed wing multi engine                         BOEING
3296  N986DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3297  N987AT  2001.0  Fixed wing multi engine                         BOEING
3298  N987DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3299  N988AT  2001.0  Fixed wing multi engine                         BOEING
3300  N988DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3301  N989AT  2001.0  Fixed wing multi engine                         BOEING
3302  N989DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3303  N990AT  2001.0  Fixed wing multi engine                         BOEING
3304  N990DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3305  N991AT     NaN  Fixed wing multi engine                         BOEING
3306  N991DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3307  N992AT  2002.0  Fixed wing multi engine                         BOEING
3308  N992DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3309  N993AT  2002.0  Fixed wing multi engine                         BOEING
3310  N993DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3311  N994AT  2002.0  Fixed wing multi engine                         BOEING
3312  N994DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION
3313  N995AT  2002.0  Fixed wing multi engine                         BOEING
3314  N995DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3315  N996AT  2002.0  Fixed wing multi engine                         BOEING
3316  N996DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3317  N997AT  2002.0  Fixed wing multi engine                         BOEING
3318  N997DL  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3319  N998AT  2002.0  Fixed wing multi engine                         BOEING
3320  N998DL  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION
3321  N999DN  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION

          model  engines  seats     engine
0     EMB-145XR        2     55  Turbo-fan
1      A320-214        2    182  Turbo-fan
2      A320-214        2    182  Turbo-fan
3      A320-214        2    182  Turbo-fan
4     EMB-145LR        2     55  Turbo-fan
5      A320-214        2    182  Turbo-fan
6      A320-214        2    182  Turbo-fan
7      A320-214        2    182  Turbo-fan
8      A320-214        2    182  Turbo-fan
9      A320-214        2    182  Turbo-fan
10    EMB-145XR        2     55  Turbo-fan
11    EMB-145XR        2     55  Turbo-fan
12    EMB-145XR        2     55  Turbo-fan
13    EMB-145XR        2     55  Turbo-fan
14    EMB-145XR        2     55  Turbo-fan
15    EMB-145XR        2     55  Turbo-fan
16    EMB-145XR        2     55  Turbo-fan
17    EMB-145XR        2     55  Turbo-fan
18    EMB-145XR        2     55  Turbo-fan
19    EMB-145XR        2     55  Turbo-fan
20    EMB-145XR        2     55  Turbo-fan
21    EMB-145XR        2     55  Turbo-fan
22    EMB-145XR        2     55  Turbo-fan
23    EMB-145XR        2     55  Turbo-fan
24    EMB-145XR        2     55  Turbo-fan
25    EMB-145XR        2     55  Turbo-fan
26    EMB-145XR        2     55  Turbo-fan
27    EMB-145XR        2     55  Turbo-fan
28    EMB-145XR        2     55  Turbo-fan
29    EMB-145XR        2     55  Turbo-fan
...         ...      ...    ...        ...
3292      MD-88        2    142  Turbo-fan
3293    717-200        2    100  Turbo-fan
3294      MD-88        2    142  Turbo-fan
3295    717-200        2    100  Turbo-fan
3296      MD-88        2    142  Turbo-fan
3297    717-200        2    100  Turbo-fan
3298      MD-88        2    142  Turbo-fan
3299    717-200        2    100  Turbo-fan
3300      MD-88        2    142  Turbo-fan
3301    717-200        2    100  Turbo-fan
3302      MD-88        2    142  Turbo-fan
3303    717-200        2    100  Turbo-fan
3304      MD-88        2    142  Turbo-fan
3305    717-200        2    100  Turbo-fan
3306      MD-88        2    142  Turbo-fan
3307    717-200        2    100  Turbo-fan
3308      MD-88        2    142  Turbo-fan
3309    717-200        2    100  Turbo-fan
3310      MD-88        2    142  Turbo-fan
3311    717-200        2    100  Turbo-fan
3312      MD-88        2    142  Turbo-jet
3313    717-200        2    100  Turbo-fan
3314      MD-88        2    142  Turbo-fan
3315    717-200        2    100  Turbo-fan
3316      MD-88        2    142  Turbo-fan
3317    717-200        2    100  Turbo-fan
3318      MD-88        2    142  Turbo-fan
3319    717-200        2    100  Turbo-fan
3320      MD-88        2    142  Turbo-jet
3321      MD-88        2    142  Turbo-jet

[3322 rows x 8 columns]

In [16]:
#for the Weather dataset, I identified multiple columns with missing values. I will find the mean of each of these columns and replace the NaNs with the mean.

a = Weather["temp"].mean()
b = Weather["dewp"].mean()
c = Weather["humid"].mean()
d = Weather["wind_dir"].mean()
e = Weather["wind_speed"].mean()
f = Weather["wind_gust"].mean()
g = Weather["pressure"].mean()
print(a, b, c, d, e, f, g)

55.203514868537034 41.38539936469043 62.34732174977937 198.06666148102053 10.39586823975324 11.963357253109523 1017.8951752136738

In [17]:
#I create new columns that fill the NaNs with the column mean

WeatherC1 = Weather["temp"].fillna(a)
print(WeatherC1)

0        37.04
1        37.04
2        37.94
3        37.94
4        37.94
5        39.02
6        39.02
7        39.02
8        39.92
9        39.02
10       37.94
11       39.02
12       39.92
13       39.92
14       41.00
15       41.00
16       39.20
17       39.20
18       39.02
19       37.94
20       37.04
21       35.96
22       33.98
23       33.08
24       32.00
25       30.02
26       28.94
27       28.04
28       26.96
29       26.06
         ...
26100    42.80
26101    39.20
26102    41.00
26103    41.00
26104    41.00
26105    42.08
26106    42.80
26107    41.00
26108    42.80
26109    42.98
26110    42.98
26111    42.08
26112    42.08
26113    41.00
26114    42.98
26115    41.00
26116    42.98
26117    42.98
26118    44.06
26119    44.06
26120    44.06
26121    42.80
26122    41.00
26123    37.94
26124    37.04
26125    35.96
26126    33.98
26127    32.00
26128    30.92
26129    28.94
Name: temp, Length: 26130, dtype: float64

In [18]:
#I can check the rows with previously missing values to ensure that the missing values were replaced by the mean

WeatherC1.loc[5596, ]

55.203514868537034

In [19]:
tempc3 = WeatherC1
print(tempc3)

#do i need this one?? Need to see if I use tempc3 or weatherc3 later in the code

0        37.04
1        37.04
2        37.94
3        37.94
4        37.94
5        39.02
6        39.02
7        39.02
8        39.92
9        39.02
10       37.94
11       39.02
12       39.92
13       39.92
14       41.00
15       41.00
16       39.20
17       39.20
18       39.02
19       37.94
20       37.04
21       35.96
22       33.98
23       33.08
24       32.00
25       30.02
26       28.94
27       28.04
28       26.96
29       26.06
         ...
26100    42.80
26101    39.20
26102    41.00
26103    41.00
26104    41.00
26105    42.08
26106    42.80
26107    41.00
26108    42.80
26109    42.98
26110    42.98
26111    42.08
26112    42.08
26113    41.00
26114    42.98
26115    41.00
26116    42.98
26117    42.98
26118    44.06
26119    44.06
26120    44.06
26121    42.80
26122    41.00
26123    37.94
26124    37.04
26125    35.96
26126    33.98
26127    32.00
26128    30.92
26129    28.94
Name: temp, Length: 26130, dtype: float64

In [21]:
Weatherc3 = Weather["dewp"].fillna(b)
print(Weatherc3)

0        21.92
1        21.92
2        21.92
3        23.00
4        24.08
5        26.06
6        26.96
7        28.04
8        28.04
9        28.04
10       28.04
11       28.04
12       28.04
13       28.04
14       28.04
15       26.96
16       28.40
17       28.40
18       24.08
19       24.08
20       19.94
21       19.04
22       15.08
23       12.92
24       15.08
25       12.92
26       12.02
27       10.94
28       10.94
29       10.94
         ...
26100    37.40
26101    37.40
26102    39.02
26103    37.94
26104    39.20
26105    39.02
26106    37.40
26107    37.40
26108    37.40
26109    37.04
26110    35.06
26111    33.98
26112    33.98
26113    33.98
26114    33.98
26115    33.08
26116    33.08
26117    33.98
26118    35.06
26119    33.98
26120    33.08
26121    33.80
26122    28.40
26123    23.00
26124    21.92
26125    19.94
26126    17.06
26127    15.08
26128    12.92
26129    10.94
Name: dewp, Length: 26130, dtype: float64

In [22]:
Weatherc3.loc[5596, ]

41.385399364690429

In [23]:
dewpc3 = Weatherc3
print(dewpc3)

#I guess I am renaming these for some reason

0        21.92
1        21.92
2        21.92
3        23.00
4        24.08
5        26.06
6        26.96
7        28.04
8        28.04
9        28.04
10       28.04
11       28.04
12       28.04
13       28.04
14       28.04
15       26.96
16       28.40
17       28.40
18       24.08
19       24.08
20       19.94
21       19.04
22       15.08
23       12.92
24       15.08
25       12.92
26       12.02
27       10.94
28       10.94
29       10.94
         ...
26100    37.40
26101    37.40
26102    39.02
26103    37.94
26104    39.20
26105    39.02
26106    37.40
26107    37.40
26108    37.40
26109    37.04
26110    35.06
26111    33.98
26112    33.98
26113    33.98
26114    33.98
26115    33.08
26116    33.08
26117    33.98
26118    35.06
26119    33.98
26120    33.08
26121    33.80
26122    28.40
26123    23.00
26124    21.92
26125    19.94
26126    17.06
26127    15.08
26128    12.92
26129    10.94
Name: dewp, Length: 26130, dtype: float64

In [25]:
humidc3 = Weather["humid"].fillna(c)
print(humidc3)

0        53.97
1        53.97
2        52.09
3        54.51
4        57.04
5        59.37
6        61.63
7        64.43
8        62.21
9        64.43
10       67.21
11       64.43
12       62.21
13       62.21
14       59.65
15       57.06
16       64.93
17       64.93
18       54.68
19       57.04
20       49.62
21       49.83
22       45.43
23       42.84
24       49.19
25       48.48
26       48.69
27       48.15
28       50.34
29       52.25
         ...
26100    81.07
26101    93.19
26102    92.59
26103    88.76
26104    93.24
26105    88.81
26106    81.07
26107    86.89
26108    81.07
26109    79.38
26110    73.39
26111    72.78
26112    72.78
26113    75.88
26114    70.30
26115    73.19
26116    67.81
26117    70.30
26118    70.42
26119    67.45
26120    65.07
26121    70.28
26122    60.54
26123    54.51
26124    53.97
26125    51.78
26126    49.51
26127    49.19
26128    46.74
26129    46.41
Name: humid, Length: 26130, dtype: float64

In [26]:
humidc3.loc[5596, ]

62.347321749779368

In [30]:
wind_dirc3 = Weather["wind_dir"].fillna(d)
print(wind_dirc3)

0        230.0
1        230.0
2        230.0
3        230.0
4        240.0
5        270.0
6        250.0
7        240.0
8        250.0
9        260.0
10       240.0
11       240.0
12       250.0
13       260.0
14       260.0
15       260.0
16       270.0
17       330.0
18       280.0
19       290.0
20       300.0
21       330.0
22       310.0
23       320.0
24       310.0
25       320.0
26       320.0
27       310.0
28       310.0
29       330.0
         ...
26100     70.0
26101     40.0
26102     40.0
26103    350.0
26104     50.0
26105    330.0
26106    320.0
26107    310.0
26108    320.0
26109    300.0
26110    310.0
26111    320.0
26112    250.0
26113    240.0
26114    270.0
26115      0.0
26116    250.0
26117    230.0
26118    240.0
26119    260.0
26120    260.0
26121    330.0
26122    340.0
26123    330.0
26124    340.0
26125    340.0
26126    330.0
26127    340.0
26128    320.0
26129    330.0
Name: wind_dir, Length: 26130, dtype: float64

In [31]:
wind_dirc3.loc[1787:1790, ]

1787    198.066661
1788    198.066661
1789    198.066661
1790    198.066661
Name: wind_dir, dtype: float64

In [32]:
wind_speedc3 = Weather["wind_speed"].fillna(e)
print(wind_speedc3)

0        10.35702
1        13.80936
2        12.65858
3        13.80936
4        14.96014
5        10.35702
6         8.05546
7        11.50780
8        12.65858
9        12.65858
10       11.50780
11       14.96014
12       10.35702
13       14.96014
14       13.80936
15       14.96014
16       16.11092
17       14.96014
18       13.80936
19        9.20624
20       13.80936
21       11.50780
22       12.65858
23       10.35702
24       14.96014
25       18.41248
26       18.41248
27       16.11092
28       14.96014
29       12.65858
           ...
26100     9.20624
26101    16.11092
26102    13.80936
26103     8.05546
26104    20.71404
26105    14.96014
26106    17.26170
26107    19.56326
26108    16.11092
26109     9.20624
26110    17.26170
26111    11.50780
26112     9.20624
26113     8.05546
26114     9.20624
26115     0.00000
26116    10.35702
26117     6.90468
26118    11.50780
26119    11.50780
26120    13.80936
26121    16.11092
26122    13.80936
26123    21.86482
26124    17.26170
26125    13.80936
26126    17.26170
26127    14.96014
26128    17.26170
26129    18.41248
Name: wind_speed, Length: 26130, dtype: float64

In [33]:
wind_speedc3.loc[13513, ]

10.39586823975324

In [34]:
wind_gustc3 = Weather["wind_gust"].fillna(f)
print(wind_gustc3)

0        11.918651
1        15.891535
2        14.567241
3        15.891535
4        17.215830
5        11.918651
6         9.270062
7        13.242946
8        14.567241
9        14.567241
10       13.242946
11       17.215830
12       11.918651
13       17.215830
14       15.891535
15       17.215830
16       18.540125
17       17.215830
18       15.891535
19       10.594357
20       15.891535
21       13.242946
22       14.567241
23       11.918651
24       17.215830
25       21.188714
26       21.188714
27       18.540125
28       17.215830
29       14.567241
           ...
26100    10.594357
26101    18.540125
26102    15.891535
26103     9.270062
26104    23.837303
26105    17.215830
26106    19.864419
26107    22.513008
26108    18.540125
26109    10.594357
26110    19.864419
26111    13.242946
26112    10.594357
26113     9.270062
26114    10.594357
26115     0.000000
26116    11.918651
26117     7.945768
26118    13.242946
26119    13.242946
26120    15.891535
26121    18.540125
26122    15.891535
26123    25.161598
26124    19.864419
26125    15.891535
26126    19.864419
26127    17.215830
26128    19.864419
26129    21.188714
Name: wind_gust, Length: 26130, dtype: float64

In [35]:
wind_gustc3.loc[2057, ]

11.963357253109523

In [38]:
pressurec3 = Weather["pressure"].fillna(e)
print(pressurec3)

0        1013.900000
1        1013.000000
2        1012.600000
3        1012.700000
4        1012.800000
5        1012.000000
6        1012.300000
7        1012.500000
8        1012.200000
9        1011.900000
10       1012.400000
11       1012.200000
12       1012.200000
13       1012.700000
14       1012.400000
15       1011.400000
16         10.395868
17         10.395868
18       1010.800000
19       1011.900000
20       1012.100000
21       1013.200000
22       1014.100000
23       1014.400000
24       1015.200000
25       1016.000000
26       1016.500000
27       1016.400000
28       1016.300000
29       1016.300000
            ...
26100      10.395868
26101      10.395868
26102     999.900000
26103     998.700000
26104      10.395868
26105     997.200000
26106      10.395868
26107      10.395868
26108      10.395868
26109    1003.800000
26110    1005.100000
26111    1005.900000
26112    1007.600000
26113    1008.300000
26114    1008.200000
26115    1008.900000
26116    1009.200000
26117    1010.800000
26118    1011.900000
26119    1012.900000
26120    1013.700000
26121      10.395868
26122      10.395868
26123    1015.700000
26124    1016.500000
26125    1017.100000
26126    1018.800000
26127    1019.500000
26128    1019.900000
26129    1020.900000
Name: pressure, Length: 26130, dtype: float64

In [39]:
pressurec3.loc[1300:1310, ]

1300      10.395868
1301      10.395868
1302    1007.800000
1303      10.395868
1304      10.395868
1305    1008.500000
1306      10.395868
1307      10.395868
1308      10.395868
1309    1007.600000
1310    1007.500000
Name: pressure, dtype: float64

In [41]:
#Now that I have modified columns for the missing data, I can remove the columns that have missing data in the original dataframe

WeatherN2 = Weather.filter(['Unnamed: 0', 'origin', 'year', 'month', 'day', 'hour', 'precip', 'visib', 'time_hour'], axis=1)
print(WeatherN2)

      origin  year  month  day  hour  precip  visib         time_hour
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00
...      ...   ...    ...  ...   ...     ...    ...               ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00

[26130 rows x 8 columns]

In [42]:
#Now I need to input the cleaned data back into the dataframe
#I start with just inputting one new column

WeatherN3 = WeatherN2.assign(temp=tempc3.values)
print(WeatherN3)

      origin  year  month  day  hour  precip  visib         time_hour   temp
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00  37.04
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00  37.04
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00  37.94
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00  37.94
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00  37.94
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00  39.02
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00  39.02
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00  39.02
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00  39.92
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00  39.02
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00  37.94
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00  39.02
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00  39.92
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00  39.92
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00  41.00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00  41.00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00  39.20
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00  39.20
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00  39.02
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00  37.94
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00  37.04
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00  35.96
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00  33.98
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00  33.08
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00  32.00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00  30.02
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00  28.94
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00  28.04
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00  26.96
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00  26.06
...      ...   ...    ...  ...   ...     ...    ...               ...    ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00  42.80
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00  39.20
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00  41.00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00  41.00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00  41.00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00  42.08
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00  42.80
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00  41.00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00  42.80
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00  42.98
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00  42.98
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00  42.08
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00  42.08
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00  41.00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00  42.98
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00  41.00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00  42.98
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00  42.98
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00  44.06
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00  44.06
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00  44.06
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00  42.80
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00  41.00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00  37.94
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00  37.04
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00  35.96
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00  33.98
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00  32.00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00  30.92
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00  28.94

[26130 rows x 9 columns]

In [43]:
#Now that I got the function to work for one column, I use the assign command to input all of the new columns

WeatherN4 = WeatherN3.assign(dewp=dewpc3.values, humid=humidc3.values, wind_dir=wind_dirc3.values, wind_speed=wind_speedc3.values, wind_gust=wind_gustc3.values, pressure=pressurec3.values)
print(WeatherN4)

      origin  year  month  day  hour  precip  visib         time_hour   temp  \
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00  37.04
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00  37.04
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00  37.94
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00  37.94
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00  37.94
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00  39.02
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00  39.02
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00  39.02
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00  39.92
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00  39.02
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00  37.94
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00  39.02
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00  39.92
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00  39.92
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00  41.00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00  41.00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00  39.20
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00  39.20
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00  39.02
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00  37.94
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00  37.04
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00  35.96
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00  33.98
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00  33.08
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00  32.00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00  30.02
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00  28.94
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00  28.04
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00  26.96
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00  26.06
...      ...   ...    ...  ...   ...     ...    ...               ...    ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00  42.80
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00  39.20
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00  41.00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00  41.00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00  41.00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00  42.08
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00  42.80
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00  41.00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00  42.80
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00  42.98
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00  42.98
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00  42.08
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00  42.08
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00  41.00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00  42.98
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00  41.00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00  42.98
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00  42.98
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00  44.06
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00  44.06
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00  44.06
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00  42.80
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00  41.00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00  37.94
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00  37.04
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00  35.96
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00  33.98
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00  32.00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00  30.92
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00  28.94

        dewp  humid     pressure  wind_dir  wind_gust  wind_speed
0      21.92  53.97  1013.900000     230.0  11.918651    10.35702
1      21.92  53.97  1013.000000     230.0  15.891535    13.80936
2      21.92  52.09  1012.600000     230.0  14.567241    12.65858
3      23.00  54.51  1012.700000     230.0  15.891535    13.80936
4      24.08  57.04  1012.800000     240.0  17.215830    14.96014
5      26.06  59.37  1012.000000     270.0  11.918651    10.35702
6      26.96  61.63  1012.300000     250.0   9.270062     8.05546
7      28.04  64.43  1012.500000     240.0  13.242946    11.50780
8      28.04  62.21  1012.200000     250.0  14.567241    12.65858
9      28.04  64.43  1011.900000     260.0  14.567241    12.65858
10     28.04  67.21  1012.400000     240.0  13.242946    11.50780
11     28.04  64.43  1012.200000     240.0  17.215830    14.96014
12     28.04  62.21  1012.200000     250.0  11.918651    10.35702
13     28.04  62.21  1012.700000     260.0  17.215830    14.96014
14     28.04  59.65  1012.400000     260.0  15.891535    13.80936
15     26.96  57.06  1011.400000     260.0  17.215830    14.96014
16     28.40  64.93    10.395868     270.0  18.540125    16.11092
17     28.40  64.93    10.395868     330.0  17.215830    14.96014
18     24.08  54.68  1010.800000     280.0  15.891535    13.80936
19     24.08  57.04  1011.900000     290.0  10.594357     9.20624
20     19.94  49.62  1012.100000     300.0  15.891535    13.80936
21     19.04  49.83  1013.200000     330.0  13.242946    11.50780
22     15.08  45.43  1014.100000     310.0  14.567241    12.65858
23     12.92  42.84  1014.400000     320.0  11.918651    10.35702
24     15.08  49.19  1015.200000     310.0  17.215830    14.96014
25     12.92  48.48  1016.000000     320.0  21.188714    18.41248
26     12.02  48.69  1016.500000     320.0  21.188714    18.41248
27     10.94  48.15  1016.400000     310.0  18.540125    16.11092
28     10.94  50.34  1016.300000     310.0  17.215830    14.96014
29     10.94  52.25  1016.300000     330.0  14.567241    12.65858
...      ...    ...          ...       ...        ...         ...
26100  37.40  81.07    10.395868      70.0  10.594357     9.20624
26101  37.40  93.19    10.395868      40.0  18.540125    16.11092
26102  39.02  92.59   999.900000      40.0  15.891535    13.80936
26103  37.94  88.76   998.700000     350.0   9.270062     8.05546
26104  39.20  93.24    10.395868      50.0  23.837303    20.71404
26105  39.02  88.81   997.200000     330.0  17.215830    14.96014
26106  37.40  81.07    10.395868     320.0  19.864419    17.26170
26107  37.40  86.89    10.395868     310.0  22.513008    19.56326
26108  37.40  81.07    10.395868     320.0  18.540125    16.11092
26109  37.04  79.38  1003.800000     300.0  10.594357     9.20624
26110  35.06  73.39  1005.100000     310.0  19.864419    17.26170
26111  33.98  72.78  1005.900000     320.0  13.242946    11.50780
26112  33.98  72.78  1007.600000     250.0  10.594357     9.20624
26113  33.98  75.88  1008.300000     240.0   9.270062     8.05546
26114  33.98  70.30  1008.200000     270.0  10.594357     9.20624
26115  33.08  73.19  1008.900000       0.0   0.000000     0.00000
26116  33.08  67.81  1009.200000     250.0  11.918651    10.35702
26117  33.98  70.30  1010.800000     230.0   7.945768     6.90468
26118  35.06  70.42  1011.900000     240.0  13.242946    11.50780
26119  33.98  67.45  1012.900000     260.0  13.242946    11.50780
26120  33.08  65.07  1013.700000     260.0  15.891535    13.80936
26121  33.80  70.28    10.395868     330.0  18.540125    16.11092
26122  28.40  60.54    10.395868     340.0  15.891535    13.80936
26123  23.00  54.51  1015.700000     330.0  25.161598    21.86482
26124  21.92  53.97  1016.500000     340.0  19.864419    17.26170
26125  19.94  51.78  1017.100000     340.0  15.891535    13.80936
26126  17.06  49.51  1018.800000     330.0  19.864419    17.26170
26127  15.08  49.19  1019.500000     340.0  17.215830    14.96014
26128  12.92  46.74  1019.900000     320.0  19.864419    17.26170
26129  10.94  46.41  1020.900000     330.0  21.188714    18.41248

[26130 rows x 15 columns]

In [44]:
#I want the cleaned dataframe to be called WeatherC

WeatherC = WeatherN4
print(WeatherC)

      origin  year  month  day  hour  precip  visib         time_hour   temp  \
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00  37.04
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00  37.04
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00  37.94
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00  37.94
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00  37.94
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00  39.02
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00  39.02
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00  39.02
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00  39.92
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00  39.02
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00  37.94
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00  39.02
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00  39.92
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00  39.92
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00  41.00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00  41.00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00  39.20
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00  39.20
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00  39.02
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00  37.94
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00  37.04
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00  35.96
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00  33.98
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00  33.08
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00  32.00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00  30.02
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00  28.94
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00  28.04
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00  26.96
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00  26.06
...      ...   ...    ...  ...   ...     ...    ...               ...    ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00  42.80
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00  39.20
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00  41.00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00  41.00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00  41.00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00  42.08
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00  42.80
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00  41.00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00  42.80
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00  42.98
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00  42.98
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00  42.08
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00  42.08
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00  41.00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00  42.98
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00  41.00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00  42.98
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00  42.98
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00  44.06
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00  44.06
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00  44.06
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00  42.80
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00  41.00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00  37.94
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00  37.04
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00  35.96
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00  33.98
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00  32.00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00  30.92
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00  28.94

        dewp  humid     pressure  wind_dir  wind_gust  wind_speed
0      21.92  53.97  1013.900000     230.0  11.918651    10.35702
1      21.92  53.97  1013.000000     230.0  15.891535    13.80936
2      21.92  52.09  1012.600000     230.0  14.567241    12.65858
3      23.00  54.51  1012.700000     230.0  15.891535    13.80936
4      24.08  57.04  1012.800000     240.0  17.215830    14.96014
5      26.06  59.37  1012.000000     270.0  11.918651    10.35702
6      26.96  61.63  1012.300000     250.0   9.270062     8.05546
7      28.04  64.43  1012.500000     240.0  13.242946    11.50780
8      28.04  62.21  1012.200000     250.0  14.567241    12.65858
9      28.04  64.43  1011.900000     260.0  14.567241    12.65858
10     28.04  67.21  1012.400000     240.0  13.242946    11.50780
11     28.04  64.43  1012.200000     240.0  17.215830    14.96014
12     28.04  62.21  1012.200000     250.0  11.918651    10.35702
13     28.04  62.21  1012.700000     260.0  17.215830    14.96014
14     28.04  59.65  1012.400000     260.0  15.891535    13.80936
15     26.96  57.06  1011.400000     260.0  17.215830    14.96014
16     28.40  64.93    10.395868     270.0  18.540125    16.11092
17     28.40  64.93    10.395868     330.0  17.215830    14.96014
18     24.08  54.68  1010.800000     280.0  15.891535    13.80936
19     24.08  57.04  1011.900000     290.0  10.594357     9.20624
20     19.94  49.62  1012.100000     300.0  15.891535    13.80936
21     19.04  49.83  1013.200000     330.0  13.242946    11.50780
22     15.08  45.43  1014.100000     310.0  14.567241    12.65858
23     12.92  42.84  1014.400000     320.0  11.918651    10.35702
24     15.08  49.19  1015.200000     310.0  17.215830    14.96014
25     12.92  48.48  1016.000000     320.0  21.188714    18.41248
26     12.02  48.69  1016.500000     320.0  21.188714    18.41248
27     10.94  48.15  1016.400000     310.0  18.540125    16.11092
28     10.94  50.34  1016.300000     310.0  17.215830    14.96014
29     10.94  52.25  1016.300000     330.0  14.567241    12.65858
...      ...    ...          ...       ...        ...         ...
26100  37.40  81.07    10.395868      70.0  10.594357     9.20624
26101  37.40  93.19    10.395868      40.0  18.540125    16.11092
26102  39.02  92.59   999.900000      40.0  15.891535    13.80936
26103  37.94  88.76   998.700000     350.0   9.270062     8.05546
26104  39.20  93.24    10.395868      50.0  23.837303    20.71404
26105  39.02  88.81   997.200000     330.0  17.215830    14.96014
26106  37.40  81.07    10.395868     320.0  19.864419    17.26170
26107  37.40  86.89    10.395868     310.0  22.513008    19.56326
26108  37.40  81.07    10.395868     320.0  18.540125    16.11092
26109  37.04  79.38  1003.800000     300.0  10.594357     9.20624
26110  35.06  73.39  1005.100000     310.0  19.864419    17.26170
26111  33.98  72.78  1005.900000     320.0  13.242946    11.50780
26112  33.98  72.78  1007.600000     250.0  10.594357     9.20624
26113  33.98  75.88  1008.300000     240.0   9.270062     8.05546
26114  33.98  70.30  1008.200000     270.0  10.594357     9.20624
26115  33.08  73.19  1008.900000       0.0   0.000000     0.00000
26116  33.08  67.81  1009.200000     250.0  11.918651    10.35702
26117  33.98  70.30  1010.800000     230.0   7.945768     6.90468
26118  35.06  70.42  1011.900000     240.0  13.242946    11.50780
26119  33.98  67.45  1012.900000     260.0  13.242946    11.50780
26120  33.08  65.07  1013.700000     260.0  15.891535    13.80936
26121  33.80  70.28    10.395868     330.0  18.540125    16.11092
26122  28.40  60.54    10.395868     340.0  15.891535    13.80936
26123  23.00  54.51  1015.700000     330.0  25.161598    21.86482
26124  21.92  53.97  1016.500000     340.0  19.864419    17.26170
26125  19.94  51.78  1017.100000     340.0  15.891535    13.80936
26126  17.06  49.51  1018.800000     330.0  19.864419    17.26170
26127  15.08  49.19  1019.500000     340.0  17.215830    14.96014
26128  12.92  46.74  1019.900000     320.0  19.864419    17.26170
26129  10.94  46.41  1020.900000     330.0  21.188714    18.41248

[26130 rows x 15 columns]

In [45]:
#I also need to clean the Flights dataset through the same process

g = Flight["dep_time"].mean()
h = Flight["dep_delay"].mean()
i = Flight["arr_time"].mean()
j = Flight["arr_delay"].mean()
k = Flight["air_time"].mean()
print(g, h, i, j, k)

1349.1099473093045 12.639070257304708 1502.0549985825894 6.89537675731489 150.68646019807787

In [46]:
l = Flight["dep_time"].fillna(g)
print(l)

0          517.000000
1          533.000000
2          542.000000
3          544.000000
4          554.000000
5          554.000000
6          555.000000
7          557.000000
8          557.000000
9          558.000000
10         558.000000
11         558.000000
12         558.000000
13         558.000000
14         559.000000
15         559.000000
16         559.000000
17         600.000000
18         600.000000
19         601.000000
20         602.000000
21         602.000000
22         606.000000
23         606.000000
24         607.000000
25         608.000000
26         611.000000
27         613.000000
28         615.000000
29         615.000000
             ...
336746    2123.000000
336747    2127.000000
336748    2128.000000
336749    2129.000000
336750    2131.000000
336751    2140.000000
336752    2142.000000
336753    2145.000000
336754    2147.000000
336755    2149.000000
336756    2150.000000
336757    2159.000000
336758    2203.000000
336759    2207.000000
336760    2211.000000
336761    2231.000000
336762    2233.000000
336763    2235.000000
336764    2237.000000
336765    2240.000000
336766    2240.000000
336767    2241.000000
336768    2307.000000
336769    2349.000000
336770    1349.109947
336771    1349.109947
336772    1349.109947
336773    1349.109947
336774    1349.109947
336775    1349.109947
Name: dep_time, Length: 336776, dtype: float64

In [47]:
l.loc[9751:9762, ]

9751    1349.109947
9752    1349.109947
9753    1349.109947
9754    1349.109947
9755    1349.109947
9756    1349.109947
9757    1349.109947
9758    1349.109947
9759    1349.109947
9760    1349.109947
9761    1349.109947
9762      30.000000
Name: dep_time, dtype: float64

In [48]:
m = Flight["dep_delay"].fillna(h)
print(m)

0           2.00000
1           4.00000
2           2.00000
3          -1.00000
4          -6.00000
5          -4.00000
6          -5.00000
7          -3.00000
8          -3.00000
9          -2.00000
10         -2.00000
11         -2.00000
12         -2.00000
13         -2.00000
14         -1.00000
15          0.00000
16         -1.00000
17          0.00000
18          0.00000
19          1.00000
20         -8.00000
21         -3.00000
22         -4.00000
23         -4.00000
24          0.00000
25          8.00000
26         11.00000
27          3.00000
28          0.00000
29          0.00000
            ...
336746     -2.00000
336747     -2.00000
336748     -2.00000
336749     30.00000
336750     -9.00000
336751      0.00000
336752     13.00000
336753      0.00000
336754     10.00000
336755     -7.00000
336756     -9.00000
336757    194.00000
336758     -2.00000
336759     27.00000
336760     72.00000
336761    -14.00000
336762     80.00000
336763    154.00000
336764     -8.00000
336765     -5.00000
336766    -10.00000
336767     -5.00000
336768     12.00000
336769    -10.00000
336770     12.63907
336771     12.63907
336772     12.63907
336773     12.63907
336774     12.63907
336775     12.63907
Name: dep_delay, Length: 336776, dtype: float64

In [49]:
m.loc[11264:11280, ]

11264    12.63907
11265    12.63907
11266    12.63907
11267    12.63907
11268    12.63907
11269    12.63907
11270    12.63907
11271    12.63907
11272    12.63907
11273    12.63907
11274    12.63907
11275    12.63907
11276    12.63907
11277    12.63907
11278    12.63907
11279    12.63907
11280    -7.00000
Name: dep_delay, dtype: float64

In [50]:
n = Flight["arr_time"].fillna(i)
print(n)

0          830.000000
1          850.000000
2          923.000000
3         1004.000000
4          812.000000
5          740.000000
6          913.000000
7          709.000000
8          838.000000
9          753.000000
10         849.000000
11         853.000000
12         924.000000
13         923.000000
14         941.000000
15         702.000000
16         854.000000
17         851.000000
18         837.000000
19         844.000000
20         812.000000
21         821.000000
22         858.000000
23         837.000000
24         858.000000
25         807.000000
26         945.000000
27         925.000000
28        1039.000000
29         833.000000
             ...
336746    2223.000000
336747    2314.000000
336748    2328.000000
336749    2230.000000
336750    2225.000000
336751      10.000000
336752    2250.000000
336753     115.000000
336754      30.000000
336755    2245.000000
336756    2250.000000
336757    2344.000000
336758    2339.000000
336759    2257.000000
336760    2339.000000
336761    2335.000000
336762     112.000000
336763      59.000000
336764    2345.000000
336765    2334.000000
336766    2347.000000
336767    2345.000000
336768    2359.000000
336769     325.000000
336770    1502.054999
336771    1502.054999
336772    1502.054999
336773    1502.054999
336774    1502.054999
336775    1502.054999
Name: arr_time, Length: 336776, dtype: float64

In [51]:
n.loc[11264:11280, ]

11264    1502.054999
11265    1502.054999
11266    1502.054999
11267    1502.054999
11268    1502.054999
11269    1502.054999
11270    1502.054999
11271    1502.054999
11272    1502.054999
11273    1502.054999
11274    1502.054999
11275    1502.054999
11276    1502.054999
11277    1502.054999
11278    1502.054999
11279    1502.054999
11280     640.000000
Name: arr_time, dtype: float64

In [52]:
o = Flight["arr_delay"].fillna(j)
print(o)

0          11.000000
1          20.000000
2          33.000000
3         -18.000000
4         -25.000000
5          12.000000
6          19.000000
7         -14.000000
8          -8.000000
9           8.000000
10         -2.000000
11         -3.000000
12          7.000000
13        -14.000000
14         31.000000
15         -4.000000
16         -8.000000
17         -7.000000
18         12.000000
19         -6.000000
20         -8.000000
21         16.000000
22        -12.000000
23         -8.000000
24        -17.000000
25         32.000000
26         14.000000
27          4.000000
28        -21.000000
29         -9.000000
             ...
336746    -24.000000
336747     -9.000000
336748    -31.000000
336749     -2.000000
336750    -30.000000
336751    -30.000000
336752     11.000000
336753    -25.000000
336754      3.000000
336755    -23.000000
336756    -16.000000
336757    194.000000
336758      8.000000
336759      7.000000
336760     57.000000
336761    -21.000000
336762     42.000000
336763    130.000000
336764     -8.000000
336765    -17.000000
336766    -20.000000
336767    -16.000000
336768      1.000000
336769    -25.000000
336770      6.895377
336771      6.895377
336772      6.895377
336773      6.895377
336774      6.895377
336775      6.895377
Name: arr_delay, Length: 336776, dtype: float64

In [53]:
o.loc[2689:2700, ]

2689      6.895377
2690      6.895377
2691      6.895377
2692      6.895377
2693      6.895377
2694      6.895377
2695      6.895377
2696      6.895377
2697      6.895377
2698      6.895377
2699     23.000000
2700    125.000000
Name: arr_delay, dtype: float64

In [54]:
p = Flight["air_time"].fillna(k)
print(p)

0         227.00000
1         227.00000
2         160.00000
3         183.00000
4         116.00000
5         150.00000
6         158.00000
7          53.00000
8         140.00000
9         138.00000
10        149.00000
11        158.00000
12        345.00000
13        361.00000
14        257.00000
15         44.00000
16        337.00000
17        152.00000
18        134.00000
19        147.00000
20        170.00000
21        105.00000
22        152.00000
23        128.00000
24        157.00000
25        139.00000
26        366.00000
27        175.00000
28        182.00000
29        120.00000
            ...
336746     45.00000
336747     72.00000
336748    213.00000
336749     45.00000
336750     36.00000
336751    298.00000
336752     47.00000
336753    192.00000
336754    139.00000
336755     37.00000
336756     39.00000
336757     50.00000
336758     61.00000
336759     97.00000
336760    120.00000
336761     48.00000
336762    318.00000
336763    123.00000
336764     43.00000
336765     41.00000
336766     52.00000
336767     47.00000
336768     33.00000
336769    196.00000
336770    150.68646
336771    150.68646
336772    150.68646
336773    150.68646
336774    150.68646
336775    150.68646
Name: air_time, Length: 336776, dtype: float64

In [55]:
p.loc[13958:13986, ]

13958    150.68646
13959    150.68646
13960    150.68646
13961    150.68646
13962    150.68646
13963    150.68646
13964    150.68646
13965    150.68646
13966    150.68646
13967    150.68646
13968    150.68646
13969    150.68646
13970    150.68646
13971    150.68646
13972    150.68646
13973    150.68646
13974    150.68646
13975    150.68646
13976    150.68646
13977    150.68646
13978    150.68646
13979    150.68646
13980    150.68646
13981    150.68646
13982    150.68646
13983    150.68646
13984    150.68646
13985    150.68646
13986    150.68646
Name: air_time, dtype: float64

In [56]:
#Now that I have cleaned the columns with missing data, I need to removed the columns with missing data from the original dataframe
#I also dropped the tailnum column because it has missing values and does not provide value for the requested analysis

FlightN2 = Flight.filter(['Column1', 'year', 'month', 'day', 'sched_dep_time', 'sched_arr_time', 'carrier', 'flight', 'origin', 'dest', 'distance', 'hour', 'minute', 'time_hour'], axis=1)
print(FlightN2)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

[336776 rows x 14 columns]

In [58]:
#I also need to add the cleaned columns back to the data frame
#one column at a time first

FlightN3 = FlightN2.assign(dep_time=l.values)
print(FlightN3)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time
0        517.000000
1        533.000000
2        542.000000
3        544.000000
4        554.000000
5        554.000000
6        555.000000
7        557.000000
8        557.000000
9        558.000000
10       558.000000
11       558.000000
12       558.000000
13       558.000000
14       559.000000
15       559.000000
16       559.000000
17       600.000000
18       600.000000
19       601.000000
20       602.000000
21       602.000000
22       606.000000
23       606.000000
24       607.000000
25       608.000000
26       611.000000
27       613.000000
28       615.000000
29       615.000000
...             ...
336746  2123.000000
336747  2127.000000
336748  2128.000000
336749  2129.000000
336750  2131.000000
336751  2140.000000
336752  2142.000000
336753  2145.000000
336754  2147.000000
336755  2149.000000
336756  2150.000000
336757  2159.000000
336758  2203.000000
336759  2207.000000
336760  2211.000000
336761  2231.000000
336762  2233.000000
336763  2235.000000
336764  2237.000000
336765  2240.000000
336766  2240.000000
336767  2241.000000
336768  2307.000000
336769  2349.000000
336770  1349.109947
336771  1349.109947
336772  1349.109947
336773  1349.109947
336774  1349.109947
336775  1349.109947

[336776 rows x 15 columns]

In [59]:
#Now I will assign the remaining cleaned columns to the dataframe

FlightN4 = FlightN3.assign(dep_delay=m.values, arr_time=n.values, arr_delay=o.values, air_time=p.values)
print(FlightN4)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time   air_time   arr_delay     arr_time  dep_delay
0        517.000000  227.00000   11.000000   830.000000    2.00000
1        533.000000  227.00000   20.000000   850.000000    4.00000
2        542.000000  160.00000   33.000000   923.000000    2.00000
3        544.000000  183.00000  -18.000000  1004.000000   -1.00000
4        554.000000  116.00000  -25.000000   812.000000   -6.00000
5        554.000000  150.00000   12.000000   740.000000   -4.00000
6        555.000000  158.00000   19.000000   913.000000   -5.00000
7        557.000000   53.00000  -14.000000   709.000000   -3.00000
8        557.000000  140.00000   -8.000000   838.000000   -3.00000
9        558.000000  138.00000    8.000000   753.000000   -2.00000
10       558.000000  149.00000   -2.000000   849.000000   -2.00000
11       558.000000  158.00000   -3.000000   853.000000   -2.00000
12       558.000000  345.00000    7.000000   924.000000   -2.00000
13       558.000000  361.00000  -14.000000   923.000000   -2.00000
14       559.000000  257.00000   31.000000   941.000000   -1.00000
15       559.000000   44.00000   -4.000000   702.000000    0.00000
16       559.000000  337.00000   -8.000000   854.000000   -1.00000
17       600.000000  152.00000   -7.000000   851.000000    0.00000
18       600.000000  134.00000   12.000000   837.000000    0.00000
19       601.000000  147.00000   -6.000000   844.000000    1.00000
20       602.000000  170.00000   -8.000000   812.000000   -8.00000
21       602.000000  105.00000   16.000000   821.000000   -3.00000
22       606.000000  152.00000  -12.000000   858.000000   -4.00000
23       606.000000  128.00000   -8.000000   837.000000   -4.00000
24       607.000000  157.00000  -17.000000   858.000000    0.00000
25       608.000000  139.00000   32.000000   807.000000    8.00000
26       611.000000  366.00000   14.000000   945.000000   11.00000
27       613.000000  175.00000    4.000000   925.000000    3.00000
28       615.000000  182.00000  -21.000000  1039.000000    0.00000
29       615.000000  120.00000   -9.000000   833.000000    0.00000
...             ...        ...         ...          ...        ...
336746  2123.000000   45.00000  -24.000000  2223.000000   -2.00000
336747  2127.000000   72.00000   -9.000000  2314.000000   -2.00000
336748  2128.000000  213.00000  -31.000000  2328.000000   -2.00000
336749  2129.000000   45.00000   -2.000000  2230.000000   30.00000
336750  2131.000000   36.00000  -30.000000  2225.000000   -9.00000
336751  2140.000000  298.00000  -30.000000    10.000000    0.00000
336752  2142.000000   47.00000   11.000000  2250.000000   13.00000
336753  2145.000000  192.00000  -25.000000   115.000000    0.00000
336754  2147.000000  139.00000    3.000000    30.000000   10.00000
336755  2149.000000   37.00000  -23.000000  2245.000000   -7.00000
336756  2150.000000   39.00000  -16.000000  2250.000000   -9.00000
336757  2159.000000   50.00000  194.000000  2344.000000  194.00000
336758  2203.000000   61.00000    8.000000  2339.000000   -2.00000
336759  2207.000000   97.00000    7.000000  2257.000000   27.00000
336760  2211.000000  120.00000   57.000000  2339.000000   72.00000
336761  2231.000000   48.00000  -21.000000  2335.000000  -14.00000
336762  2233.000000  318.00000   42.000000   112.000000   80.00000
336763  2235.000000  123.00000  130.000000    59.000000  154.00000
336764  2237.000000   43.00000   -8.000000  2345.000000   -8.00000
336765  2240.000000   41.00000  -17.000000  2334.000000   -5.00000
336766  2240.000000   52.00000  -20.000000  2347.000000  -10.00000
336767  2241.000000   47.00000  -16.000000  2345.000000   -5.00000
336768  2307.000000   33.00000    1.000000  2359.000000   12.00000
336769  2349.000000  196.00000  -25.000000   325.000000  -10.00000
336770  1349.109947  150.68646    6.895377  1502.054999   12.63907
336771  1349.109947  150.68646    6.895377  1502.054999   12.63907
336772  1349.109947  150.68646    6.895377  1502.054999   12.63907
336773  1349.109947  150.68646    6.895377  1502.054999   12.63907
336774  1349.109947  150.68646    6.895377  1502.054999   12.63907
336775  1349.109947  150.68646    6.895377  1502.054999   12.63907

[336776 rows x 19 columns]

In [60]:
#I want the cleaned dataframe to be called FlightC

FlightC = FlightN4
print(FlightC)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time   air_time   arr_delay     arr_time  dep_delay
0        517.000000  227.00000   11.000000   830.000000    2.00000
1        533.000000  227.00000   20.000000   850.000000    4.00000
2        542.000000  160.00000   33.000000   923.000000    2.00000
3        544.000000  183.00000  -18.000000  1004.000000   -1.00000
4        554.000000  116.00000  -25.000000   812.000000   -6.00000
5        554.000000  150.00000   12.000000   740.000000   -4.00000
6        555.000000  158.00000   19.000000   913.000000   -5.00000
7        557.000000   53.00000  -14.000000   709.000000   -3.00000
8        557.000000  140.00000   -8.000000   838.000000   -3.00000
9        558.000000  138.00000    8.000000   753.000000   -2.00000
10       558.000000  149.00000   -2.000000   849.000000   -2.00000
11       558.000000  158.00000   -3.000000   853.000000   -2.00000
12       558.000000  345.00000    7.000000   924.000000   -2.00000
13       558.000000  361.00000  -14.000000   923.000000   -2.00000
14       559.000000  257.00000   31.000000   941.000000   -1.00000
15       559.000000   44.00000   -4.000000   702.000000    0.00000
16       559.000000  337.00000   -8.000000   854.000000   -1.00000
17       600.000000  152.00000   -7.000000   851.000000    0.00000
18       600.000000  134.00000   12.000000   837.000000    0.00000
19       601.000000  147.00000   -6.000000   844.000000    1.00000
20       602.000000  170.00000   -8.000000   812.000000   -8.00000
21       602.000000  105.00000   16.000000   821.000000   -3.00000
22       606.000000  152.00000  -12.000000   858.000000   -4.00000
23       606.000000  128.00000   -8.000000   837.000000   -4.00000
24       607.000000  157.00000  -17.000000   858.000000    0.00000
25       608.000000  139.00000   32.000000   807.000000    8.00000
26       611.000000  366.00000   14.000000   945.000000   11.00000
27       613.000000  175.00000    4.000000   925.000000    3.00000
28       615.000000  182.00000  -21.000000  1039.000000    0.00000
29       615.000000  120.00000   -9.000000   833.000000    0.00000
...             ...        ...         ...          ...        ...
336746  2123.000000   45.00000  -24.000000  2223.000000   -2.00000
336747  2127.000000   72.00000   -9.000000  2314.000000   -2.00000
336748  2128.000000  213.00000  -31.000000  2328.000000   -2.00000
336749  2129.000000   45.00000   -2.000000  2230.000000   30.00000
336750  2131.000000   36.00000  -30.000000  2225.000000   -9.00000
336751  2140.000000  298.00000  -30.000000    10.000000    0.00000
336752  2142.000000   47.00000   11.000000  2250.000000   13.00000
336753  2145.000000  192.00000  -25.000000   115.000000    0.00000
336754  2147.000000  139.00000    3.000000    30.000000   10.00000
336755  2149.000000   37.00000  -23.000000  2245.000000   -7.00000
336756  2150.000000   39.00000  -16.000000  2250.000000   -9.00000
336757  2159.000000   50.00000  194.000000  2344.000000  194.00000
336758  2203.000000   61.00000    8.000000  2339.000000   -2.00000
336759  2207.000000   97.00000    7.000000  2257.000000   27.00000
336760  2211.000000  120.00000   57.000000  2339.000000   72.00000
336761  2231.000000   48.00000  -21.000000  2335.000000  -14.00000
336762  2233.000000  318.00000   42.000000   112.000000   80.00000
336763  2235.000000  123.00000  130.000000    59.000000  154.00000
336764  2237.000000   43.00000   -8.000000  2345.000000   -8.00000
336765  2240.000000   41.00000  -17.000000  2334.000000   -5.00000
336766  2240.000000   52.00000  -20.000000  2347.000000  -10.00000
336767  2241.000000   47.00000  -16.000000  2345.000000   -5.00000
336768  2307.000000   33.00000    1.000000  2359.000000   12.00000
336769  2349.000000  196.00000  -25.000000   325.000000  -10.00000
336770  1349.109947  150.68646    6.895377  1502.054999   12.63907
336771  1349.109947  150.68646    6.895377  1502.054999   12.63907
336772  1349.109947  150.68646    6.895377  1502.054999   12.63907
336773  1349.109947  150.68646    6.895377  1502.054999   12.63907
336774  1349.109947  150.68646    6.895377  1502.054999   12.63907
336775  1349.109947  150.68646    6.895377  1502.054999   12.63907

[336776 rows x 19 columns]

In [64]:
#Now I will print row counts for the cleaned dataframes to show that missing values have been removed

PlaneC.count()

tailnum         3322
year            3252
type            3322
manufacturer    3322
model           3322
engines         3322
seats           3322
engine          3322
dtype: int64

In [65]:
PlaneC.shape[0]

3322

In [66]:
FlightC.count()

Column1           336776
year              336776
month             336776
day               336776
sched_dep_time    336776
sched_arr_time    336776
carrier           336776
flight            336776
origin            336776
dest              336776
distance          336776
hour              336776
minute            336776
time_hour         336776
dep_time          336776
air_time          336776
arr_delay         336776
arr_time          336776
dep_delay         336776
dtype: int64

In [67]:
FlightC.shape[0]

336776

In [68]:
WeatherC.count()

origin        26130
year          26130
month         26130
day           26130
hour          26130
precip        26130
visib         26130
time_hour     26130
temp          26130
dewp          26130
humid         26130
pressure      26130
wind_dir      26130
wind_gust     26130
wind_speed    26130
dtype: int64

In [69]:
WeatherC.shape[0]

26130

In [ ]:
#This shows that all of the missing values are removed from the cleaned dataframes.

In [70]:
#Part A - ii
#Now I will find the top 5 busiest airports based on average number of arrivals per day

k = FlightC.groupby('dest').count()
print(k)

      Column1   year  month    day  sched_dep_time  sched_arr_time  carrier  \
dest
ABQ       254    254    254    254             254             254      254
ACK       265    265    265    265             265             265      265
ALB       439    439    439    439             439             439      439
ANC         8      8      8      8               8               8        8
ATL     17215  17215  17215  17215           17215           17215    17215
AUS      2439   2439   2439   2439            2439            2439     2439
AVL       275    275    275    275             275             275      275
BDL       443    443    443    443             443             443      443
BGR       375    375    375    375             375             375      375
BHM       297    297    297    297             297             297      297
BNA      6333   6333   6333   6333            6333            6333     6333
BOS     15508  15508  15508  15508           15508           15508    15508
BQN       896    896    896    896             896             896      896
BTV      2589   2589   2589   2589            2589            2589     2589
BUF      4681   4681   4681   4681            4681            4681     4681
BUR       371    371    371    371             371             371      371
BWI      1781   1781   1781   1781            1781            1781     1781
BZN        36     36     36     36              36              36       36
CAE       116    116    116    116             116             116      116
CAK       864    864    864    864             864             864      864
CHO        52     52     52     52              52              52       52
CHS      2884   2884   2884   2884            2884            2884     2884
CLE      4573   4573   4573   4573            4573            4573     4573
CLT     14064  14064  14064  14064           14064           14064    14064
CMH      3524   3524   3524   3524            3524            3524     3524
CRW       138    138    138    138             138             138      138
CVG      3941   3941   3941   3941            3941            3941     3941
DAY      1525   1525   1525   1525            1525            1525     1525
DCA      9705   9705   9705   9705            9705            9705     9705
DEN      7266   7266   7266   7266            7266            7266     7266
...       ...    ...    ...    ...             ...             ...      ...
PIT      2875   2875   2875   2875            2875            2875     2875
PSE       365    365    365    365             365             365      365
PSP        19     19     19     19              19              19       19
PVD       376    376    376    376             376             376      376
PWM      2352   2352   2352   2352            2352            2352     2352
RDU      8163   8163   8163   8163            8163            8163     8163
RIC      2454   2454   2454   2454            2454            2454     2454
ROC      2416   2416   2416   2416            2416            2416     2416
RSW      3537   3537   3537   3537            3537            3537     3537
SAN      2737   2737   2737   2737            2737            2737     2737
SAT       686    686    686    686             686             686      686
SAV       804    804    804    804             804             804      804
SBN        10     10     10     10              10              10       10
SDF      1157   1157   1157   1157            1157            1157     1157
SEA      3923   3923   3923   3923            3923            3923     3923
SFO     13331  13331  13331  13331           13331           13331    13331
SJC       329    329    329    329             329             329      329
SJU      5819   5819   5819   5819            5819            5819     5819
SLC      2467   2467   2467   2467            2467            2467     2467
SMF       284    284    284    284             284             284      284
SNA       825    825    825    825             825             825      825
SRQ      1211   1211   1211   1211            1211            1211     1211
STL      4339   4339   4339   4339            4339            4339     4339
STT       522    522    522    522             522             522      522
SYR      1761   1761   1761   1761            1761            1761     1761
TPA      7466   7466   7466   7466            7466            7466     7466
TUL       315    315    315    315             315             315      315
TVC       101    101    101    101             101             101      101
TYS       631    631    631    631             631             631      631
XNA      1036   1036   1036   1036            1036            1036     1036

      flight  origin  distance   hour  minute  time_hour  dep_time  air_time  \
dest
ABQ      254     254       254    254     254        254       254       254
ACK      265     265       265    265     265        265       265       265
ALB      439     439       439    439     439        439       439       439
ANC        8       8         8      8       8          8         8         8
ATL    17215   17215     17215  17215   17215      17215     17215     17215
AUS     2439    2439      2439   2439    2439       2439      2439      2439
AVL      275     275       275    275     275        275       275       275
BDL      443     443       443    443     443        443       443       443
BGR      375     375       375    375     375        375       375       375
BHM      297     297       297    297     297        297       297       297
BNA     6333    6333      6333   6333    6333       6333      6333      6333
BOS    15508   15508     15508  15508   15508      15508     15508     15508
BQN      896     896       896    896     896        896       896       896
BTV     2589    2589      2589   2589    2589       2589      2589      2589
BUF     4681    4681      4681   4681    4681       4681      4681      4681
BUR      371     371       371    371     371        371       371       371
BWI     1781    1781      1781   1781    1781       1781      1781      1781
BZN       36      36        36     36      36         36        36        36
CAE      116     116       116    116     116        116       116       116
CAK      864     864       864    864     864        864       864       864
CHO       52      52        52     52      52         52        52        52
CHS     2884    2884      2884   2884    2884       2884      2884      2884
CLE     4573    4573      4573   4573    4573       4573      4573      4573
CLT    14064   14064     14064  14064   14064      14064     14064     14064
CMH     3524    3524      3524   3524    3524       3524      3524      3524
CRW      138     138       138    138     138        138       138       138
CVG     3941    3941      3941   3941    3941       3941      3941      3941
DAY     1525    1525      1525   1525    1525       1525      1525      1525
DCA     9705    9705      9705   9705    9705       9705      9705      9705
DEN     7266    7266      7266   7266    7266       7266      7266      7266
...      ...     ...       ...    ...     ...        ...       ...       ...
PIT     2875    2875      2875   2875    2875       2875      2875      2875
PSE      365     365       365    365     365        365       365       365
PSP       19      19        19     19      19         19        19        19
PVD      376     376       376    376     376        376       376       376
PWM     2352    2352      2352   2352    2352       2352      2352      2352
RDU     8163    8163      8163   8163    8163       8163      8163      8163
RIC     2454    2454      2454   2454    2454       2454      2454      2454
ROC     2416    2416      2416   2416    2416       2416      2416      2416
RSW     3537    3537      3537   3537    3537       3537      3537      3537
SAN     2737    2737      2737   2737    2737       2737      2737      2737
SAT      686     686       686    686     686        686       686       686
SAV      804     804       804    804     804        804       804       804
SBN       10      10        10     10      10         10        10        10
SDF     1157    1157      1157   1157    1157       1157      1157      1157
SEA     3923    3923      3923   3923    3923       3923      3923      3923
SFO    13331   13331     13331  13331   13331      13331     13331     13331
SJC      329     329       329    329     329        329       329       329
SJU     5819    5819      5819   5819    5819       5819      5819      5819
SLC     2467    2467      2467   2467    2467       2467      2467      2467
SMF      284     284       284    284     284        284       284       284
SNA      825     825       825    825     825        825       825       825
SRQ     1211    1211      1211   1211    1211       1211      1211      1211
STL     4339    4339      4339   4339    4339       4339      4339      4339
STT      522     522       522    522     522        522       522       522
SYR     1761    1761      1761   1761    1761       1761      1761      1761
TPA     7466    7466      7466   7466    7466       7466      7466      7466
TUL      315     315       315    315     315        315       315       315
TVC      101     101       101    101     101        101       101       101
TYS      631     631       631    631     631        631       631       631
XNA     1036    1036      1036   1036    1036       1036      1036      1036

      arr_delay  arr_time  dep_delay
dest
ABQ         254       254        254
ACK         265       265        265
ALB         439       439        439
ANC           8         8          8
ATL       17215     17215      17215
AUS        2439      2439       2439
AVL         275       275        275
BDL         443       443        443
BGR         375       375        375
BHM         297       297        297
BNA        6333      6333       6333
BOS       15508     15508      15508
BQN         896       896        896
BTV        2589      2589       2589
BUF        4681      4681       4681
BUR         371       371        371
BWI        1781      1781       1781
BZN          36        36         36
CAE         116       116        116
CAK         864       864        864
CHO          52        52         52
CHS        2884      2884       2884
CLE        4573      4573       4573
CLT       14064     14064      14064
CMH        3524      3524       3524
CRW         138       138        138
CVG        3941      3941       3941
DAY        1525      1525       1525
DCA        9705      9705       9705
DEN        7266      7266       7266
...         ...       ...        ...
PIT        2875      2875       2875
PSE         365       365        365
PSP          19        19         19
PVD         376       376        376
PWM        2352      2352       2352
RDU        8163      8163       8163
RIC        2454      2454       2454
ROC        2416      2416       2416
RSW        3537      3537       3537
SAN        2737      2737       2737
SAT         686       686        686
SAV         804       804        804
SBN          10        10         10
SDF        1157      1157       1157
SEA        3923      3923       3923
SFO       13331     13331      13331
SJC         329       329        329
SJU        5819      5819       5819
SLC        2467      2467       2467
SMF         284       284        284
SNA         825       825        825
SRQ        1211      1211       1211
STL        4339      4339       4339
STT         522       522        522
SYR        1761      1761       1761
TPA        7466      7466       7466
TUL         315       315        315
TVC         101       101        101
TYS         631       631        631
XNA        1036      1036       1036

[105 rows x 18 columns]

In [71]:
#by sorting the counts from high to low, we see that ORD (O'hare), ATL (Atlanta), LAX (Los Angeles), BOS (Boston), and MCO (Orlando) have the most arrivals during 2013.
#all of the airports in the data set operate 365 days per year, so the airports with the highest total counts will also have the highest average arrivals per day.

k.sort_values(by=['Column1'], ascending=False)

,Column1,year,month,day,sched_dep_time,sched_arr_time,carrier,flight,origin,distance,hour,minute,time_hour,dep_time,air_time,arr_delay,arr_time,dep_delay
dest,,,,,,,,,,,,,,,,,,
ORD,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283
ATL,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215
LAX,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174
BOS,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508
MCO,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082
CLT,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064
SFO,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331
FLL,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055
MIA,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728
DCA,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705
DTW,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384
DFW,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738
RDU,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163
TPA,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466
DEN,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266
IAH,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198
MSP,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185
PBI,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554
BNA,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333
LAS,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997
SJU,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819
IAD,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700
BUF,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681
PHX,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656
CLE,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573
STL,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339
MDW,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113
CVG,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941
SEA,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923
MSY,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BGR,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375
BUR,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371
PSE,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365
OKC,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346
SJC,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329
TUL,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315
OAK,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312
BHM,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297
SMF,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284
AVL,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275
ACK,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265
ABQ,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254
MVY,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221
EGE,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213
CRW,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138
CAE,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116
ILM,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110
TVC,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101
MYR,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59
CHO,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52
BZN,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
JAC,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
PSP,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
EYW,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
HDN,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
MTJ,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
SBN,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
ANC,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
LGA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LEX,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
#I can just not make the datetime conversions to find the inter-arrival times. I spent hours on this to no avail.

In [ ]:
#Part A - iii
#I cannot plot the inter-arrival times because I cannot get the datetime conversions to work.

In [ ]:
#Upon completion of the data cleaning portion, I converted the cleaned data files into a csv file for import into mySQL
#These csv files got saved to my current working directory, and I was able to attempt the data import into mySQL - See Part B file

FlightC5.to_csv('FlightC5.csv')

In [ ]:
WeatherC3.to_csv('WeatherC3.csv')

In [ ]:
PlaneC.to_csv('PlaneC2.csv')