In [10]:
import mysql.connector
import pandas as pd

#import the required packages

In [11]:
Airline = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics\Week 10/Assignment 9/airlines.csv')
Airport = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/airports.csv')
Flight = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/flights.csv')
Plane = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/planes.csv')
Weather = pd.read_csv('C:/Users/Justin/Documents/Grad Courses/DNSC 6211 - Programming for Analytics/Week 10/Assignment 9/weather.csv')

#read the original csv files into pandas/jupyter

In [7]:
Airline.count()

#the count function provides information about potentially missing values within each column of the dataset for each csv file

Unnamed: 0    16
carrier       16
name          16
dtype: int64

In [8]:
Airline.shape[0]

#the shape function provides a true row count for the dataset for each csv file

16

In [9]:
Airport.count()

Unnamed: 0    1458
faa           1458
name          1458
lat           1458
lon           1458
alt           1458
tz            1458
dst           1458
tzone         1458
dtype: int64

In [10]:
Airport.shape[0]

1458

In [11]:
Flight.count()

Column1           336776
year              336776
month             336776
day               336776
dep_time          328521
sched_dep_time    336776
dep_delay         328521
arr_time          328063
sched_arr_time    336776
arr_delay         327346
carrier           336776
flight            336776
tailnum           334264
origin            336776
dest              336776
air_time          327346
distance          336776
hour              336776
minute            336776
time_hour         336776
dtype: int64

In [12]:
Flight.shape[0]

336776

In [13]:
Plane.count()

Unnamed: 0      3322
tailnum         3322
year            3252
type            3322
manufacturer    3322
model           3322
engines         3322
seats           3322
speed             23
engine          3322
dtype: int64

In [14]:
Plane.shape[0]

3322

In [60]:
Weather.count()

Column1       26130
origin        26130
year          26130
month         26130
day           26130
hour          26130
temp          26129
dewp          26129
humid         26129
wind_dir      25712
wind_speed    26127
wind_gust     26127
precip        26130
pressure      23400
visib         26130
time_hour     26130
dtype: int64

In [16]:
Weather.shape[0]

26130

In [ ]:
#based on the exploratory analysis, the Airline and Airport csv files do not appear to have any missing data
#Flight shows a few columns with partial data, this can be further cleaned by inputting the average value of the missing data
#Plane shows a column titled Speed that has only 23 entries out of a possible 3,322 rows
#For Plane, the entire Speed column can likely be removed because the variable will not play a role in the analysis 
#Weather appears to display a similar situation as Flight where a few columns show only partial information. This problem can also likely be solved by inputting the average of the missing data

#let's look into cleaning these 3 data sets, starting with Plane

In [18]:
Airline

#simply typing in the name of each dataframe also provides a summary..

    Unnamed: 0 carrier                         name
0            1      9E            Endeavor Air Inc.
1            2      AA       American Airlines Inc.
2            3      AS         Alaska Airlines Inc.
3            4      B6              JetBlue Airways
4            5      DL         Delta Air Lines Inc.
5            6      EV     ExpressJet Airlines Inc.
6            7      F9       Frontier Airlines Inc.
7            8      FL  AirTran Airways Corporation
8            9      HA       Hawaiian Airlines Inc.
9           10      MQ                    Envoy Air
10          11      OO        SkyWest Airlines Inc.
11          12      UA        United Air Lines Inc.
12          13      US              US Airways Inc.
13          14      VX               Virgin America
14          15      WN       Southwest Airlines Co.
15          16      YV           Mesa Airlines Inc.

In [79]:
Airport

,Unnamed: 0,faa,name,lat,lon,alt,tz,dst,tzone
0,1,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,2,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,3,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,4,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,5,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
5,6,0A9,Elizabethton Municipal Airport,36.371222,-82.173417,1593,-5,A,America/New_York
6,7,0G6,Williams County Airport,41.467306,-84.506778,730,-5,A,America/New_York
7,8,0G7,Finger Lakes Regional Airport,42.883565,-76.781232,492,-5,A,America/New_York
8,9,0P2,Shoestring Aviation Airfield,39.794824,-76.647191,1000,-5,U,America/New_York
9,10,0S9,Jefferson County Intl,48.053809,-122.810644,108,-8,A,America/Los_Angeles
10,11,0W3,Harford County Airport,39.566838,-76.202403,409,-5,A,America/New_York
11,12,10C,Galt Field Airport,42.402889,-88.375111,875,-6,U,America/Chicago
12,13,17G,Port Bucyrus-Crawford County Airport,40.781556,-82.974806,1003,-5,A,America/New_York
13,14,19A,Jackson County Airport,34.175864,-83.561597,951,-5,U,America/New_York
14,15,1A3,Martin Campbell Field Airport,35.015806,-84.346833,1789,-5,A,America/New_York
15,16,1B9,Mansfield Municipal,42.000133,-71.196771,122,-5,A,America/New_York
16,17,1C9,Frazier Lake Airpark,54.013333,-124.768333,152,-8,A,America/Vancouver
17,18,1CS,Clow International Airport,41.695974,-88.129231,670,-6,U,America/Chicago
18,19,1G3,Kent State Airport,41.151389,-81.415111,1134,-5,A,America/New_York
19,20,1G4,Grand Canyon West Airport,35.899904,-113.815674,4813,-7,A,America/Phoenix
20,21,1H2,Effingham Memorial Airport,39.070000,-88.534000,585,-6,A,America/Chicago
21,22,1OH,Fortman Airport,40.555325,-84.386619,885,-5,U,America/New_York
22,23,1RL,Point Roberts Airpark,48.979722,-123.078889,10,-8,A,America/Los_Angeles
23,24,23M,Clarke CO,32.051700,-88.443400,320,-6,A,America/Chicago
24,25,24C,Lowell City Airport,42.953920,-85.343906,681,-5,A,America/New_York
25,26,24J,Suwannee County Airport,30.300125,-83.024694,104,-5,A,America/New_York
26,27,25D,Forest Lake Airport,45.247746,-92.994385,925,-6,A,America/Chicago
27,28,29D,Grove City Airport,41.146028,-80.167750,1371,-5,A,America/New_York
28,29,2A0,Mark Anton Airport,35.486250,-84.931083,718,-5,A,America/New_York
29,30,2B2,Plum Island Airport,42.795361,-70.839444,11,-5,A,America/New_York
...,...,...,...,...,...,...,...,...,...
1428,1429,X59,Valkaria Municipal,27.960861,-80.558333,26,-5,A,America/New_York
1429,1430,XFL,Flagler County Airport,29.282100,-81.121200,33,-5,A,America/New_York
1430,1431,XNA,NW Arkansas Regional,36.281869,-94.306811,1287,-6,A,America/Chicago
1431,1432,XZK,Amherst Amtrak Station AMM,42.375000,-72.511389,258,-5,A,America/New_York
1432,1433,Y51,Municipal Airport,43.579360,-90.896474,1292,-6,A,America/Chicago
1433,1434,Y72,Bloyer Field,43.976222,-90.480611,966,-6,A,America/Chicago
1434,1435,YAK,Yakutat,59.301200,-139.393700,33,-9,A,\N
1435,1436,YIP,Willow Run,42.237928,-83.530408,716,-5,A,America/New_York
1436,1437,YKM,Yakima Air Terminal McAllister Field,46.568200,-120.544000,1095,-8,A,America/Los_Angeles
1437,1438,YKN,Chan Gurney,42.871100,-97.396900,1200,-6,A,America/Chicago
1438,1439,YNG,Youngstown Warren Rgnl,41.260736,-80.679097,1196,-5,A,America/New_York
1439,1440,YUM,Yuma Mcas Yuma Intl,32.656578,-114.605980,216,-7,N,America/Phoenix
1440,1441,Z84,Clear,64.301203,-149.120144,552,-9,A,America/Anchorage
1441,1442,ZBP,Penn Station,39.307222,-76.615556,66,-5,A,America/New_York
1442,1443,ZFV,Philadelphia 30th St Station,39.955700,-75.182000,0,-5,A,America/New_York
1443,1444,ZPH,Municipal Airport,28.228056,-82.155833,90,-5,A,America/New_York
1444,1445,ZRA,Atlantic City Rail Terminal,39.366500,-74.442000,8,-5,A,America/New_York
1445,1446,ZRD,Train Station,37.534300,-77.429450,26,-5,A,America/New_York
1446,1447,ZRP,Newark Penn Station,40.734722,-74.164167,0,-5,A,America/New_York
1447,1448,ZRT,Hartford Union Station,41.768880,-72.681500,0,-5,A,America/New_York
1448,1449,ZRZ,New Carrollton Rail Station,38.948000,-76.871900,39,-5,A,America/New_York
1449,1450,ZSF,Springfield Amtrak Station,42.106000,-72.593054,65,-5,A,America/New_York
1450,1451,ZSY,Scottsdale Airport,33.622889,-111.910528,1519,-7,A,America/Phoenix
1451,1452,ZTF,Stamford Amtrak Station,41.046937,-73.541493,0,-5,A,America/New_York
1452,1453,ZTY,Boston Back Bay Station,42.347800,-71.075000,20,-5,A,America/New_York
1453,1454,ZUN,Black Rock,35.083228,-108.791778,6454,-7,A,America/Denver
1454,1455,ZVE,New Haven Rail Station,41.298669,-72.925992,7,-5,A,America/New_York
1455,1456,ZWI,Wilmington Amtrak Station,39.736667,-75.551667,0,-5,A,America/New_York
1456,1457,ZWU,Washington Union Station,38.897460,-77.006430,76,-5,A,America/New_York
1457,1458,ZYP,Penn Station,40.750500,-73.993500,35,-5,A,America/New_York

In [20]:
Flight

,Column1,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,1/1/2013 5:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,1/1/2013 5:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,1/1/2013 5:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,1/1/2013 5:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,1/1/2013 6:00
5,6,2013,1,1,554.0,558,-4.0,740.0,728,12.0,UA,1696,N39463,EWR,ORD,150.0,719,5,58,1/1/2013 5:00
6,7,2013,1,1,555.0,600,-5.0,913.0,854,19.0,B6,507,N516JB,EWR,FLL,158.0,1065,6,0,1/1/2013 6:00
7,8,2013,1,1,557.0,600,-3.0,709.0,723,-14.0,EV,5708,N829AS,LGA,IAD,53.0,229,6,0,1/1/2013 6:00
8,9,2013,1,1,557.0,600,-3.0,838.0,846,-8.0,B6,79,N593JB,JFK,MCO,140.0,944,6,0,1/1/2013 6:00
9,10,2013,1,1,558.0,600,-2.0,753.0,745,8.0,AA,301,N3ALAA,LGA,ORD,138.0,733,6,0,1/1/2013 6:00
10,11,2013,1,1,558.0,600,-2.0,849.0,851,-2.0,B6,49,N793JB,JFK,PBI,149.0,1028,6,0,1/1/2013 6:00
11,12,2013,1,1,558.0,600,-2.0,853.0,856,-3.0,B6,71,N657JB,JFK,TPA,158.0,1005,6,0,1/1/2013 6:00
12,13,2013,1,1,558.0,600,-2.0,924.0,917,7.0,UA,194,N29129,JFK,LAX,345.0,2475,6,0,1/1/2013 6:00
13,14,2013,1,1,558.0,600,-2.0,923.0,937,-14.0,UA,1124,N53441,EWR,SFO,361.0,2565,6,0,1/1/2013 6:00
14,15,2013,1,1,559.0,600,-1.0,941.0,910,31.0,AA,707,N3DUAA,LGA,DFW,257.0,1389,6,0,1/1/2013 6:00
15,16,2013,1,1,559.0,559,0.0,702.0,706,-4.0,B6,1806,N708JB,JFK,BOS,44.0,187,5,59,1/1/2013 5:00
16,17,2013,1,1,559.0,600,-1.0,854.0,902,-8.0,UA,1187,N76515,EWR,LAS,337.0,2227,6,0,1/1/2013 6:00
17,18,2013,1,1,600.0,600,0.0,851.0,858,-7.0,B6,371,N595JB,LGA,FLL,152.0,1076,6,0,1/1/2013 6:00
18,19,2013,1,1,600.0,600,0.0,837.0,825,12.0,MQ,4650,N542MQ,LGA,ATL,134.0,762,6,0,1/1/2013 6:00
19,20,2013,1,1,601.0,600,1.0,844.0,850,-6.0,B6,343,N644JB,EWR,PBI,147.0,1023,6,0,1/1/2013 6:00
20,21,2013,1,1,602.0,610,-8.0,812.0,820,-8.0,DL,1919,N971DL,LGA,MSP,170.0,1020,6,10,1/1/2013 6:00
21,22,2013,1,1,602.0,605,-3.0,821.0,805,16.0,MQ,4401,N730MQ,LGA,DTW,105.0,502,6,5,1/1/2013 6:00
22,23,2013,1,1,606.0,610,-4.0,858.0,910,-12.0,AA,1895,N633AA,EWR,MIA,152.0,1085,6,10,1/1/2013 6:00
23,24,2013,1,1,606.0,610,-4.0,837.0,845,-8.0,DL,1743,N3739P,JFK,ATL,128.0,760,6,10,1/1/2013 6:00
24,25,2013,1,1,607.0,607,0.0,858.0,915,-17.0,UA,1077,N53442,EWR,MIA,157.0,1085,6,7,1/1/2013 6:00
25,26,2013,1,1,608.0,600,8.0,807.0,735,32.0,MQ,3768,N9EAMQ,EWR,ORD,139.0,719,6,0,1/1/2013 6:00
26,27,2013,1,1,611.0,600,11.0,945.0,931,14.0,UA,303,N532UA,JFK,SFO,366.0,2586,6,0,1/1/2013 6:00
27,28,2013,1,1,613.0,610,3.0,925.0,921,4.0,B6,135,N635JB,JFK,RSW,175.0,1074,6,10,1/1/2013 6:00
28,29,2013,1,1,615.0,615,0.0,1039.0,1100,-21.0,B6,709,N794JB,JFK,SJU,182.0,1598,6,15,1/1/2013 6:00
29,30,2013,1,1,615.0,615,0.0,833.0,842,-9.0,DL,575,N326NB,EWR,ATL,120.0,746,6,15,1/1/2013 6:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336746,336747,2013,9,30,2123.0,2125,-2.0,2223.0,2247,-24.0,EV,5489,N712EV,LGA,CHO,45.0,305,21,25,9/30/2013 21:00
336747,336748,2013,9,30,2127.0,2129,-2.0,2314.0,2323,-9.0,EV,3833,N16546,EWR,CLT,72.0,529,21,29,9/30/2013 21:00
336748,336749,2013,9,30,2128.0,2130,-2.0,2328.0,2359,-31.0,B6,97,N807JB,JFK,DEN,213.0,1626,21,30,9/30/2013 21:00
336749,336750,2013,9,30,2129.0,2059,30.0,2230.0,2232,-2.0,EV,5048,N751EV,LGA,RIC,45.0,292,20,59,9/30/2013 20:00
336750,336751,2013,9,30,2131.0,2140,-9.0,2225.0,2255,-30.0,MQ,3621,N807MQ,JFK,DCA,36.0,213,21,40,9/30/2013 21:00
336751,336752,2013,9,30,2140.0,2140,0.0,10.0,40,-30.0,AA,185,N335AA,JFK,LAX,298.0,2475,21,40,9/30/2013 21:00
336752,336753,2013,9,30,2142.0,2129,13.0,2250.0,2239,11.0,EV,4509,N12957,EWR,PWM,47.0,284,21,29,9/30/2013 21:00
336753,336754,2013,9,30,2145.0,2145,0.0,115.0,140,-25.0,B6,1103,N633JB,JFK,SJU,192.0,1598,21,45,9/30/2013 21:00
336754,336755,2013,9,30,2147.0,2137,10.0,30.0,27,3.0,B6,1371,N627JB,LGA,FLL,139.0,1076,21,37,9/30/2013 21:00
336755,336756,2013,9,30,2149.0,2156,-7.0,2245.0,2308,-23.0,UA,523,N813UA,EWR,BOS,37.0,200,21,56,9/30/2013 21:00
336756,336757,2013,9,30,2150.0,2159,-9.0,2250.0,2306,-16.0,EV,3842,N10575,EWR,MHT,39.0,209,21,59,9/30/2013 21:00
336757,336758,2013,9,30,2159.0,1845,194.0,2344.0,2030,194.0,9E,3320,N906XJ,JFK,BUF,50.0,301,18,45,9/30/2013 18:00
336758,336759,2013,9,30,2203.0,2205,-2.0,2339.0,2331,8.0,EV,5311,N722EV,LGA,BGR,61.0,378,22,5,9/30/2013 22:00
336759,336760,2013,9,30,2207.0,2140,27.0,2257.0,2250,7.0,MQ,3660,N532MQ,LGA,BNA,97.0,764,21,40,9/30/2013 21:00
336760,336761,2013,9,30,2211.0,2059,72.0,2339.0,2242,57.0,EV,4672,N12145,EWR,STL,120.0,872,20,59,9/30/2013 20:00
336761,336762,2013,9,30,2231.0,2245,-14.0,2335.0,2356,-21.0,B6,108,N193JB,JFK,PWM,48.0,273,22,45,9/30/2013 22:00
336762,336763,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,9/30/2013 21:00
336763,336764,2013,9,30,2235.0,2001,154.0,59.0,2249,130.0,B6,1083,N804JB,JFK,MCO,123.0,944,20,1,9/30/2013 20:00
336764,336765,2013,9,30,2237.0,2245,-8.0,2345.0,2353,-8.0,B6,234,N318JB,JFK,BTV,43.0,266,22,45,9/30/2013 22:00
336765,336766,2013,9,30,2240.0,2245,-5.0,2334.0,2351,-17.0,B6,1816,N354JB,JFK,SYR,41.0,209,22,45,9/30/2013 22:00
336766,336767,2013,9,30,2240.0,2250,-10.0,2347.0,7,-20.0,B6,2002,N281JB,JFK,BUF,52.0,301,22,50,9/30/2013 22:00
336767,336768,2013,9,30,2241.0,2246,-5.0,2345.0,1,-16.0,B6,486,N346JB,JFK,ROC,47.0,264,22,46,9/30/2013 22:00
336768,336769,2013,9,30,2307.0,2255,12.0,2359.0,2358,1.0,B6,718,N565JB,JFK,BOS,33.0,187,22,55,9/30/2013 22:00
336769,336770,2013,9,30,2349.0,2359,-10.0,325.0,350,-25.0,B6,745,N516JB,JFK,PSE,196.0,1617,23,59,9/30/2013 23:00
336770,336771,2013,9,30,NaN,1842,NaN,NaN,2019,NaN,EV,5274,N740EV,LGA,BNA,NaN,764,18,42,9/30/2013 18:00
336771,336772,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,9/30/2013 14:00
336772,336773,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,9/30/2013 22:00
336773,336774,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,9/30/2013 12:00
336774,336775,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,9/30/2013 11:00
336775,336776,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,9/30/2013 8:00

In [17]:
Plane

,Unnamed: 0,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,1,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,2,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,3,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,4,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,5,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan
5,6,N105UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
6,7,N107US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
7,8,N108UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
8,9,N109UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
9,10,N110UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
10,11,N11106,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
11,12,N11107,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
12,13,N11109,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
13,14,N11113,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
14,15,N11119,2002.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
15,16,N11121,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
16,17,N11127,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
17,18,N11137,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
18,19,N11140,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
19,20,N11150,2003.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
20,21,N11155,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
21,22,N11164,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
22,23,N11165,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
23,24,N11176,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
24,25,N11181,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
25,26,N11184,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
26,27,N11187,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
27,28,N11189,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
28,29,N11191,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
29,30,N11192,2005.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
...,...,...,...,...,...,...,...,...,...,...
3292,3293,N984DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3293,3294,N985AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3294,3295,N985DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3295,3296,N986AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3296,3297,N986DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3297,3298,N987AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3298,3299,N987DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3299,3300,N988AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3300,3301,N988DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3301,3302,N989AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3302,3303,N989DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3303,3304,N990AT,2001.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3304,3305,N990DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3305,3306,N991AT,NaN,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3306,3307,N991DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3307,3308,N992AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3308,3309,N992DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3309,3310,N993AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3310,3311,N993DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3311,3312,N994AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3312,3313,N994DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3313,3314,N995AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3314,3315,N995DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3315,3316,N996AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3316,3317,N996DL,1991.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3317,3318,N997AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3318,3319,N997DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS AIRCRAFT CO,MD-88,2,142,NaN,Turbo-fan
3319,3320,N998AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3320,3321,N998DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3321,3322,N999DN,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet

In [21]:
Weather

,Unnamed: 0,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,1,EWR,2013,1,1,0,37.04,21.92,53.97,230.0,10.35702,11.918651,0.00,1013.9,10.00,2012-12-31 19:00:00
1,2,EWR,2013,1,1,1,37.04,21.92,53.97,230.0,13.80936,15.891535,0.00,1013.0,10.00,2012-12-31 20:00:00
2,3,EWR,2013,1,1,2,37.94,21.92,52.09,230.0,12.65858,14.567241,0.00,1012.6,10.00,2012-12-31 21:00:00
3,4,EWR,2013,1,1,3,37.94,23.00,54.51,230.0,13.80936,15.891535,0.00,1012.7,10.00,2012-12-31 22:00:00
4,5,EWR,2013,1,1,4,37.94,24.08,57.04,240.0,14.96014,17.215830,0.00,1012.8,10.00,2012-12-31 23:00:00
5,6,EWR,2013,1,1,6,39.02,26.06,59.37,270.0,10.35702,11.918651,0.00,1012.0,10.00,2013-01-01 01:00:00
6,7,EWR,2013,1,1,7,39.02,26.96,61.63,250.0,8.05546,9.270062,0.00,1012.3,10.00,2013-01-01 02:00:00
7,8,EWR,2013,1,1,8,39.02,28.04,64.43,240.0,11.50780,13.242946,0.00,1012.5,10.00,2013-01-01 03:00:00
8,9,EWR,2013,1,1,9,39.92,28.04,62.21,250.0,12.65858,14.567241,0.00,1012.2,10.00,2013-01-01 04:00:00
9,10,EWR,2013,1,1,10,39.02,28.04,64.43,260.0,12.65858,14.567241,0.00,1011.9,10.00,2013-01-01 05:00:00
10,11,EWR,2013,1,1,11,37.94,28.04,67.21,240.0,11.50780,13.242946,0.00,1012.4,10.00,2013-01-01 06:00:00
11,12,EWR,2013,1,1,12,39.02,28.04,64.43,240.0,14.96014,17.215830,0.00,1012.2,10.00,2013-01-01 07:00:00
12,13,EWR,2013,1,1,13,39.92,28.04,62.21,250.0,10.35702,11.918651,0.00,1012.2,10.00,2013-01-01 08:00:00
13,14,EWR,2013,1,1,14,39.92,28.04,62.21,260.0,14.96014,17.215830,0.00,1012.7,10.00,2013-01-01 09:00:00
14,15,EWR,2013,1,1,15,41.00,28.04,59.65,260.0,13.80936,15.891535,0.00,1012.4,10.00,2013-01-01 10:00:00
15,16,EWR,2013,1,1,16,41.00,26.96,57.06,260.0,14.96014,17.215830,0.00,1011.4,10.00,2013-01-01 11:00:00
16,17,EWR,2013,1,1,17,39.20,28.40,64.93,270.0,16.11092,18.540125,0.00,NaN,10.00,2013-01-01 12:00:00
17,18,EWR,2013,1,1,18,39.20,28.40,64.93,330.0,14.96014,17.215830,0.00,NaN,10.00,2013-01-01 13:00:00
18,19,EWR,2013,1,1,19,39.02,24.08,54.68,280.0,13.80936,15.891535,0.00,1010.8,10.00,2013-01-01 14:00:00
19,20,EWR,2013,1,1,20,37.94,24.08,57.04,290.0,9.20624,10.594357,0.00,1011.9,10.00,2013-01-01 15:00:00
20,21,EWR,2013,1,1,21,37.04,19.94,49.62,300.0,13.80936,15.891535,0.00,1012.1,10.00,2013-01-01 16:00:00
21,22,EWR,2013,1,1,22,35.96,19.04,49.83,330.0,11.50780,13.242946,0.00,1013.2,10.00,2013-01-01 17:00:00
22,23,EWR,2013,1,1,23,33.98,15.08,45.43,310.0,12.65858,14.567241,0.00,1014.1,10.00,2013-01-01 18:00:00
23,24,EWR,2013,1,2,0,33.08,12.92,42.84,320.0,10.35702,11.918651,0.00,1014.4,10.00,2013-01-01 19:00:00
24,25,EWR,2013,1,2,1,32.00,15.08,49.19,310.0,14.96014,17.215830,0.00,1015.2,10.00,2013-01-01 20:00:00
25,26,EWR,2013,1,2,2,30.02,12.92,48.48,320.0,18.41248,21.188714,0.00,1016.0,10.00,2013-01-01 21:00:00
26,27,EWR,2013,1,2,3,28.94,12.02,48.69,320.0,18.41248,21.188714,0.00,1016.5,10.00,2013-01-01 22:00:00
27,28,EWR,2013,1,2,4,28.04,10.94,48.15,310.0,16.11092,18.540125,0.00,1016.4,10.00,2013-01-01 23:00:00
28,29,EWR,2013,1,2,5,26.96,10.94,50.34,310.0,14.96014,17.215830,0.00,1016.3,10.00,2013-01-02 00:00:00
29,30,EWR,2013,1,2,6,26.06,10.94,52.25,330.0,12.65858,14.567241,0.00,1016.3,10.00,2013-01-02 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26100,26101,LGA,2013,12,29,18,42.80,37.40,81.07,70.0,9.20624,10.594357,0.06,NaN,2.50,2013-12-29 13:00:00
26101,26102,LGA,2013,12,29,19,39.20,37.40,93.19,40.0,16.11092,18.540125,0.06,NaN,1.75,2013-12-29 14:00:00
26102,26103,LGA,2013,12,29,20,41.00,39.02,92.59,40.0,13.80936,15.891535,0.37,999.9,1.50,2013-12-29 15:00:00
26103,26104,LGA,2013,12,29,21,41.00,37.94,88.76,350.0,8.05546,9.270062,0.28,998.7,1.50,2013-12-29 16:00:00
26104,26105,LGA,2013,12,29,22,41.00,39.20,93.24,50.0,20.71404,23.837303,0.03,NaN,2.00,2013-12-29 17:00:00
26105,26106,LGA,2013,12,29,23,42.08,39.02,88.81,330.0,14.96014,17.215830,0.00,997.2,3.00,2013-12-29 18:00:00
26106,26107,LGA,2013,12,30,0,42.80,37.40,81.07,320.0,17.26170,19.864419,0.00,NaN,8.00,2013-12-29 19:00:00
26107,26108,LGA,2013,12,30,1,41.00,37.40,86.89,310.0,19.56326,22.513008,0.00,NaN,6.00,2013-12-29 20:00:00
26108,26109,LGA,2013,12,30,2,42.80,37.40,81.07,320.0,16.11092,18.540125,0.00,NaN,10.00,2013-12-29 21:00:00
26109,26110,LGA,2013,12,30,3,42.98,37.04,79.38,300.0,9.20624,10.594357,0.00,1003.8,10.00,2013-12-29 22:00:00
26110,26111,LGA,2013,12,30,4,42.98,35.06,73.39,310.0,17.26170,19.864419,0.00,1005.1,10.00,2013-12-29 23:00:00
26111,26112,LGA,2013,12,30,5,42.08,33.98,72.78,320.0,11.50780,13.242946,0.00,1005.9,10.00,2013-12-30 00:00:00
26112,26113,LGA,2013,12,30,6,42.08,33.98,72.78,250.0,9.20624,10.594357,0.00,1007.6,10.00,2013-12-30 01:00:00
26113,26114,LGA,2013,12,30,7,41.00,33.98,75.88,240.0,8.05546,9.270062,0.00,1008.3,10.00,2013-12-30 02:00:00
26114,26115,LGA,2013,12,30,8,42.98,33.98,70.30,270.0,9.20624,10.594357,0.00,1008.2,10.00,2013-12-30 03:00:00
26115,26116,LGA,2013,12,30,9,41.00,33.08,73.19,0.0,0.00000,0.000000,0.00,1008.9,10.00,2013-12-30 04:00:00
26116,26117,LGA,2013,12,30,10,42.98,33.08,67.81,250.0,10.35702,11.918651,0.00,1009.2,10.00,2013-12-30 05:00:00
26117,26118,LGA,2013,12,30,11,42.98,33.98,70.30,230.0,6.90468,7.945768,0.00,1010.8,10.00,2013-12-30 06:00:00
26118,26119,LGA,2013,12,30,12,44.06,35.06,70.42,240.0,11.50780,13.242946,0.00,1011.9,10.00,2013-12-30 07:00:00
26119,26120,LGA,2013,12,30,13,44.06,33.98,67.45,260.0,11.50780,13.242946,0.00,1012.9,10.00,2013-12-30 08:00:00
26120,26121,LGA,2013,12,30,14,44.06,33.08,65.07,260.0,13.80936,15.891535,0.00,1013.7,10.00,2013-12-30 09:00:00
26121,26122,LGA,2013,12,30,15,42.80,33.80,70.28,330.0,16.11092,18.540125,0.00,NaN,10.00,2013-12-30 10:00:00
26122,26123,LGA,2013,12,30,16,41.00,28.40,60.54,340.0,13.80936,15.891535,0.00,NaN,10.00,2013-12-30 11:00:00
26123,26124,LGA,2013,12,30,17,37.94,23.00,54.51,330.0,21.86482,25.161598,0.00,1015.7,10.00,2013-12-30 12:00:00
26124,26125,LGA,2013,12,30,18,37.04,21.92,53.97,340.0,17.26170,19.864419,0.00,1016.5,10.00,2013-12-30 13:00:00
26125,26126,LGA,2013,12,30,19,35.96,19.94,51.78,340.0,13.80936,15.891535,0.00,1017.1,10.00,2013-12-30 14:00:00
26126,26127,LGA,2013,12,30,20,33.98,17.06,49.51,330.0,17.26170,19.864419,0.00,1018.8,10.00,2013-12-30 15:00:00
26127,26128,LGA,2013,12,30,21,32.00,15.08,49.19,340.0,14.96014,17.215830,0.00,1019.5,10.00,2013-12-30 16:00:00
26128,26129,LGA,2013,12,30,22,30.92,12.92,46.74,320.0,17.26170,19.864419,0.00,1019.9,10.00,2013-12-30 17:00:00
26129,26130,LGA,2013,12,30,23,28.94,10.94,46.41,330.0,18.41248,21.188714,0.00,1020.9,10.00,2013-12-30 18:00:00

In [78]:
Airport.summary()

AttributeError: 'DataFrame' object has no attribute 'summary'

In [3]:
PlaneC = Plane[['tailnum', 'year', 'type', 'manufacturer', 'model', 'engines', 'seats', 'engine']]
print(PlaneC)

#clean the Plane csv by removing the Speed variable because it contains an excessive amount of NaNs (missing values)

     tailnum    year                     type                   manufacturer  \
0     N10156  2004.0  Fixed wing multi engine                        EMBRAER
1     N102UW  1998.0  Fixed wing multi engine               AIRBUS INDUSTRIE
2     N103US  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
3     N104UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
4     N10575  2002.0  Fixed wing multi engine                        EMBRAER
5     N105UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
6     N107US  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
7     N108UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
8     N109UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
9     N110UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
10    N11106  2002.0  Fixed wing multi engine                        EMBRAER
11    N11107  2002.0  Fixed wing multi engine                        EMBRAER
12    N11109  2002.0  Fixed wing multi engine                        EMBRAER
13    N11113  2002.0  Fixed wing multi engine                        EMBRAER
14    N11119  2002.0  Fixed wing multi engine                        EMBRAER
15    N11121  2003.0  Fixed wing multi engine                        EMBRAER
16    N11127  2003.0  Fixed wing multi engine                        EMBRAER
17    N11137  2003.0  Fixed wing multi engine                        EMBRAER
18    N11140  2003.0  Fixed wing multi engine                        EMBRAER
19    N11150  2003.0  Fixed wing multi engine                        EMBRAER
20    N11155  2004.0  Fixed wing multi engine                        EMBRAER
21    N11164  2004.0  Fixed wing multi engine                        EMBRAER
22    N11165  2004.0  Fixed wing multi engine                        EMBRAER
23    N11176  2004.0  Fixed wing multi engine                        EMBRAER
24    N11181  2005.0  Fixed wing multi engine                        EMBRAER
25    N11184  2005.0  Fixed wing multi engine                        EMBRAER
26    N11187  2005.0  Fixed wing multi engine                        EMBRAER
27    N11189  2005.0  Fixed wing multi engine                        EMBRAER
28    N11191  2005.0  Fixed wing multi engine                        EMBRAER
29    N11192  2005.0  Fixed wing multi engine                        EMBRAER
...      ...     ...                      ...                            ...
3292  N984DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3293  N985AT  2001.0  Fixed wing multi engine                         BOEING
3294  N985DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3295  N986AT  2001.0  Fixed wing multi engine                         BOEING
3296  N986DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3297  N987AT  2001.0  Fixed wing multi engine                         BOEING
3298  N987DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3299  N988AT  2001.0  Fixed wing multi engine                         BOEING
3300  N988DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3301  N989AT  2001.0  Fixed wing multi engine                         BOEING
3302  N989DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3303  N990AT  2001.0  Fixed wing multi engine                         BOEING
3304  N990DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3305  N991AT     NaN  Fixed wing multi engine                         BOEING
3306  N991DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3307  N992AT  2002.0  Fixed wing multi engine                         BOEING
3308  N992DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3309  N993AT  2002.0  Fixed wing multi engine                         BOEING
3310  N993DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3311  N994AT  2002.0  Fixed wing multi engine                         BOEING
3312  N994DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION
3313  N995AT  2002.0  Fixed wing multi engine                         BOEING
3314  N995DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3315  N996AT  2002.0  Fixed wing multi engine                         BOEING
3316  N996DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3317  N997AT  2002.0  Fixed wing multi engine                         BOEING
3318  N997DL  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3319  N998AT  2002.0  Fixed wing multi engine                         BOEING
3320  N998DL  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION
3321  N999DN  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION

          model  engines  seats     engine
0     EMB-145XR        2     55  Turbo-fan
1      A320-214        2    182  Turbo-fan
2      A320-214        2    182  Turbo-fan
3      A320-214        2    182  Turbo-fan
4     EMB-145LR        2     55  Turbo-fan
5      A320-214        2    182  Turbo-fan
6      A320-214        2    182  Turbo-fan
7      A320-214        2    182  Turbo-fan
8      A320-214        2    182  Turbo-fan
9      A320-214        2    182  Turbo-fan
10    EMB-145XR        2     55  Turbo-fan
11    EMB-145XR        2     55  Turbo-fan
12    EMB-145XR        2     55  Turbo-fan
13    EMB-145XR        2     55  Turbo-fan
14    EMB-145XR        2     55  Turbo-fan
15    EMB-145XR        2     55  Turbo-fan
16    EMB-145XR        2     55  Turbo-fan
17    EMB-145XR        2     55  Turbo-fan
18    EMB-145XR        2     55  Turbo-fan
19    EMB-145XR        2     55  Turbo-fan
20    EMB-145XR        2     55  Turbo-fan
21    EMB-145XR        2     55  Turbo-fan
22    EMB-145XR        2     55  Turbo-fan
23    EMB-145XR        2     55  Turbo-fan
24    EMB-145XR        2     55  Turbo-fan
25    EMB-145XR        2     55  Turbo-fan
26    EMB-145XR        2     55  Turbo-fan
27    EMB-145XR        2     55  Turbo-fan
28    EMB-145XR        2     55  Turbo-fan
29    EMB-145XR        2     55  Turbo-fan
...         ...      ...    ...        ...
3292      MD-88        2    142  Turbo-fan
3293    717-200        2    100  Turbo-fan
3294      MD-88        2    142  Turbo-fan
3295    717-200        2    100  Turbo-fan
3296      MD-88        2    142  Turbo-fan
3297    717-200        2    100  Turbo-fan
3298      MD-88        2    142  Turbo-fan
3299    717-200        2    100  Turbo-fan
3300      MD-88        2    142  Turbo-fan
3301    717-200        2    100  Turbo-fan
3302      MD-88        2    142  Turbo-fan
3303    717-200        2    100  Turbo-fan
3304      MD-88        2    142  Turbo-fan
3305    717-200        2    100  Turbo-fan
3306      MD-88        2    142  Turbo-fan
3307    717-200        2    100  Turbo-fan
3308      MD-88        2    142  Turbo-fan
3309    717-200        2    100  Turbo-fan
3310      MD-88        2    142  Turbo-fan
3311    717-200        2    100  Turbo-fan
3312      MD-88        2    142  Turbo-jet
3313    717-200        2    100  Turbo-fan
3314      MD-88        2    142  Turbo-fan
3315    717-200        2    100  Turbo-fan
3316      MD-88        2    142  Turbo-fan
3317    717-200        2    100  Turbo-fan
3318      MD-88        2    142  Turbo-fan
3319    717-200        2    100  Turbo-fan
3320      MD-88        2    142  Turbo-jet
3321      MD-88        2    142  Turbo-jet

[3322 rows x 8 columns]

In [43]:
Weather["temp"].mean()


#Weather["temp","dewp","humid","wind_dir","wind_speed","wind_gust","pressure"].mean(axis=1)

#Weather shows several columns with missing data. I want to find the average of each of these columns and input this figure into the Nans...

55.203514868537034

In [44]:
Weather["dewp"].mean()

41.38539936469043

In [45]:
Weather["humid"].mean()

62.34732174977937

In [46]:
Weather["wind_dir"].mean()

198.06666148102053

In [47]:
Weather["wind_speed"].mean()

10.39586823975324

In [48]:
Weather["wind_gust"].mean()

11.963357253109523

In [49]:
Weather["pressure"].mean()

1017.8951752136738

In [48]:
Weather["temp"].isna()

AttributeError: 'Series' object has no attribute 'isna'

In [49]:
Weather.isnull().values.any()
#yes I am aware of this...

True

In [50]:
WeatherC1 = Weather["temp"].fillna(55.2)
print(WeatherC1)

0        37.04
1        37.04
2        37.94
3        37.94
4        37.94
5        39.02
6        39.02
7        39.02
8        39.92
9        39.02
10       37.94
11       39.02
12       39.92
13       39.92
14       41.00
15       41.00
16       39.20
17       39.20
18       39.02
19       37.94
20       37.04
21       35.96
22       33.98
23       33.08
24       32.00
25       30.02
26       28.94
27       28.04
28       26.96
29       26.06
         ...
26100    42.80
26101    39.20
26102    41.00
26103    41.00
26104    41.00
26105    42.08
26106    42.80
26107    41.00
26108    42.80
26109    42.98
26110    42.98
26111    42.08
26112    42.08
26113    41.00
26114    42.98
26115    41.00
26116    42.98
26117    42.98
26118    44.06
26119    44.06
26120    44.06
26121    42.80
26122    41.00
26123    37.94
26124    37.04
26125    35.96
26126    33.98
26127    32.00
26128    30.92
26129    28.94
Name: temp, Length: 26130, dtype: float64

In [51]:
Weatherc2 = Weather["temp"].drop(['NaN'])

#removing row 5597 because it is the only missing value for the temp, dewp, and humid columns
#didn't work...

ValueError: labels ['NaN'] not contained in axis

In [63]:
Weatherc3 = [Weather.temp != 'NA']
#didn't work either

C:\Users\Justin\Anaconda3\lib\site-packages\pandas\core\ops.py:798: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)

TypeError: invalid type comparison

In [64]:
print(Weather)

       Unnamed: 0 origin  year  month  day  hour   temp   dewp  humid  \
0               1    EWR  2013      1    1     0  37.04  21.92  53.97
1               2    EWR  2013      1    1     1  37.04  21.92  53.97
2               3    EWR  2013      1    1     2  37.94  21.92  52.09
3               4    EWR  2013      1    1     3  37.94  23.00  54.51
4               5    EWR  2013      1    1     4  37.94  24.08  57.04
5               6    EWR  2013      1    1     6  39.02  26.06  59.37
6               7    EWR  2013      1    1     7  39.02  26.96  61.63
7               8    EWR  2013      1    1     8  39.02  28.04  64.43
8               9    EWR  2013      1    1     9  39.92  28.04  62.21
9              10    EWR  2013      1    1    10  39.02  28.04  64.43
10             11    EWR  2013      1    1    11  37.94  28.04  67.21
11             12    EWR  2013      1    1    12  39.02  28.04  64.43
12             13    EWR  2013      1    1    13  39.92  28.04  62.21
13             14    EWR  2013      1    1    14  39.92  28.04  62.21
14             15    EWR  2013      1    1    15  41.00  28.04  59.65
15             16    EWR  2013      1    1    16  41.00  26.96  57.06
16             17    EWR  2013      1    1    17  39.20  28.40  64.93
17             18    EWR  2013      1    1    18  39.20  28.40  64.93
18             19    EWR  2013      1    1    19  39.02  24.08  54.68
19             20    EWR  2013      1    1    20  37.94  24.08  57.04
20             21    EWR  2013      1    1    21  37.04  19.94  49.62
21             22    EWR  2013      1    1    22  35.96  19.04  49.83
22             23    EWR  2013      1    1    23  33.98  15.08  45.43
23             24    EWR  2013      1    2     0  33.08  12.92  42.84
24             25    EWR  2013      1    2     1  32.00  15.08  49.19
25             26    EWR  2013      1    2     2  30.02  12.92  48.48
26             27    EWR  2013      1    2     3  28.94  12.02  48.69
27             28    EWR  2013      1    2     4  28.04  10.94  48.15
28             29    EWR  2013      1    2     5  26.96  10.94  50.34
29             30    EWR  2013      1    2     6  26.06  10.94  52.25
...           ...    ...   ...    ...  ...   ...    ...    ...    ...
26100       26101    LGA  2013     12   29    18  42.80  37.40  81.07
26101       26102    LGA  2013     12   29    19  39.20  37.40  93.19
26102       26103    LGA  2013     12   29    20  41.00  39.02  92.59
26103       26104    LGA  2013     12   29    21  41.00  37.94  88.76
26104       26105    LGA  2013     12   29    22  41.00  39.20  93.24
26105       26106    LGA  2013     12   29    23  42.08  39.02  88.81
26106       26107    LGA  2013     12   30     0  42.80  37.40  81.07
26107       26108    LGA  2013     12   30     1  41.00  37.40  86.89
26108       26109    LGA  2013     12   30     2  42.80  37.40  81.07
26109       26110    LGA  2013     12   30     3  42.98  37.04  79.38
26110       26111    LGA  2013     12   30     4  42.98  35.06  73.39
26111       26112    LGA  2013     12   30     5  42.08  33.98  72.78
26112       26113    LGA  2013     12   30     6  42.08  33.98  72.78
26113       26114    LGA  2013     12   30     7  41.00  33.98  75.88
26114       26115    LGA  2013     12   30     8  42.98  33.98  70.30
26115       26116    LGA  2013     12   30     9  41.00  33.08  73.19
26116       26117    LGA  2013     12   30    10  42.98  33.08  67.81
26117       26118    LGA  2013     12   30    11  42.98  33.98  70.30
26118       26119    LGA  2013     12   30    12  44.06  35.06  70.42
26119       26120    LGA  2013     12   30    13  44.06  33.98  67.45
26120       26121    LGA  2013     12   30    14  44.06  33.08  65.07
26121       26122    LGA  2013     12   30    15  42.80  33.80  70.28
26122       26123    LGA  2013     12   30    16  41.00  28.40  60.54
26123       26124    LGA  2013     12   30    17  37.94  23.00  54.51
26124       26125    LGA  2013     12   30    18  37.04  21.92  53.97
26125       26126    LGA  2013     12   30    19  35.96  19.94  51.78
26126       26127    LGA  2013     12   30    20  33.98  17.06  49.51
26127       26128    LGA  2013     12   30    21  32.00  15.08  49.19
26128       26129    LGA  2013     12   30    22  30.92  12.92  46.74
26129       26130    LGA  2013     12   30    23  28.94  10.94  46.41

       wind_dir  wind_speed  wind_gust  precip  pressure  visib  \
0         230.0    10.35702  11.918651    0.00    1013.9  10.00
1         230.0    13.80936  15.891535    0.00    1013.0  10.00
2         230.0    12.65858  14.567241    0.00    1012.6  10.00
3         230.0    13.80936  15.891535    0.00    1012.7  10.00
4         240.0    14.96014  17.215830    0.00    1012.8  10.00
5         270.0    10.35702  11.918651    0.00    1012.0  10.00
6         250.0     8.05546   9.270062    0.00    1012.3  10.00
7         240.0    11.50780  13.242946    0.00    1012.5  10.00
8         250.0    12.65858  14.567241    0.00    1012.2  10.00
9         260.0    12.65858  14.567241    0.00    1011.9  10.00
10        240.0    11.50780  13.242946    0.00    1012.4  10.00
11        240.0    14.96014  17.215830    0.00    1012.2  10.00
12        250.0    10.35702  11.918651    0.00    1012.2  10.00
13        260.0    14.96014  17.215830    0.00    1012.7  10.00
14        260.0    13.80936  15.891535    0.00    1012.4  10.00
15        260.0    14.96014  17.215830    0.00    1011.4  10.00
16        270.0    16.11092  18.540125    0.00       NaN  10.00
17        330.0    14.96014  17.215830    0.00       NaN  10.00
18        280.0    13.80936  15.891535    0.00    1010.8  10.00
19        290.0     9.20624  10.594357    0.00    1011.9  10.00
20        300.0    13.80936  15.891535    0.00    1012.1  10.00
21        330.0    11.50780  13.242946    0.00    1013.2  10.00
22        310.0    12.65858  14.567241    0.00    1014.1  10.00
23        320.0    10.35702  11.918651    0.00    1014.4  10.00
24        310.0    14.96014  17.215830    0.00    1015.2  10.00
25        320.0    18.41248  21.188714    0.00    1016.0  10.00
26        320.0    18.41248  21.188714    0.00    1016.5  10.00
27        310.0    16.11092  18.540125    0.00    1016.4  10.00
28        310.0    14.96014  17.215830    0.00    1016.3  10.00
29        330.0    12.65858  14.567241    0.00    1016.3  10.00
...         ...         ...        ...     ...       ...    ...
26100      70.0     9.20624  10.594357    0.06       NaN   2.50
26101      40.0    16.11092  18.540125    0.06       NaN   1.75
26102      40.0    13.80936  15.891535    0.37     999.9   1.50
26103     350.0     8.05546   9.270062    0.28     998.7   1.50
26104      50.0    20.71404  23.837303    0.03       NaN   2.00
26105     330.0    14.96014  17.215830    0.00     997.2   3.00
26106     320.0    17.26170  19.864419    0.00       NaN   8.00
26107     310.0    19.56326  22.513008    0.00       NaN   6.00
26108     320.0    16.11092  18.540125    0.00       NaN  10.00
26109     300.0     9.20624  10.594357    0.00    1003.8  10.00
26110     310.0    17.26170  19.864419    0.00    1005.1  10.00
26111     320.0    11.50780  13.242946    0.00    1005.9  10.00
26112     250.0     9.20624  10.594357    0.00    1007.6  10.00
26113     240.0     8.05546   9.270062    0.00    1008.3  10.00
26114     270.0     9.20624  10.594357    0.00    1008.2  10.00
26115       0.0     0.00000   0.000000    0.00    1008.9  10.00
26116     250.0    10.35702  11.918651    0.00    1009.2  10.00
26117     230.0     6.90468   7.945768    0.00    1010.8  10.00
26118     240.0    11.50780  13.242946    0.00    1011.9  10.00
26119     260.0    11.50780  13.242946    0.00    1012.9  10.00
26120     260.0    13.80936  15.891535    0.00    1013.7  10.00
26121     330.0    16.11092  18.540125    0.00       NaN  10.00
26122     340.0    13.80936  15.891535    0.00       NaN  10.00
26123     330.0    21.86482  25.161598    0.00    1015.7  10.00
26124     340.0    17.26170  19.864419    0.00    1016.5  10.00
26125     340.0    13.80936  15.891535    0.00    1017.1  10.00
26126     330.0    17.26170  19.864419    0.00    1018.8  10.00
26127     340.0    14.96014  17.215830    0.00    1019.5  10.00
26128     320.0    17.26170  19.864419    0.00    1019.9  10.00
26129     330.0    18.41248  21.188714    0.00    1020.9  10.00

                 time_hour
0      2012-12-31 19:00:00
1      2012-12-31 20:00:00
2      2012-12-31 21:00:00
3      2012-12-31 22:00:00
4      2012-12-31 23:00:00
5      2013-01-01 01:00:00
6      2013-01-01 02:00:00
7      2013-01-01 03:00:00
8      2013-01-01 04:00:00
9      2013-01-01 05:00:00
10     2013-01-01 06:00:00
11     2013-01-01 07:00:00
12     2013-01-01 08:00:00
13     2013-01-01 09:00:00
14     2013-01-01 10:00:00
15     2013-01-01 11:00:00
16     2013-01-01 12:00:00
17     2013-01-01 13:00:00
18     2013-01-01 14:00:00
19     2013-01-01 15:00:00
20     2013-01-01 16:00:00
21     2013-01-01 17:00:00
22     2013-01-01 18:00:00
23     2013-01-01 19:00:00
24     2013-01-01 20:00:00
25     2013-01-01 21:00:00
26     2013-01-01 22:00:00
27     2013-01-01 23:00:00
28     2013-01-02 00:00:00
29     2013-01-02 01:00:00
...                    ...
26100  2013-12-29 13:00:00
26101  2013-12-29 14:00:00
26102  2013-12-29 15:00:00
26103  2013-12-29 16:00:00
26104  2013-12-29 17:00:00
26105  2013-12-29 18:00:00
26106  2013-12-29 19:00:00
26107  2013-12-29 20:00:00
26108  2013-12-29 21:00:00
26109  2013-12-29 22:00:00
26110  2013-12-29 23:00:00
26111  2013-12-30 00:00:00
26112  2013-12-30 01:00:00
26113  2013-12-30 02:00:00
26114  2013-12-30 03:00:00
26115  2013-12-30 04:00:00
26116  2013-12-30 05:00:00
26117  2013-12-30 06:00:00
26118  2013-12-30 07:00:00
26119  2013-12-30 08:00:00
26120  2013-12-30 09:00:00
26121  2013-12-30 10:00:00
26122  2013-12-30 11:00:00
26123  2013-12-30 12:00:00
26124  2013-12-30 13:00:00
26125  2013-12-30 14:00:00
26126  2013-12-30 15:00:00
26127  2013-12-30 16:00:00
26128  2013-12-30 17:00:00
26129  2013-12-30 18:00:00

[26130 rows x 16 columns]

In [74]:
WeatherC1.loc[5596, ]

55.200000000000003

In [52]:
print(WeatherC1)

0        37.04
1        37.04
2        37.94
3        37.94
4        37.94
5        39.02
6        39.02
7        39.02
8        39.92
9        39.02
10       37.94
11       39.02
12       39.92
13       39.92
14       41.00
15       41.00
16       39.20
17       39.20
18       39.02
19       37.94
20       37.04
21       35.96
22       33.98
23       33.08
24       32.00
25       30.02
26       28.94
27       28.04
28       26.96
29       26.06
         ...
26100    42.80
26101    39.20
26102    41.00
26103    41.00
26104    41.00
26105    42.08
26106    42.80
26107    41.00
26108    42.80
26109    42.98
26110    42.98
26111    42.08
26112    42.08
26113    41.00
26114    42.98
26115    41.00
26116    42.98
26117    42.98
26118    44.06
26119    44.06
26120    44.06
26121    42.80
26122    41.00
26123    37.94
26124    37.04
26125    35.96
26126    33.98
26127    32.00
26128    30.92
26129    28.94
Name: temp, Length: 26130, dtype: float64

In [53]:
tempc3 = WeatherC1
print(tempc3)

0        37.04
1        37.04
2        37.94
3        37.94
4        37.94
5        39.02
6        39.02
7        39.02
8        39.92
9        39.02
10       37.94
11       39.02
12       39.92
13       39.92
14       41.00
15       41.00
16       39.20
17       39.20
18       39.02
19       37.94
20       37.04
21       35.96
22       33.98
23       33.08
24       32.00
25       30.02
26       28.94
27       28.04
28       26.96
29       26.06
         ...
26100    42.80
26101    39.20
26102    41.00
26103    41.00
26104    41.00
26105    42.08
26106    42.80
26107    41.00
26108    42.80
26109    42.98
26110    42.98
26111    42.08
26112    42.08
26113    41.00
26114    42.98
26115    41.00
26116    42.98
26117    42.98
26118    44.06
26119    44.06
26120    44.06
26121    42.80
26122    41.00
26123    37.94
26124    37.04
26125    35.96
26126    33.98
26127    32.00
26128    30.92
26129    28.94
Name: temp, Length: 26130, dtype: float64

In [54]:
Weatherc3 = Weather["dewp"].fillna(41.39)
print(Weatherc3)

0        21.92
1        21.92
2        21.92
3        23.00
4        24.08
5        26.06
6        26.96
7        28.04
8        28.04
9        28.04
10       28.04
11       28.04
12       28.04
13       28.04
14       28.04
15       26.96
16       28.40
17       28.40
18       24.08
19       24.08
20       19.94
21       19.04
22       15.08
23       12.92
24       15.08
25       12.92
26       12.02
27       10.94
28       10.94
29       10.94
         ...
26100    37.40
26101    37.40
26102    39.02
26103    37.94
26104    39.20
26105    39.02
26106    37.40
26107    37.40
26108    37.40
26109    37.04
26110    35.06
26111    33.98
26112    33.98
26113    33.98
26114    33.98
26115    33.08
26116    33.08
26117    33.98
26118    35.06
26119    33.98
26120    33.08
26121    33.80
26122    28.40
26123    23.00
26124    21.92
26125    19.94
26126    17.06
26127    15.08
26128    12.92
26129    10.94
Name: dewp, Length: 26130, dtype: float64

In [82]:
Weatherc3.loc[5596, ]

41.390000000000001

In [55]:
dewpc3 = Weatherc3
print(dewpc3)

0        21.92
1        21.92
2        21.92
3        23.00
4        24.08
5        26.06
6        26.96
7        28.04
8        28.04
9        28.04
10       28.04
11       28.04
12       28.04
13       28.04
14       28.04
15       26.96
16       28.40
17       28.40
18       24.08
19       24.08
20       19.94
21       19.04
22       15.08
23       12.92
24       15.08
25       12.92
26       12.02
27       10.94
28       10.94
29       10.94
         ...
26100    37.40
26101    37.40
26102    39.02
26103    37.94
26104    39.20
26105    39.02
26106    37.40
26107    37.40
26108    37.40
26109    37.04
26110    35.06
26111    33.98
26112    33.98
26113    33.98
26114    33.98
26115    33.08
26116    33.08
26117    33.98
26118    35.06
26119    33.98
26120    33.08
26121    33.80
26122    28.40
26123    23.00
26124    21.92
26125    19.94
26126    17.06
26127    15.08
26128    12.92
26129    10.94
Name: dewp, Length: 26130, dtype: float64

In [56]:
humidc3 = Weather["humid"].fillna(62.35)
print(humidc3)

0        53.97
1        53.97
2        52.09
3        54.51
4        57.04
5        59.37
6        61.63
7        64.43
8        62.21
9        64.43
10       67.21
11       64.43
12       62.21
13       62.21
14       59.65
15       57.06
16       64.93
17       64.93
18       54.68
19       57.04
20       49.62
21       49.83
22       45.43
23       42.84
24       49.19
25       48.48
26       48.69
27       48.15
28       50.34
29       52.25
         ...
26100    81.07
26101    93.19
26102    92.59
26103    88.76
26104    93.24
26105    88.81
26106    81.07
26107    86.89
26108    81.07
26109    79.38
26110    73.39
26111    72.78
26112    72.78
26113    75.88
26114    70.30
26115    73.19
26116    67.81
26117    70.30
26118    70.42
26119    67.45
26120    65.07
26121    70.28
26122    60.54
26123    54.51
26124    53.97
26125    51.78
26126    49.51
26127    49.19
26128    46.74
26129    46.41
Name: humid, Length: 26130, dtype: float64

In [86]:
humidc3.loc[5596, ]

62.350000000000001

In [57]:
wind_dirc3 = Weather["wind_dir"].fillna(198.07)
print(wind_dirc3)

0        230.0
1        230.0
2        230.0
3        230.0
4        240.0
5        270.0
6        250.0
7        240.0
8        250.0
9        260.0
10       240.0
11       240.0
12       250.0
13       260.0
14       260.0
15       260.0
16       270.0
17       330.0
18       280.0
19       290.0
20       300.0
21       330.0
22       310.0
23       320.0
24       310.0
25       320.0
26       320.0
27       310.0
28       310.0
29       330.0
         ...
26100     70.0
26101     40.0
26102     40.0
26103    350.0
26104     50.0
26105    330.0
26106    320.0
26107    310.0
26108    320.0
26109    300.0
26110    310.0
26111    320.0
26112    250.0
26113    240.0
26114    270.0
26115      0.0
26116    250.0
26117    230.0
26118    240.0
26119    260.0
26120    260.0
26121    330.0
26122    340.0
26123    330.0
26124    340.0
26125    340.0
26126    330.0
26127    340.0
26128    320.0
26129    330.0
Name: wind_dir, Length: 26130, dtype: float64

In [90]:
wind_dirc3.loc[1787:1790, ]

1787    198.07
1788    198.07
1789    198.07
1790    198.07
Name: wind_dir, dtype: float64

In [58]:
wind_speedc3 = Weather["wind_speed"].fillna(10.4)
print(wind_speedc3)

0        10.35702
1        13.80936
2        12.65858
3        13.80936
4        14.96014
5        10.35702
6         8.05546
7        11.50780
8        12.65858
9        12.65858
10       11.50780
11       14.96014
12       10.35702
13       14.96014
14       13.80936
15       14.96014
16       16.11092
17       14.96014
18       13.80936
19        9.20624
20       13.80936
21       11.50780
22       12.65858
23       10.35702
24       14.96014
25       18.41248
26       18.41248
27       16.11092
28       14.96014
29       12.65858
           ...
26100     9.20624
26101    16.11092
26102    13.80936
26103     8.05546
26104    20.71404
26105    14.96014
26106    17.26170
26107    19.56326
26108    16.11092
26109     9.20624
26110    17.26170
26111    11.50780
26112     9.20624
26113     8.05546
26114     9.20624
26115     0.00000
26116    10.35702
26117     6.90468
26118    11.50780
26119    11.50780
26120    13.80936
26121    16.11092
26122    13.80936
26123    21.86482
26124    17.26170
26125    13.80936
26126    17.26170
26127    14.96014
26128    17.26170
26129    18.41248
Name: wind_speed, Length: 26130, dtype: float64

In [95]:
wind_speedc3.loc[13513, ]

10.4

In [59]:
wind_gustc3 = Weather["wind_gust"].fillna(11.96)
print(wind_gustc3)

0        11.918651
1        15.891535
2        14.567241
3        15.891535
4        17.215830
5        11.918651
6         9.270062
7        13.242946
8        14.567241
9        14.567241
10       13.242946
11       17.215830
12       11.918651
13       17.215830
14       15.891535
15       17.215830
16       18.540125
17       17.215830
18       15.891535
19       10.594357
20       15.891535
21       13.242946
22       14.567241
23       11.918651
24       17.215830
25       21.188714
26       21.188714
27       18.540125
28       17.215830
29       14.567241
           ...
26100    10.594357
26101    18.540125
26102    15.891535
26103     9.270062
26104    23.837303
26105    17.215830
26106    19.864419
26107    22.513008
26108    18.540125
26109    10.594357
26110    19.864419
26111    13.242946
26112    10.594357
26113     9.270062
26114    10.594357
26115     0.000000
26116    11.918651
26117     7.945768
26118    13.242946
26119    13.242946
26120    15.891535
26121    18.540125
26122    15.891535
26123    25.161598
26124    19.864419
26125    15.891535
26126    19.864419
26127    17.215830
26128    19.864419
26129    21.188714
Name: wind_gust, Length: 26130, dtype: float64

In [99]:
wind_gustc3.loc[2057, ]

11.960000000000001

In [60]:
pressurec3 = Weather["pressure"].fillna(1017.9)
print(pressurec3)

0        1013.9
1        1013.0
2        1012.6
3        1012.7
4        1012.8
5        1012.0
6        1012.3
7        1012.5
8        1012.2
9        1011.9
10       1012.4
11       1012.2
12       1012.2
13       1012.7
14       1012.4
15       1011.4
16       1017.9
17       1017.9
18       1010.8
19       1011.9
20       1012.1
21       1013.2
22       1014.1
23       1014.4
24       1015.2
25       1016.0
26       1016.5
27       1016.4
28       1016.3
29       1016.3
          ...
26100    1017.9
26101    1017.9
26102     999.9
26103     998.7
26104    1017.9
26105     997.2
26106    1017.9
26107    1017.9
26108    1017.9
26109    1003.8
26110    1005.1
26111    1005.9
26112    1007.6
26113    1008.3
26114    1008.2
26115    1008.9
26116    1009.2
26117    1010.8
26118    1011.9
26119    1012.9
26120    1013.7
26121    1017.9
26122    1017.9
26123    1015.7
26124    1016.5
26125    1017.1
26126    1018.8
26127    1019.5
26128    1019.9
26129    1020.9
Name: pressure, Length: 26130, dtype: float64

In [103]:
pressurec3.loc[1300:1310, ]

1300    1017.9
1301    1017.9
1302    1007.8
1303    1017.9
1304    1017.9
1305    1008.5
1306    1017.9
1307    1017.9
1308    1017.9
1309    1007.6
1310    1007.5
Name: pressure, dtype: float64

In [105]:
Weather.loc[5596,]

Unnamed: 0                   5597
origin                        EWR
year                         2013
month                           8
day                            22
hour                           13
temp                          NaN
dewp                          NaN
humid                         NaN
wind_dir                      240
wind_speed                12.6586
wind_gust                 14.5672
precip                       0.03
pressure                      NaN
visib                           4
time_hour     2013-08-22 08:00:00
Name: 5596, dtype: object

In [70]:
Weather.head(n=5)

,Column1,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,1,EWR,2013,1,1,0,37.04,21.92,53.97,230.0,10.35702,11.918651,0.0,1013.9,10.0,12/31/2012 19:00
1,2,EWR,2013,1,1,1,37.04,21.92,53.97,230.0,13.80936,15.891535,0.0,1013.0,10.0,12/31/2012 20:00
2,3,EWR,2013,1,1,2,37.94,21.92,52.09,230.0,12.65858,14.567241,0.0,1012.6,10.0,12/31/2012 21:00
3,4,EWR,2013,1,1,3,37.94,23.00,54.51,230.0,13.80936,15.891535,0.0,1012.7,10.0,12/31/2012 22:00
4,5,EWR,2013,1,1,4,37.94,24.08,57.04,240.0,14.96014,17.215830,0.0,1012.8,10.0,12/31/2012 23:00

In [58]:
WeatherN = Weather['Unnamed: 0', 'origin', 'year', 'month', 'day', 'hour', 'precip', 'visib', 'time_hour'].copy()
#doesn't work

KeyError: ('Unnamed: 0', 'origin', 'year', 'month', 'day', 'hour', 'precip', 'visib', 'time_hour')

In [61]:
WeatherN2 = Weather.filter(['Unnamed: 0', 'origin', 'year', 'month', 'day', 'hour', 'precip', 'visib', 'time_hour'], axis=1)
#works

In [62]:
print(WeatherN2)

      origin  year  month  day  hour  precip  visib         time_hour
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00
...      ...   ...    ...  ...   ...     ...    ...               ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00

[26130 rows x 8 columns]

In [63]:
WeatherN3 = WeatherN2.assign(temp=tempc3.values)
print(WeatherN3)

      origin  year  month  day  hour  precip  visib         time_hour   temp
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00  37.04
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00  37.04
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00  37.94
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00  37.94
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00  37.94
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00  39.02
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00  39.02
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00  39.02
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00  39.92
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00  39.02
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00  37.94
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00  39.02
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00  39.92
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00  39.92
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00  41.00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00  41.00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00  39.20
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00  39.20
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00  39.02
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00  37.94
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00  37.04
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00  35.96
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00  33.98
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00  33.08
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00  32.00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00  30.02
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00  28.94
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00  28.04
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00  26.96
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00  26.06
...      ...   ...    ...  ...   ...     ...    ...               ...    ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00  42.80
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00  39.20
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00  41.00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00  41.00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00  41.00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00  42.08
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00  42.80
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00  41.00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00  42.80
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00  42.98
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00  42.98
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00  42.08
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00  42.08
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00  41.00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00  42.98
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00  41.00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00  42.98
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00  42.98
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00  44.06
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00  44.06
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00  44.06
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00  42.80
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00  41.00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00  37.94
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00  37.04
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00  35.96
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00  33.98
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00  32.00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00  30.92
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00  28.94

[26130 rows x 9 columns]

In [64]:
WeatherN4 = WeatherN3.assign(dewp=dewpc3.values, humid=humidc3.values, wind_dir=wind_dirc3.values, wind_speed=wind_speedc3.values, wind_gust=wind_gustc3.values, pressure=pressurec3.values)
print(WeatherN4)

      origin  year  month  day  hour  precip  visib         time_hour   temp  \
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00  37.04
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00  37.04
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00  37.94
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00  37.94
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00  37.94
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00  39.02
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00  39.02
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00  39.02
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00  39.92
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00  39.02
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00  37.94
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00  39.02
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00  39.92
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00  39.92
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00  41.00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00  41.00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00  39.20
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00  39.20
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00  39.02
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00  37.94
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00  37.04
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00  35.96
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00  33.98
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00  33.08
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00  32.00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00  30.02
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00  28.94
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00  28.04
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00  26.96
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00  26.06
...      ...   ...    ...  ...   ...     ...    ...               ...    ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00  42.80
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00  39.20
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00  41.00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00  41.00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00  41.00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00  42.08
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00  42.80
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00  41.00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00  42.80
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00  42.98
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00  42.98
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00  42.08
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00  42.08
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00  41.00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00  42.98
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00  41.00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00  42.98
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00  42.98
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00  44.06
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00  44.06
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00  44.06
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00  42.80
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00  41.00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00  37.94
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00  37.04
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00  35.96
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00  33.98
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00  32.00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00  30.92
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00  28.94

        dewp  humid  pressure  wind_dir  wind_gust  wind_speed
0      21.92  53.97    1013.9     230.0  11.918651    10.35702
1      21.92  53.97    1013.0     230.0  15.891535    13.80936
2      21.92  52.09    1012.6     230.0  14.567241    12.65858
3      23.00  54.51    1012.7     230.0  15.891535    13.80936
4      24.08  57.04    1012.8     240.0  17.215830    14.96014
5      26.06  59.37    1012.0     270.0  11.918651    10.35702
6      26.96  61.63    1012.3     250.0   9.270062     8.05546
7      28.04  64.43    1012.5     240.0  13.242946    11.50780
8      28.04  62.21    1012.2     250.0  14.567241    12.65858
9      28.04  64.43    1011.9     260.0  14.567241    12.65858
10     28.04  67.21    1012.4     240.0  13.242946    11.50780
11     28.04  64.43    1012.2     240.0  17.215830    14.96014
12     28.04  62.21    1012.2     250.0  11.918651    10.35702
13     28.04  62.21    1012.7     260.0  17.215830    14.96014
14     28.04  59.65    1012.4     260.0  15.891535    13.80936
15     26.96  57.06    1011.4     260.0  17.215830    14.96014
16     28.40  64.93    1017.9     270.0  18.540125    16.11092
17     28.40  64.93    1017.9     330.0  17.215830    14.96014
18     24.08  54.68    1010.8     280.0  15.891535    13.80936
19     24.08  57.04    1011.9     290.0  10.594357     9.20624
20     19.94  49.62    1012.1     300.0  15.891535    13.80936
21     19.04  49.83    1013.2     330.0  13.242946    11.50780
22     15.08  45.43    1014.1     310.0  14.567241    12.65858
23     12.92  42.84    1014.4     320.0  11.918651    10.35702
24     15.08  49.19    1015.2     310.0  17.215830    14.96014
25     12.92  48.48    1016.0     320.0  21.188714    18.41248
26     12.02  48.69    1016.5     320.0  21.188714    18.41248
27     10.94  48.15    1016.4     310.0  18.540125    16.11092
28     10.94  50.34    1016.3     310.0  17.215830    14.96014
29     10.94  52.25    1016.3     330.0  14.567241    12.65858
...      ...    ...       ...       ...        ...         ...
26100  37.40  81.07    1017.9      70.0  10.594357     9.20624
26101  37.40  93.19    1017.9      40.0  18.540125    16.11092
26102  39.02  92.59     999.9      40.0  15.891535    13.80936
26103  37.94  88.76     998.7     350.0   9.270062     8.05546
26104  39.20  93.24    1017.9      50.0  23.837303    20.71404
26105  39.02  88.81     997.2     330.0  17.215830    14.96014
26106  37.40  81.07    1017.9     320.0  19.864419    17.26170
26107  37.40  86.89    1017.9     310.0  22.513008    19.56326
26108  37.40  81.07    1017.9     320.0  18.540125    16.11092
26109  37.04  79.38    1003.8     300.0  10.594357     9.20624
26110  35.06  73.39    1005.1     310.0  19.864419    17.26170
26111  33.98  72.78    1005.9     320.0  13.242946    11.50780
26112  33.98  72.78    1007.6     250.0  10.594357     9.20624
26113  33.98  75.88    1008.3     240.0   9.270062     8.05546
26114  33.98  70.30    1008.2     270.0  10.594357     9.20624
26115  33.08  73.19    1008.9       0.0   0.000000     0.00000
26116  33.08  67.81    1009.2     250.0  11.918651    10.35702
26117  33.98  70.30    1010.8     230.0   7.945768     6.90468
26118  35.06  70.42    1011.9     240.0  13.242946    11.50780
26119  33.98  67.45    1012.9     260.0  13.242946    11.50780
26120  33.08  65.07    1013.7     260.0  15.891535    13.80936
26121  33.80  70.28    1017.9     330.0  18.540125    16.11092
26122  28.40  60.54    1017.9     340.0  15.891535    13.80936
26123  23.00  54.51    1015.7     330.0  25.161598    21.86482
26124  21.92  53.97    1016.5     340.0  19.864419    17.26170
26125  19.94  51.78    1017.1     340.0  15.891535    13.80936
26126  17.06  49.51    1018.8     330.0  19.864419    17.26170
26127  15.08  49.19    1019.5     340.0  17.215830    14.96014
26128  12.92  46.74    1019.9     320.0  19.864419    17.26170
26129  10.94  46.41    1020.9     330.0  21.188714    18.41248

[26130 rows x 15 columns]

In [57]:
WeatherN4.head(n=5)

NameError: name 'WeatherN4' is not defined

In [65]:
WeatherC = WeatherN4
print(WeatherC)

      origin  year  month  day  hour  precip  visib         time_hour   temp  \
0        EWR  2013      1    1     0    0.00  10.00  12/31/2012 19:00  37.04
1        EWR  2013      1    1     1    0.00  10.00  12/31/2012 20:00  37.04
2        EWR  2013      1    1     2    0.00  10.00  12/31/2012 21:00  37.94
3        EWR  2013      1    1     3    0.00  10.00  12/31/2012 22:00  37.94
4        EWR  2013      1    1     4    0.00  10.00  12/31/2012 23:00  37.94
5        EWR  2013      1    1     6    0.00  10.00     1/1/2013 1:00  39.02
6        EWR  2013      1    1     7    0.00  10.00     1/1/2013 2:00  39.02
7        EWR  2013      1    1     8    0.00  10.00     1/1/2013 3:00  39.02
8        EWR  2013      1    1     9    0.00  10.00     1/1/2013 4:00  39.92
9        EWR  2013      1    1    10    0.00  10.00     1/1/2013 5:00  39.02
10       EWR  2013      1    1    11    0.00  10.00     1/1/2013 6:00  37.94
11       EWR  2013      1    1    12    0.00  10.00     1/1/2013 7:00  39.02
12       EWR  2013      1    1    13    0.00  10.00     1/1/2013 8:00  39.92
13       EWR  2013      1    1    14    0.00  10.00     1/1/2013 9:00  39.92
14       EWR  2013      1    1    15    0.00  10.00    1/1/2013 10:00  41.00
15       EWR  2013      1    1    16    0.00  10.00    1/1/2013 11:00  41.00
16       EWR  2013      1    1    17    0.00  10.00    1/1/2013 12:00  39.20
17       EWR  2013      1    1    18    0.00  10.00    1/1/2013 13:00  39.20
18       EWR  2013      1    1    19    0.00  10.00    1/1/2013 14:00  39.02
19       EWR  2013      1    1    20    0.00  10.00    1/1/2013 15:00  37.94
20       EWR  2013      1    1    21    0.00  10.00    1/1/2013 16:00  37.04
21       EWR  2013      1    1    22    0.00  10.00    1/1/2013 17:00  35.96
22       EWR  2013      1    1    23    0.00  10.00    1/1/2013 18:00  33.98
23       EWR  2013      1    2     0    0.00  10.00    1/1/2013 19:00  33.08
24       EWR  2013      1    2     1    0.00  10.00    1/1/2013 20:00  32.00
25       EWR  2013      1    2     2    0.00  10.00    1/1/2013 21:00  30.02
26       EWR  2013      1    2     3    0.00  10.00    1/1/2013 22:00  28.94
27       EWR  2013      1    2     4    0.00  10.00    1/1/2013 23:00  28.04
28       EWR  2013      1    2     5    0.00  10.00     1/2/2013 0:00  26.96
29       EWR  2013      1    2     6    0.00  10.00     1/2/2013 1:00  26.06
...      ...   ...    ...  ...   ...     ...    ...               ...    ...
26100    LGA  2013     12   29    18    0.06   2.50  12/29/2013 13:00  42.80
26101    LGA  2013     12   29    19    0.06   1.75  12/29/2013 14:00  39.20
26102    LGA  2013     12   29    20    0.37   1.50  12/29/2013 15:00  41.00
26103    LGA  2013     12   29    21    0.28   1.50  12/29/2013 16:00  41.00
26104    LGA  2013     12   29    22    0.03   2.00  12/29/2013 17:00  41.00
26105    LGA  2013     12   29    23    0.00   3.00  12/29/2013 18:00  42.08
26106    LGA  2013     12   30     0    0.00   8.00  12/29/2013 19:00  42.80
26107    LGA  2013     12   30     1    0.00   6.00  12/29/2013 20:00  41.00
26108    LGA  2013     12   30     2    0.00  10.00  12/29/2013 21:00  42.80
26109    LGA  2013     12   30     3    0.00  10.00  12/29/2013 22:00  42.98
26110    LGA  2013     12   30     4    0.00  10.00  12/29/2013 23:00  42.98
26111    LGA  2013     12   30     5    0.00  10.00   12/30/2013 0:00  42.08
26112    LGA  2013     12   30     6    0.00  10.00   12/30/2013 1:00  42.08
26113    LGA  2013     12   30     7    0.00  10.00   12/30/2013 2:00  41.00
26114    LGA  2013     12   30     8    0.00  10.00   12/30/2013 3:00  42.98
26115    LGA  2013     12   30     9    0.00  10.00   12/30/2013 4:00  41.00
26116    LGA  2013     12   30    10    0.00  10.00   12/30/2013 5:00  42.98
26117    LGA  2013     12   30    11    0.00  10.00   12/30/2013 6:00  42.98
26118    LGA  2013     12   30    12    0.00  10.00   12/30/2013 7:00  44.06
26119    LGA  2013     12   30    13    0.00  10.00   12/30/2013 8:00  44.06
26120    LGA  2013     12   30    14    0.00  10.00   12/30/2013 9:00  44.06
26121    LGA  2013     12   30    15    0.00  10.00  12/30/2013 10:00  42.80
26122    LGA  2013     12   30    16    0.00  10.00  12/30/2013 11:00  41.00
26123    LGA  2013     12   30    17    0.00  10.00  12/30/2013 12:00  37.94
26124    LGA  2013     12   30    18    0.00  10.00  12/30/2013 13:00  37.04
26125    LGA  2013     12   30    19    0.00  10.00  12/30/2013 14:00  35.96
26126    LGA  2013     12   30    20    0.00  10.00  12/30/2013 15:00  33.98
26127    LGA  2013     12   30    21    0.00  10.00  12/30/2013 16:00  32.00
26128    LGA  2013     12   30    22    0.00  10.00  12/30/2013 17:00  30.92
26129    LGA  2013     12   30    23    0.00  10.00  12/30/2013 18:00  28.94

        dewp  humid  pressure  wind_dir  wind_gust  wind_speed
0      21.92  53.97    1013.9     230.0  11.918651    10.35702
1      21.92  53.97    1013.0     230.0  15.891535    13.80936
2      21.92  52.09    1012.6     230.0  14.567241    12.65858
3      23.00  54.51    1012.7     230.0  15.891535    13.80936
4      24.08  57.04    1012.8     240.0  17.215830    14.96014
5      26.06  59.37    1012.0     270.0  11.918651    10.35702
6      26.96  61.63    1012.3     250.0   9.270062     8.05546
7      28.04  64.43    1012.5     240.0  13.242946    11.50780
8      28.04  62.21    1012.2     250.0  14.567241    12.65858
9      28.04  64.43    1011.9     260.0  14.567241    12.65858
10     28.04  67.21    1012.4     240.0  13.242946    11.50780
11     28.04  64.43    1012.2     240.0  17.215830    14.96014
12     28.04  62.21    1012.2     250.0  11.918651    10.35702
13     28.04  62.21    1012.7     260.0  17.215830    14.96014
14     28.04  59.65    1012.4     260.0  15.891535    13.80936
15     26.96  57.06    1011.4     260.0  17.215830    14.96014
16     28.40  64.93    1017.9     270.0  18.540125    16.11092
17     28.40  64.93    1017.9     330.0  17.215830    14.96014
18     24.08  54.68    1010.8     280.0  15.891535    13.80936
19     24.08  57.04    1011.9     290.0  10.594357     9.20624
20     19.94  49.62    1012.1     300.0  15.891535    13.80936
21     19.04  49.83    1013.2     330.0  13.242946    11.50780
22     15.08  45.43    1014.1     310.0  14.567241    12.65858
23     12.92  42.84    1014.4     320.0  11.918651    10.35702
24     15.08  49.19    1015.2     310.0  17.215830    14.96014
25     12.92  48.48    1016.0     320.0  21.188714    18.41248
26     12.02  48.69    1016.5     320.0  21.188714    18.41248
27     10.94  48.15    1016.4     310.0  18.540125    16.11092
28     10.94  50.34    1016.3     310.0  17.215830    14.96014
29     10.94  52.25    1016.3     330.0  14.567241    12.65858
...      ...    ...       ...       ...        ...         ...
26100  37.40  81.07    1017.9      70.0  10.594357     9.20624
26101  37.40  93.19    1017.9      40.0  18.540125    16.11092
26102  39.02  92.59     999.9      40.0  15.891535    13.80936
26103  37.94  88.76     998.7     350.0   9.270062     8.05546
26104  39.20  93.24    1017.9      50.0  23.837303    20.71404
26105  39.02  88.81     997.2     330.0  17.215830    14.96014
26106  37.40  81.07    1017.9     320.0  19.864419    17.26170
26107  37.40  86.89    1017.9     310.0  22.513008    19.56326
26108  37.40  81.07    1017.9     320.0  18.540125    16.11092
26109  37.04  79.38    1003.8     300.0  10.594357     9.20624
26110  35.06  73.39    1005.1     310.0  19.864419    17.26170
26111  33.98  72.78    1005.9     320.0  13.242946    11.50780
26112  33.98  72.78    1007.6     250.0  10.594357     9.20624
26113  33.98  75.88    1008.3     240.0   9.270062     8.05546
26114  33.98  70.30    1008.2     270.0  10.594357     9.20624
26115  33.08  73.19    1008.9       0.0   0.000000     0.00000
26116  33.08  67.81    1009.2     250.0  11.918651    10.35702
26117  33.98  70.30    1010.8     230.0   7.945768     6.90468
26118  35.06  70.42    1011.9     240.0  13.242946    11.50780
26119  33.98  67.45    1012.9     260.0  13.242946    11.50780
26120  33.08  65.07    1013.7     260.0  15.891535    13.80936
26121  33.80  70.28    1017.9     330.0  18.540125    16.11092
26122  28.40  60.54    1017.9     340.0  15.891535    13.80936
26123  23.00  54.51    1015.7     330.0  25.161598    21.86482
26124  21.92  53.97    1016.5     340.0  19.864419    17.26170
26125  19.94  51.78    1017.1     340.0  15.891535    13.80936
26126  17.06  49.51    1018.8     330.0  19.864419    17.26170
26127  15.08  49.19    1019.5     340.0  17.215830    14.96014
26128  12.92  46.74    1019.9     320.0  19.864419    17.26170
26129  10.94  46.41    1020.9     330.0  21.188714    18.41248

[26130 rows x 15 columns]

In [5]:
#Now to go through the same process for the Flights data

Flight.count()

Column1           336776
year              336776
month             336776
day               336776
dep_time          328521
sched_dep_time    336776
dep_delay         328521
arr_time          328063
sched_arr_time    336776
arr_delay         327346
carrier           336776
flight            336776
tailnum           334264
origin            336776
dest              336776
air_time          327346
distance          336776
hour              336776
minute            336776
time_hour         336776
dtype: int64

In [6]:
Flight.shape[0]

336776

In [24]:
a = Flight["dep_time"].mean()
b = Flight["dep_delay"].mean()
c = Flight["arr_time"].mean()
d = Flight["arr_delay"].mean()
e = Flight["air_time"].mean()
print(a, b, c, d, e)

#tailnum column cannot provide a mean...

1349.1099473093045 12.639070257304708 1502.0549985825894 6.89537675731489 150.68646019807787

In [25]:
f = Flight["dep_time"].fillna(a)
print(f)

0          517.000000
1          533.000000
2          542.000000
3          544.000000
4          554.000000
5          554.000000
6          555.000000
7          557.000000
8          557.000000
9          558.000000
10         558.000000
11         558.000000
12         558.000000
13         558.000000
14         559.000000
15         559.000000
16         559.000000
17         600.000000
18         600.000000
19         601.000000
20         602.000000
21         602.000000
22         606.000000
23         606.000000
24         607.000000
25         608.000000
26         611.000000
27         613.000000
28         615.000000
29         615.000000
             ...
336746    2123.000000
336747    2127.000000
336748    2128.000000
336749    2129.000000
336750    2131.000000
336751    2140.000000
336752    2142.000000
336753    2145.000000
336754    2147.000000
336755    2149.000000
336756    2150.000000
336757    2159.000000
336758    2203.000000
336759    2207.000000
336760    2211.000000
336761    2231.000000
336762    2233.000000
336763    2235.000000
336764    2237.000000
336765    2240.000000
336766    2240.000000
336767    2241.000000
336768    2307.000000
336769    2349.000000
336770    1349.109947
336771    1349.109947
336772    1349.109947
336773    1349.109947
336774    1349.109947
336775    1349.109947
Name: dep_time, Length: 336776, dtype: float64

In [17]:
f.loc[9751:9762, ]
#checking to see if the NaNs were replaced with the mean

9751    1349.109947
9752    1349.109947
9753    1349.109947
9754    1349.109947
9755    1349.109947
9756    1349.109947
9757    1349.109947
9758    1349.109947
9759    1349.109947
9760    1349.109947
9761    1349.109947
9762      30.000000
Name: dep_time, dtype: float64

In [26]:
g = Flight["dep_delay"].fillna(b)
print(g)

0           2.00000
1           4.00000
2           2.00000
3          -1.00000
4          -6.00000
5          -4.00000
6          -5.00000
7          -3.00000
8          -3.00000
9          -2.00000
10         -2.00000
11         -2.00000
12         -2.00000
13         -2.00000
14         -1.00000
15          0.00000
16         -1.00000
17          0.00000
18          0.00000
19          1.00000
20         -8.00000
21         -3.00000
22         -4.00000
23         -4.00000
24          0.00000
25          8.00000
26         11.00000
27          3.00000
28          0.00000
29          0.00000
            ...
336746     -2.00000
336747     -2.00000
336748     -2.00000
336749     30.00000
336750     -9.00000
336751      0.00000
336752     13.00000
336753      0.00000
336754     10.00000
336755     -7.00000
336756     -9.00000
336757    194.00000
336758     -2.00000
336759     27.00000
336760     72.00000
336761    -14.00000
336762     80.00000
336763    154.00000
336764     -8.00000
336765     -5.00000
336766    -10.00000
336767     -5.00000
336768     12.00000
336769    -10.00000
336770     12.63907
336771     12.63907
336772     12.63907
336773     12.63907
336774     12.63907
336775     12.63907
Name: dep_delay, Length: 336776, dtype: float64

In [19]:
g.loc[11264:11280, ]

11264    12.63907
11265    12.63907
11266    12.63907
11267    12.63907
11268    12.63907
11269    12.63907
11270    12.63907
11271    12.63907
11272    12.63907
11273    12.63907
11274    12.63907
11275    12.63907
11276    12.63907
11277    12.63907
11278    12.63907
11279    12.63907
11280    -7.00000
Name: dep_delay, dtype: float64

In [27]:
h = Flight["arr_time"].fillna(c)
print(h)

0          830.000000
1          850.000000
2          923.000000
3         1004.000000
4          812.000000
5          740.000000
6          913.000000
7          709.000000
8          838.000000
9          753.000000
10         849.000000
11         853.000000
12         924.000000
13         923.000000
14         941.000000
15         702.000000
16         854.000000
17         851.000000
18         837.000000
19         844.000000
20         812.000000
21         821.000000
22         858.000000
23         837.000000
24         858.000000
25         807.000000
26         945.000000
27         925.000000
28        1039.000000
29         833.000000
             ...
336746    2223.000000
336747    2314.000000
336748    2328.000000
336749    2230.000000
336750    2225.000000
336751      10.000000
336752    2250.000000
336753     115.000000
336754      30.000000
336755    2245.000000
336756    2250.000000
336757    2344.000000
336758    2339.000000
336759    2257.000000
336760    2339.000000
336761    2335.000000
336762     112.000000
336763      59.000000
336764    2345.000000
336765    2334.000000
336766    2347.000000
336767    2345.000000
336768    2359.000000
336769     325.000000
336770    1502.054999
336771    1502.054999
336772    1502.054999
336773    1502.054999
336774    1502.054999
336775    1502.054999
Name: arr_time, Length: 336776, dtype: float64

In [23]:
h.loc[11264:11280, ]

11264    1502.054999
11265    1502.054999
11266    1502.054999
11267    1502.054999
11268    1502.054999
11269    1502.054999
11270    1502.054999
11271    1502.054999
11272    1502.054999
11273    1502.054999
11274    1502.054999
11275    1502.054999
11276    1502.054999
11277    1502.054999
11278    1502.054999
11279    1502.054999
11280     640.000000
Name: arr_time, dtype: float64

In [28]:
i = Flight["arr_delay"].fillna(d)
print(i)

0          11.000000
1          20.000000
2          33.000000
3         -18.000000
4         -25.000000
5          12.000000
6          19.000000
7         -14.000000
8          -8.000000
9           8.000000
10         -2.000000
11         -3.000000
12          7.000000
13        -14.000000
14         31.000000
15         -4.000000
16         -8.000000
17         -7.000000
18         12.000000
19         -6.000000
20         -8.000000
21         16.000000
22        -12.000000
23         -8.000000
24        -17.000000
25         32.000000
26         14.000000
27          4.000000
28        -21.000000
29         -9.000000
             ...
336746    -24.000000
336747     -9.000000
336748    -31.000000
336749     -2.000000
336750    -30.000000
336751    -30.000000
336752     11.000000
336753    -25.000000
336754      3.000000
336755    -23.000000
336756    -16.000000
336757    194.000000
336758      8.000000
336759      7.000000
336760     57.000000
336761    -21.000000
336762     42.000000
336763    130.000000
336764     -8.000000
336765    -17.000000
336766    -20.000000
336767    -16.000000
336768      1.000000
336769    -25.000000
336770      6.895377
336771      6.895377
336772      6.895377
336773      6.895377
336774      6.895377
336775      6.895377
Name: arr_delay, Length: 336776, dtype: float64

In [27]:
i.loc[2689:2700, ]

2689      6.895377
2690      6.895377
2691      6.895377
2692      6.895377
2693      6.895377
2694      6.895377
2695      6.895377
2696      6.895377
2697      6.895377
2698      6.895377
2699     23.000000
2700    125.000000
Name: arr_delay, dtype: float64

In [29]:
j = Flight["air_time"].fillna(e)
print(j)

0         227.00000
1         227.00000
2         160.00000
3         183.00000
4         116.00000
5         150.00000
6         158.00000
7          53.00000
8         140.00000
9         138.00000
10        149.00000
11        158.00000
12        345.00000
13        361.00000
14        257.00000
15         44.00000
16        337.00000
17        152.00000
18        134.00000
19        147.00000
20        170.00000
21        105.00000
22        152.00000
23        128.00000
24        157.00000
25        139.00000
26        366.00000
27        175.00000
28        182.00000
29        120.00000
            ...
336746     45.00000
336747     72.00000
336748    213.00000
336749     45.00000
336750     36.00000
336751    298.00000
336752     47.00000
336753    192.00000
336754    139.00000
336755     37.00000
336756     39.00000
336757     50.00000
336758     61.00000
336759     97.00000
336760    120.00000
336761     48.00000
336762    318.00000
336763    123.00000
336764     43.00000
336765     41.00000
336766     52.00000
336767     47.00000
336768     33.00000
336769    196.00000
336770    150.68646
336771    150.68646
336772    150.68646
336773    150.68646
336774    150.68646
336775    150.68646
Name: air_time, Length: 336776, dtype: float64

In [42]:
j.loc[13958:13986, ]

13958    150.68646
13959    150.68646
13960    150.68646
13961    150.68646
13962    150.68646
13963    150.68646
13964    150.68646
13965    150.68646
13966    150.68646
13967    150.68646
13968    150.68646
13969    150.68646
13970    150.68646
13971    150.68646
13972    150.68646
13973    150.68646
13974    150.68646
13975    150.68646
13976    150.68646
13977    150.68646
13978    150.68646
13979    150.68646
13980    150.68646
13981    150.68646
13982    150.68646
13983    150.68646
13984    150.68646
13985    150.68646
13986    150.68646
Name: air_time, dtype: float64

In [30]:
Flight.head(n=5)

,Column1,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,1,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,1/1/2013 5:00
1,2,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,1/1/2013 5:00
2,3,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,1/1/2013 5:00
3,4,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,1/1/2013 5:00
4,5,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,1/1/2013 6:00

In [31]:
FlightN2 = Flight.filter(['Column1', 'year', 'month', 'day', 'sched_dep_time', 'sched_arr_time', 'carrier', 'flight', 'origin', 'dest', 'distance', 'hour', 'minute', 'time_hour'], axis=1)
#works, these are the columns to keep...
#also dropping tailnum because it has missing values and is irrelevant for finding the desired information
print(FlightN2)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

[336776 rows x 14 columns]

In [32]:
#add the modified columns to the reduced DF
#one at a time first..

FlightN3 = FlightN2.assign(dep_time=f.values)
print(FlightN3)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time
0        517.000000
1        533.000000
2        542.000000
3        544.000000
4        554.000000
5        554.000000
6        555.000000
7        557.000000
8        557.000000
9        558.000000
10       558.000000
11       558.000000
12       558.000000
13       558.000000
14       559.000000
15       559.000000
16       559.000000
17       600.000000
18       600.000000
19       601.000000
20       602.000000
21       602.000000
22       606.000000
23       606.000000
24       607.000000
25       608.000000
26       611.000000
27       613.000000
28       615.000000
29       615.000000
...             ...
336746  2123.000000
336747  2127.000000
336748  2128.000000
336749  2129.000000
336750  2131.000000
336751  2140.000000
336752  2142.000000
336753  2145.000000
336754  2147.000000
336755  2149.000000
336756  2150.000000
336757  2159.000000
336758  2203.000000
336759  2207.000000
336760  2211.000000
336761  2231.000000
336762  2233.000000
336763  2235.000000
336764  2237.000000
336765  2240.000000
336766  2240.000000
336767  2241.000000
336768  2307.000000
336769  2349.000000
336770  1349.109947
336771  1349.109947
336772  1349.109947
336773  1349.109947
336774  1349.109947
336775  1349.109947

[336776 rows x 15 columns]

In [33]:
FlightN4 = FlightN3.assign(dep_delay=g.values, arr_time=h.values, arr_delay=i.values, air_time=j.values)
print(FlightN4)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time   air_time   arr_delay     arr_time  dep_delay
0        517.000000  227.00000   11.000000   830.000000    2.00000
1        533.000000  227.00000   20.000000   850.000000    4.00000
2        542.000000  160.00000   33.000000   923.000000    2.00000
3        544.000000  183.00000  -18.000000  1004.000000   -1.00000
4        554.000000  116.00000  -25.000000   812.000000   -6.00000
5        554.000000  150.00000   12.000000   740.000000   -4.00000
6        555.000000  158.00000   19.000000   913.000000   -5.00000
7        557.000000   53.00000  -14.000000   709.000000   -3.00000
8        557.000000  140.00000   -8.000000   838.000000   -3.00000
9        558.000000  138.00000    8.000000   753.000000   -2.00000
10       558.000000  149.00000   -2.000000   849.000000   -2.00000
11       558.000000  158.00000   -3.000000   853.000000   -2.00000
12       558.000000  345.00000    7.000000   924.000000   -2.00000
13       558.000000  361.00000  -14.000000   923.000000   -2.00000
14       559.000000  257.00000   31.000000   941.000000   -1.00000
15       559.000000   44.00000   -4.000000   702.000000    0.00000
16       559.000000  337.00000   -8.000000   854.000000   -1.00000
17       600.000000  152.00000   -7.000000   851.000000    0.00000
18       600.000000  134.00000   12.000000   837.000000    0.00000
19       601.000000  147.00000   -6.000000   844.000000    1.00000
20       602.000000  170.00000   -8.000000   812.000000   -8.00000
21       602.000000  105.00000   16.000000   821.000000   -3.00000
22       606.000000  152.00000  -12.000000   858.000000   -4.00000
23       606.000000  128.00000   -8.000000   837.000000   -4.00000
24       607.000000  157.00000  -17.000000   858.000000    0.00000
25       608.000000  139.00000   32.000000   807.000000    8.00000
26       611.000000  366.00000   14.000000   945.000000   11.00000
27       613.000000  175.00000    4.000000   925.000000    3.00000
28       615.000000  182.00000  -21.000000  1039.000000    0.00000
29       615.000000  120.00000   -9.000000   833.000000    0.00000
...             ...        ...         ...          ...        ...
336746  2123.000000   45.00000  -24.000000  2223.000000   -2.00000
336747  2127.000000   72.00000   -9.000000  2314.000000   -2.00000
336748  2128.000000  213.00000  -31.000000  2328.000000   -2.00000
336749  2129.000000   45.00000   -2.000000  2230.000000   30.00000
336750  2131.000000   36.00000  -30.000000  2225.000000   -9.00000
336751  2140.000000  298.00000  -30.000000    10.000000    0.00000
336752  2142.000000   47.00000   11.000000  2250.000000   13.00000
336753  2145.000000  192.00000  -25.000000   115.000000    0.00000
336754  2147.000000  139.00000    3.000000    30.000000   10.00000
336755  2149.000000   37.00000  -23.000000  2245.000000   -7.00000
336756  2150.000000   39.00000  -16.000000  2250.000000   -9.00000
336757  2159.000000   50.00000  194.000000  2344.000000  194.00000
336758  2203.000000   61.00000    8.000000  2339.000000   -2.00000
336759  2207.000000   97.00000    7.000000  2257.000000   27.00000
336760  2211.000000  120.00000   57.000000  2339.000000   72.00000
336761  2231.000000   48.00000  -21.000000  2335.000000  -14.00000
336762  2233.000000  318.00000   42.000000   112.000000   80.00000
336763  2235.000000  123.00000  130.000000    59.000000  154.00000
336764  2237.000000   43.00000   -8.000000  2345.000000   -8.00000
336765  2240.000000   41.00000  -17.000000  2334.000000   -5.00000
336766  2240.000000   52.00000  -20.000000  2347.000000  -10.00000
336767  2241.000000   47.00000  -16.000000  2345.000000   -5.00000
336768  2307.000000   33.00000    1.000000  2359.000000   12.00000
336769  2349.000000  196.00000  -25.000000   325.000000  -10.00000
336770  1349.109947  150.68646    6.895377  1502.054999   12.63907
336771  1349.109947  150.68646    6.895377  1502.054999   12.63907
336772  1349.109947  150.68646    6.895377  1502.054999   12.63907
336773  1349.109947  150.68646    6.895377  1502.054999   12.63907
336774  1349.109947  150.68646    6.895377  1502.054999   12.63907
336775  1349.109947  150.68646    6.895377  1502.054999   12.63907

[336776 rows x 19 columns]

In [34]:
FlightC = FlightN4
print(FlightC)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time   air_time   arr_delay     arr_time  dep_delay
0        517.000000  227.00000   11.000000   830.000000    2.00000
1        533.000000  227.00000   20.000000   850.000000    4.00000
2        542.000000  160.00000   33.000000   923.000000    2.00000
3        544.000000  183.00000  -18.000000  1004.000000   -1.00000
4        554.000000  116.00000  -25.000000   812.000000   -6.00000
5        554.000000  150.00000   12.000000   740.000000   -4.00000
6        555.000000  158.00000   19.000000   913.000000   -5.00000
7        557.000000   53.00000  -14.000000   709.000000   -3.00000
8        557.000000  140.00000   -8.000000   838.000000   -3.00000
9        558.000000  138.00000    8.000000   753.000000   -2.00000
10       558.000000  149.00000   -2.000000   849.000000   -2.00000
11       558.000000  158.00000   -3.000000   853.000000   -2.00000
12       558.000000  345.00000    7.000000   924.000000   -2.00000
13       558.000000  361.00000  -14.000000   923.000000   -2.00000
14       559.000000  257.00000   31.000000   941.000000   -1.00000
15       559.000000   44.00000   -4.000000   702.000000    0.00000
16       559.000000  337.00000   -8.000000   854.000000   -1.00000
17       600.000000  152.00000   -7.000000   851.000000    0.00000
18       600.000000  134.00000   12.000000   837.000000    0.00000
19       601.000000  147.00000   -6.000000   844.000000    1.00000
20       602.000000  170.00000   -8.000000   812.000000   -8.00000
21       602.000000  105.00000   16.000000   821.000000   -3.00000
22       606.000000  152.00000  -12.000000   858.000000   -4.00000
23       606.000000  128.00000   -8.000000   837.000000   -4.00000
24       607.000000  157.00000  -17.000000   858.000000    0.00000
25       608.000000  139.00000   32.000000   807.000000    8.00000
26       611.000000  366.00000   14.000000   945.000000   11.00000
27       613.000000  175.00000    4.000000   925.000000    3.00000
28       615.000000  182.00000  -21.000000  1039.000000    0.00000
29       615.000000  120.00000   -9.000000   833.000000    0.00000
...             ...        ...         ...          ...        ...
336746  2123.000000   45.00000  -24.000000  2223.000000   -2.00000
336747  2127.000000   72.00000   -9.000000  2314.000000   -2.00000
336748  2128.000000  213.00000  -31.000000  2328.000000   -2.00000
336749  2129.000000   45.00000   -2.000000  2230.000000   30.00000
336750  2131.000000   36.00000  -30.000000  2225.000000   -9.00000
336751  2140.000000  298.00000  -30.000000    10.000000    0.00000
336752  2142.000000   47.00000   11.000000  2250.000000   13.00000
336753  2145.000000  192.00000  -25.000000   115.000000    0.00000
336754  2147.000000  139.00000    3.000000    30.000000   10.00000
336755  2149.000000   37.00000  -23.000000  2245.000000   -7.00000
336756  2150.000000   39.00000  -16.000000  2250.000000   -9.00000
336757  2159.000000   50.00000  194.000000  2344.000000  194.00000
336758  2203.000000   61.00000    8.000000  2339.000000   -2.00000
336759  2207.000000   97.00000    7.000000  2257.000000   27.00000
336760  2211.000000  120.00000   57.000000  2339.000000   72.00000
336761  2231.000000   48.00000  -21.000000  2335.000000  -14.00000
336762  2233.000000  318.00000   42.000000   112.000000   80.00000
336763  2235.000000  123.00000  130.000000    59.000000  154.00000
336764  2237.000000   43.00000   -8.000000  2345.000000   -8.00000
336765  2240.000000   41.00000  -17.000000  2334.000000   -5.00000
336766  2240.000000   52.00000  -20.000000  2347.000000  -10.00000
336767  2241.000000   47.00000  -16.000000  2345.000000   -5.00000
336768  2307.000000   33.00000    1.000000  2359.000000   12.00000
336769  2349.000000  196.00000  -25.000000   325.000000  -10.00000
336770  1349.109947  150.68646    6.895377  1502.054999   12.63907
336771  1349.109947  150.68646    6.895377  1502.054999   12.63907
336772  1349.109947  150.68646    6.895377  1502.054999   12.63907
336773  1349.109947  150.68646    6.895377  1502.054999   12.63907
336774  1349.109947  150.68646    6.895377  1502.054999   12.63907
336775  1349.109947  150.68646    6.895377  1502.054999   12.63907

[336776 rows x 19 columns]

In [45]:
#now printing row counts for the cleaned data sets
Airline.count()

Unnamed: 0    16
carrier       16
name          16
dtype: int64

In [46]:
Airline.shape[0]

16

In [47]:
Airport.count()

Unnamed: 0    1458
faa           1458
name          1458
lat           1458
lon           1458
alt           1458
tz            1458
dst           1458
tzone         1458
dtype: int64

In [48]:
Airport.shape[0]

1458

In [49]:
FlightC.count()

Column1           336776
year              336776
month             336776
day               336776
sched_dep_time    336776
sched_arr_time    336776
carrier           336776
flight            336776
origin            336776
dest              336776
distance          336776
hour              336776
minute            336776
time_hour         336776
dep_time          336776
air_time          336776
arr_delay         336776
arr_time          336776
dep_delay         336776
dtype: int64

In [50]:
FlightC.shape[0]

336776

In [54]:
PlaneC.count()

tailnum         3322
year            3252
type            3322
manufacturer    3322
model           3322
engines         3322
seats           3322
engine          3322
dtype: int64

In [55]:
PlaneC.shape[0]

3322

In [76]:
WeatherC.count()

origin        26130
year          26130
month         26130
day           26130
hour          26130
precip        26130
visib         26130
time_hour     26130
temp          26130
dewp          26130
humid         26130
pressure      26130
wind_dir      26130
wind_gust     26130
wind_speed    26130
dtype: int64

In [77]:
WeatherC.shape[0]

26130

In [80]:
k = FlightC.groupby('dest').count()
print(k)

#Finding the Top 5 busiest airports by highest average number of flights arrived per day

      Column1   year  month    day  sched_dep_time  sched_arr_time  carrier  \
dest
ABQ       254    254    254    254             254             254      254
ACK       265    265    265    265             265             265      265
ALB       439    439    439    439             439             439      439
ANC         8      8      8      8               8               8        8
ATL     17215  17215  17215  17215           17215           17215    17215
AUS      2439   2439   2439   2439            2439            2439     2439
AVL       275    275    275    275             275             275      275
BDL       443    443    443    443             443             443      443
BGR       375    375    375    375             375             375      375
BHM       297    297    297    297             297             297      297
BNA      6333   6333   6333   6333            6333            6333     6333
BOS     15508  15508  15508  15508           15508           15508    15508
BQN       896    896    896    896             896             896      896
BTV      2589   2589   2589   2589            2589            2589     2589
BUF      4681   4681   4681   4681            4681            4681     4681
BUR       371    371    371    371             371             371      371
BWI      1781   1781   1781   1781            1781            1781     1781
BZN        36     36     36     36              36              36       36
CAE       116    116    116    116             116             116      116
CAK       864    864    864    864             864             864      864
CHO        52     52     52     52              52              52       52
CHS      2884   2884   2884   2884            2884            2884     2884
CLE      4573   4573   4573   4573            4573            4573     4573
CLT     14064  14064  14064  14064           14064           14064    14064
CMH      3524   3524   3524   3524            3524            3524     3524
CRW       138    138    138    138             138             138      138
CVG      3941   3941   3941   3941            3941            3941     3941
DAY      1525   1525   1525   1525            1525            1525     1525
DCA      9705   9705   9705   9705            9705            9705     9705
DEN      7266   7266   7266   7266            7266            7266     7266
...       ...    ...    ...    ...             ...             ...      ...
PIT      2875   2875   2875   2875            2875            2875     2875
PSE       365    365    365    365             365             365      365
PSP        19     19     19     19              19              19       19
PVD       376    376    376    376             376             376      376
PWM      2352   2352   2352   2352            2352            2352     2352
RDU      8163   8163   8163   8163            8163            8163     8163
RIC      2454   2454   2454   2454            2454            2454     2454
ROC      2416   2416   2416   2416            2416            2416     2416
RSW      3537   3537   3537   3537            3537            3537     3537
SAN      2737   2737   2737   2737            2737            2737     2737
SAT       686    686    686    686             686             686      686
SAV       804    804    804    804             804             804      804
SBN        10     10     10     10              10              10       10
SDF      1157   1157   1157   1157            1157            1157     1157
SEA      3923   3923   3923   3923            3923            3923     3923
SFO     13331  13331  13331  13331           13331           13331    13331
SJC       329    329    329    329             329             329      329
SJU      5819   5819   5819   5819            5819            5819     5819
SLC      2467   2467   2467   2467            2467            2467     2467
SMF       284    284    284    284             284             284      284
SNA       825    825    825    825             825             825      825
SRQ      1211   1211   1211   1211            1211            1211     1211
STL      4339   4339   4339   4339            4339            4339     4339
STT       522    522    522    522             522             522      522
SYR      1761   1761   1761   1761            1761            1761     1761
TPA      7466   7466   7466   7466            7466            7466     7466
TUL       315    315    315    315             315             315      315
TVC       101    101    101    101             101             101      101
TYS       631    631    631    631             631             631      631
XNA      1036   1036   1036   1036            1036            1036     1036

      flight  origin  distance   hour  minute  time_hour  dep_time  air_time  \
dest
ABQ      254     254       254    254     254        254       254       254
ACK      265     265       265    265     265        265       265       265
ALB      439     439       439    439     439        439       439       439
ANC        8       8         8      8       8          8         8         8
ATL    17215   17215     17215  17215   17215      17215     17215     17215
AUS     2439    2439      2439   2439    2439       2439      2439      2439
AVL      275     275       275    275     275        275       275       275
BDL      443     443       443    443     443        443       443       443
BGR      375     375       375    375     375        375       375       375
BHM      297     297       297    297     297        297       297       297
BNA     6333    6333      6333   6333    6333       6333      6333      6333
BOS    15508   15508     15508  15508   15508      15508     15508     15508
BQN      896     896       896    896     896        896       896       896
BTV     2589    2589      2589   2589    2589       2589      2589      2589
BUF     4681    4681      4681   4681    4681       4681      4681      4681
BUR      371     371       371    371     371        371       371       371
BWI     1781    1781      1781   1781    1781       1781      1781      1781
BZN       36      36        36     36      36         36        36        36
CAE      116     116       116    116     116        116       116       116
CAK      864     864       864    864     864        864       864       864
CHO       52      52        52     52      52         52        52        52
CHS     2884    2884      2884   2884    2884       2884      2884      2884
CLE     4573    4573      4573   4573    4573       4573      4573      4573
CLT    14064   14064     14064  14064   14064      14064     14064     14064
CMH     3524    3524      3524   3524    3524       3524      3524      3524
CRW      138     138       138    138     138        138       138       138
CVG     3941    3941      3941   3941    3941       3941      3941      3941
DAY     1525    1525      1525   1525    1525       1525      1525      1525
DCA     9705    9705      9705   9705    9705       9705      9705      9705
DEN     7266    7266      7266   7266    7266       7266      7266      7266
...      ...     ...       ...    ...     ...        ...       ...       ...
PIT     2875    2875      2875   2875    2875       2875      2875      2875
PSE      365     365       365    365     365        365       365       365
PSP       19      19        19     19      19         19        19        19
PVD      376     376       376    376     376        376       376       376
PWM     2352    2352      2352   2352    2352       2352      2352      2352
RDU     8163    8163      8163   8163    8163       8163      8163      8163
RIC     2454    2454      2454   2454    2454       2454      2454      2454
ROC     2416    2416      2416   2416    2416       2416      2416      2416
RSW     3537    3537      3537   3537    3537       3537      3537      3537
SAN     2737    2737      2737   2737    2737       2737      2737      2737
SAT      686     686       686    686     686        686       686       686
SAV      804     804       804    804     804        804       804       804
SBN       10      10        10     10      10         10        10        10
SDF     1157    1157      1157   1157    1157       1157      1157      1157
SEA     3923    3923      3923   3923    3923       3923      3923      3923
SFO    13331   13331     13331  13331   13331      13331     13331     13331
SJC      329     329       329    329     329        329       329       329
SJU     5819    5819      5819   5819    5819       5819      5819      5819
SLC     2467    2467      2467   2467    2467       2467      2467      2467
SMF      284     284       284    284     284        284       284       284
SNA      825     825       825    825     825        825       825       825
SRQ     1211    1211      1211   1211    1211       1211      1211      1211
STL     4339    4339      4339   4339    4339       4339      4339      4339
STT      522     522       522    522     522        522       522       522
SYR     1761    1761      1761   1761    1761       1761      1761      1761
TPA     7466    7466      7466   7466    7466       7466      7466      7466
TUL      315     315       315    315     315        315       315       315
TVC      101     101       101    101     101        101       101       101
TYS      631     631       631    631     631        631       631       631
XNA     1036    1036      1036   1036    1036       1036      1036      1036

      arr_delay  arr_time  dep_delay
dest
ABQ         254       254        254
ACK         265       265        265
ALB         439       439        439
ANC           8         8          8
ATL       17215     17215      17215
AUS        2439      2439       2439
AVL         275       275        275
BDL         443       443        443
BGR         375       375        375
BHM         297       297        297
BNA        6333      6333       6333
BOS       15508     15508      15508
BQN         896       896        896
BTV        2589      2589       2589
BUF        4681      4681       4681
BUR         371       371        371
BWI        1781      1781       1781
BZN          36        36         36
CAE         116       116        116
CAK         864       864        864
CHO          52        52         52
CHS        2884      2884       2884
CLE        4573      4573       4573
CLT       14064     14064      14064
CMH        3524      3524       3524
CRW         138       138        138
CVG        3941      3941       3941
DAY        1525      1525       1525
DCA        9705      9705       9705
DEN        7266      7266       7266
...         ...       ...        ...
PIT        2875      2875       2875
PSE         365       365        365
PSP          19        19         19
PVD         376       376        376
PWM        2352      2352       2352
RDU        8163      8163       8163
RIC        2454      2454       2454
ROC        2416      2416       2416
RSW        3537      3537       3537
SAN        2737      2737       2737
SAT         686       686        686
SAV         804       804        804
SBN          10        10         10
SDF        1157      1157       1157
SEA        3923      3923       3923
SFO       13331     13331      13331
SJC         329       329        329
SJU        5819      5819       5819
SLC        2467      2467       2467
SMF         284       284        284
SNA         825       825        825
SRQ        1211      1211       1211
STL        4339      4339       4339
STT         522       522        522
SYR        1761      1761       1761
TPA        7466      7466       7466
TUL         315       315        315
TVC         101       101        101
TYS         631       631        631
XNA        1036      1036       1036

[105 rows x 18 columns]

In [82]:
k.sort_values(by=['Column1'], ascending=False)

#by sorting the counts from high to low, we see that ORD (O'hare), ATL (Atlanta), LAX (Los Angeles), BOS (Boston), and MCO (Orlando) have the most arrivals during 2013.
#all of the airports in the data set operate 365 days per year, so the airports with the highest total counts will also have the highest average arrivals per day.

,Column1,year,month,day,sched_dep_time,sched_arr_time,carrier,flight,origin,distance,hour,minute,time_hour,dep_time,air_time,arr_delay,arr_time,dep_delay
dest,,,,,,,,,,,,,,,,,,
ORD,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283,17283
ATL,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215,17215
LAX,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174,16174
BOS,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508,15508
MCO,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082,14082
CLT,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064,14064
SFO,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331,13331
FLL,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055,12055
MIA,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728,11728
DCA,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705,9705
DTW,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384,9384
DFW,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738,8738
RDU,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163,8163
TPA,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466,7466
DEN,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266,7266
IAH,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198,7198
MSP,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185,7185
PBI,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554,6554
BNA,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333,6333
LAS,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997,5997
SJU,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819,5819
IAD,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700
BUF,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681,4681
PHX,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656,4656
CLE,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573,4573
STL,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339,4339
MDW,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113,4113
CVG,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941,3941
SEA,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923,3923
MSY,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799,3799
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BGR,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375,375
BUR,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371,371
PSE,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365,365
OKC,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346,346
SJC,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329,329
TUL,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315,315
OAK,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312,312
BHM,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297,297
SMF,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284,284
AVL,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275,275
ACK,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265,265
ABQ,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254,254
MVY,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221,221
EGE,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213,213
CRW,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138,138
CAE,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116,116
ILM,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110,110
TVC,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101
MYR,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59
CHO,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52
BZN,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36
JAC,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
PSP,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
EYW,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
HDN,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
MTJ,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15
SBN,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
ANC,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
LGA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
LEX,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
#now it it time to find the inter-arrival times for these 5 airports

In [95]:
FlightC.head()

,Column1,year,month,day,sched_dep_time,sched_arr_time,carrier,flight,origin,dest,distance,hour,minute,time_hour,dep_time,air_time,arr_delay,arr_time,dep_delay
0,1,2013,1,1,515,819,UA,1545,EWR,IAH,1400,5,15,1/1/2013 5:00,517.0,227.0,11.0,830.0,2.0
1,2,2013,1,1,529,830,UA,1714,LGA,IAH,1416,5,29,1/1/2013 5:00,533.0,227.0,20.0,850.0,4.0
2,3,2013,1,1,540,850,AA,1141,JFK,MIA,1089,5,40,1/1/2013 5:00,542.0,160.0,33.0,923.0,2.0
3,4,2013,1,1,545,1022,B6,725,JFK,BQN,1576,5,45,1/1/2013 5:00,544.0,183.0,-18.0,1004.0,-1.0
4,5,2013,1,1,600,837,DL,461,LGA,ATL,762,6,0,1/1/2013 6:00,554.0,116.0,-25.0,812.0,-6.0

In [92]:
#remove rows with flights departing on one day and arriving on the next day (red eye flight

if('sched_dep_time' + 'dep_delay' + 'air_time' > 2400)

SyntaxError: invalid syntax (<ipython-input-92-a186334c70e0>, line 3)

In [99]:
FlightC['sched_dep_time'] + ['dep_delay'] > 1200

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

In [100]:
FlightC.dtypes

Column1             int64
year                int64
month               int64
day                 int64
sched_dep_time      int64
sched_arr_time      int64
carrier            object
flight              int64
origin             object
dest               object
distance            int64
hour                int64
minute              int64
time_hour          object
dep_time          float64
air_time          float64
arr_delay         float64
arr_time          float64
dep_delay         float64
dtype: object

In [66]:
WeatherC.dtypes

origin         object
year            int64
month           int64
day             int64
hour            int64
precip        float64
visib         float64
time_hour      object
temp          float64
dewp          float64
humid         float64
pressure      float64
wind_dir      float64
wind_gust     float64
wind_speed    float64
dtype: object

In [106]:
FlightC['dep_time'].astype(str)

0                 517.0
1                 533.0
2                 542.0
3                 544.0
4                 554.0
5                 554.0
6                 555.0
7                 557.0
8                 557.0
9                 558.0
10                558.0
11                558.0
12                558.0
13                558.0
14                559.0
15                559.0
16                559.0
17                600.0
18                600.0
19                601.0
20                602.0
21                602.0
22                606.0
23                606.0
24                607.0
25                608.0
26                611.0
27                613.0
28                615.0
29                615.0
              ...
336746           2123.0
336747           2127.0
336748           2128.0
336749           2129.0
336750           2131.0
336751           2140.0
336752           2142.0
336753           2145.0
336754           2147.0
336755           2149.0
336756           2150.0
336757           2159.0
336758           2203.0
336759           2207.0
336760           2211.0
336761           2231.0
336762           2233.0
336763           2235.0
336764           2237.0
336765           2240.0
336766           2240.0
336767           2241.0
336768           2307.0
336769           2349.0
336770    1349.10994731
336771    1349.10994731
336772    1349.10994731
336773    1349.10994731
336774    1349.10994731
336775    1349.10994731
Name: dep_time, Length: 336776, dtype: object

In [107]:
FlightC.dtypes

Column1             int64
year                int64
month               int64
day                 int64
sched_dep_time      int64
sched_arr_time      int64
carrier            object
flight              int64
origin             object
dest               object
distance            int64
hour                int64
minute              int64
time_hour          object
dep_time          float64
air_time          float64
arr_delay         float64
arr_time          float64
dep_delay         float64
dtype: object

In [35]:
cols = ['dep_time', 'air_time', 'arr_delay', 'arr_time', 'dep_delay']
FlightC2 = FlightC[cols].applymap(int)
print(FlightC2)

        dep_time  air_time  arr_delay  arr_time  dep_delay
0            517       227         11       830          2
1            533       227         20       850          4
2            542       160         33       923          2
3            544       183        -18      1004         -1
4            554       116        -25       812         -6
5            554       150         12       740         -4
6            555       158         19       913         -5
7            557        53        -14       709         -3
8            557       140         -8       838         -3
9            558       138          8       753         -2
10           558       149         -2       849         -2
11           558       158         -3       853         -2
12           558       345          7       924         -2
13           558       361        -14       923         -2
14           559       257         31       941         -1
15           559        44         -4       702          0
16           559       337         -8       854         -1
17           600       152         -7       851          0
18           600       134         12       837          0
19           601       147         -6       844          1
20           602       170         -8       812         -8
21           602       105         16       821         -3
22           606       152        -12       858         -4
23           606       128         -8       837         -4
24           607       157        -17       858          0
25           608       139         32       807          8
26           611       366         14       945         11
27           613       175          4       925          3
28           615       182        -21      1039          0
29           615       120         -9       833          0
...          ...       ...        ...       ...        ...
336746      2123        45        -24      2223         -2
336747      2127        72         -9      2314         -2
336748      2128       213        -31      2328         -2
336749      2129        45         -2      2230         30
336750      2131        36        -30      2225         -9
336751      2140       298        -30        10          0
336752      2142        47         11      2250         13
336753      2145       192        -25       115          0
336754      2147       139          3        30         10
336755      2149        37        -23      2245         -7
336756      2150        39        -16      2250         -9
336757      2159        50        194      2344        194
336758      2203        61          8      2339         -2
336759      2207        97          7      2257         27
336760      2211       120         57      2339         72
336761      2231        48        -21      2335        -14
336762      2233       318         42       112         80
336763      2235       123        130        59        154
336764      2237        43         -8      2345         -8
336765      2240        41        -17      2334         -5
336766      2240        52        -20      2347        -10
336767      2241        47        -16      2345         -5
336768      2307        33          1      2359         12
336769      2349       196        -25       325        -10
336770      1349       150          6      1502         12
336771      1349       150          6      1502         12
336772      1349       150          6      1502         12
336773      1349       150          6      1502         12
336774      1349       150          6      1502         12
336775      1349       150          6      1502         12

[336776 rows x 5 columns]

In [36]:
FlightC2.dtypes

dep_time     int64
air_time     int64
arr_delay    int64
arr_time     int64
dep_delay    int64
dtype: object

In [37]:
FlightC3 = FlightC.assign(Column1=Column1.values, year=year.values, month=month.values, day=day.values, sched_dep_time=sched_dep_time.values, sched_arr_time=sched_arr_time.values, carrier=carrier.values, flight=flight.values, origin=origin.values, dest=dest.values, distance=distance.values, hour=hour.values, minute=minute.values)
print(FlightC3)
#doesn't work

NameError: name 'Column1' is not defined

In [132]:
FlightC3 = FlightC.assign(yeara = 'year')
print(FlightC3)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time   air_time   arr_delay     arr_time  dep_delay yeara
0        517.000000  227.00000   11.000000   830.000000    2.00000  year
1        533.000000  227.00000   20.000000   850.000000    4.00000  year
2        542.000000  160.00000   33.000000   923.000000    2.00000  year
3        544.000000  183.00000  -18.000000  1004.000000   -1.00000  year
4        554.000000  116.00000  -25.000000   812.000000   -6.00000  year
5        554.000000  150.00000   12.000000   740.000000   -4.00000  year
6        555.000000  158.00000   19.000000   913.000000   -5.00000  year
7        557.000000   53.00000  -14.000000   709.000000   -3.00000  year
8        557.000000  140.00000   -8.000000   838.000000   -3.00000  year
9        558.000000  138.00000    8.000000   753.000000   -2.00000  year
10       558.000000  149.00000   -2.000000   849.000000   -2.00000  year
11       558.000000  158.00000   -3.000000   853.000000   -2.00000  year
12       558.000000  345.00000    7.000000   924.000000   -2.00000  year
13       558.000000  361.00000  -14.000000   923.000000   -2.00000  year
14       559.000000  257.00000   31.000000   941.000000   -1.00000  year
15       559.000000   44.00000   -4.000000   702.000000    0.00000  year
16       559.000000  337.00000   -8.000000   854.000000   -1.00000  year
17       600.000000  152.00000   -7.000000   851.000000    0.00000  year
18       600.000000  134.00000   12.000000   837.000000    0.00000  year
19       601.000000  147.00000   -6.000000   844.000000    1.00000  year
20       602.000000  170.00000   -8.000000   812.000000   -8.00000  year
21       602.000000  105.00000   16.000000   821.000000   -3.00000  year
22       606.000000  152.00000  -12.000000   858.000000   -4.00000  year
23       606.000000  128.00000   -8.000000   837.000000   -4.00000  year
24       607.000000  157.00000  -17.000000   858.000000    0.00000  year
25       608.000000  139.00000   32.000000   807.000000    8.00000  year
26       611.000000  366.00000   14.000000   945.000000   11.00000  year
27       613.000000  175.00000    4.000000   925.000000    3.00000  year
28       615.000000  182.00000  -21.000000  1039.000000    0.00000  year
29       615.000000  120.00000   -9.000000   833.000000    0.00000  year
...             ...        ...         ...          ...        ...   ...
336746  2123.000000   45.00000  -24.000000  2223.000000   -2.00000  year
336747  2127.000000   72.00000   -9.000000  2314.000000   -2.00000  year
336748  2128.000000  213.00000  -31.000000  2328.000000   -2.00000  year
336749  2129.000000   45.00000   -2.000000  2230.000000   30.00000  year
336750  2131.000000   36.00000  -30.000000  2225.000000   -9.00000  year
336751  2140.000000  298.00000  -30.000000    10.000000    0.00000  year
336752  2142.000000   47.00000   11.000000  2250.000000   13.00000  year
336753  2145.000000  192.00000  -25.000000   115.000000    0.00000  year
336754  2147.000000  139.00000    3.000000    30.000000   10.00000  year
336755  2149.000000   37.00000  -23.000000  2245.000000   -7.00000  year
336756  2150.000000   39.00000  -16.000000  2250.000000   -9.00000  year
336757  2159.000000   50.00000  194.000000  2344.000000  194.00000  year
336758  2203.000000   61.00000    8.000000  2339.000000   -2.00000  year
336759  2207.000000   97.00000    7.000000  2257.000000   27.00000  year
336760  2211.000000  120.00000   57.000000  2339.000000   72.00000  year
336761  2231.000000   48.00000  -21.000000  2335.000000  -14.00000  year
336762  2233.000000  318.00000   42.000000   112.000000   80.00000  year
336763  2235.000000  123.00000  130.000000    59.000000  154.00000  year
336764  2237.000000   43.00000   -8.000000  2345.000000   -8.00000  year
336765  2240.000000   41.00000  -17.000000  2334.000000   -5.00000  year
336766  2240.000000   52.00000  -20.000000  2347.000000  -10.00000  year
336767  2241.000000   47.00000  -16.000000  2345.000000   -5.00000  year
336768  2307.000000   33.00000    1.000000  2359.000000   12.00000  year
336769  2349.000000  196.00000  -25.000000   325.000000  -10.00000  year
336770  1349.109947  150.68646    6.895377  1502.054999   12.63907  year
336771  1349.109947  150.68646    6.895377  1502.054999   12.63907  year
336772  1349.109947  150.68646    6.895377  1502.054999   12.63907  year
336773  1349.109947  150.68646    6.895377  1502.054999   12.63907  year
336774  1349.109947  150.68646    6.895377  1502.054999   12.63907  year
336775  1349.109947  150.68646    6.895377  1502.054999   12.63907  year

[336776 rows x 20 columns]

In [38]:
FlightC4 = FlightC.assign(yeara = FlightC['year'].values)
print(FlightC4)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00
4          461    LGA  ATL       762     6       0    1/1/2013 6:00
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           79    JFK  MCO       944     6       0    1/1/2013 6:00
9          301    LGA  ORD       733     6       0    1/1/2013 6:00
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00
29         575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...    ...  ...       ...   ...     ...              ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00

           dep_time   air_time   arr_delay     arr_time  dep_delay  yeara
0        517.000000  227.00000   11.000000   830.000000    2.00000   2013
1        533.000000  227.00000   20.000000   850.000000    4.00000   2013
2        542.000000  160.00000   33.000000   923.000000    2.00000   2013
3        544.000000  183.00000  -18.000000  1004.000000   -1.00000   2013
4        554.000000  116.00000  -25.000000   812.000000   -6.00000   2013
5        554.000000  150.00000   12.000000   740.000000   -4.00000   2013
6        555.000000  158.00000   19.000000   913.000000   -5.00000   2013
7        557.000000   53.00000  -14.000000   709.000000   -3.00000   2013
8        557.000000  140.00000   -8.000000   838.000000   -3.00000   2013
9        558.000000  138.00000    8.000000   753.000000   -2.00000   2013
10       558.000000  149.00000   -2.000000   849.000000   -2.00000   2013
11       558.000000  158.00000   -3.000000   853.000000   -2.00000   2013
12       558.000000  345.00000    7.000000   924.000000   -2.00000   2013
13       558.000000  361.00000  -14.000000   923.000000   -2.00000   2013
14       559.000000  257.00000   31.000000   941.000000   -1.00000   2013
15       559.000000   44.00000   -4.000000   702.000000    0.00000   2013
16       559.000000  337.00000   -8.000000   854.000000   -1.00000   2013
17       600.000000  152.00000   -7.000000   851.000000    0.00000   2013
18       600.000000  134.00000   12.000000   837.000000    0.00000   2013
19       601.000000  147.00000   -6.000000   844.000000    1.00000   2013
20       602.000000  170.00000   -8.000000   812.000000   -8.00000   2013
21       602.000000  105.00000   16.000000   821.000000   -3.00000   2013
22       606.000000  152.00000  -12.000000   858.000000   -4.00000   2013
23       606.000000  128.00000   -8.000000   837.000000   -4.00000   2013
24       607.000000  157.00000  -17.000000   858.000000    0.00000   2013
25       608.000000  139.00000   32.000000   807.000000    8.00000   2013
26       611.000000  366.00000   14.000000   945.000000   11.00000   2013
27       613.000000  175.00000    4.000000   925.000000    3.00000   2013
28       615.000000  182.00000  -21.000000  1039.000000    0.00000   2013
29       615.000000  120.00000   -9.000000   833.000000    0.00000   2013
...             ...        ...         ...          ...        ...    ...
336746  2123.000000   45.00000  -24.000000  2223.000000   -2.00000   2013
336747  2127.000000   72.00000   -9.000000  2314.000000   -2.00000   2013
336748  2128.000000  213.00000  -31.000000  2328.000000   -2.00000   2013
336749  2129.000000   45.00000   -2.000000  2230.000000   30.00000   2013
336750  2131.000000   36.00000  -30.000000  2225.000000   -9.00000   2013
336751  2140.000000  298.00000  -30.000000    10.000000    0.00000   2013
336752  2142.000000   47.00000   11.000000  2250.000000   13.00000   2013
336753  2145.000000  192.00000  -25.000000   115.000000    0.00000   2013
336754  2147.000000  139.00000    3.000000    30.000000   10.00000   2013
336755  2149.000000   37.00000  -23.000000  2245.000000   -7.00000   2013
336756  2150.000000   39.00000  -16.000000  2250.000000   -9.00000   2013
336757  2159.000000   50.00000  194.000000  2344.000000  194.00000   2013
336758  2203.000000   61.00000    8.000000  2339.000000   -2.00000   2013
336759  2207.000000   97.00000    7.000000  2257.000000   27.00000   2013
336760  2211.000000  120.00000   57.000000  2339.000000   72.00000   2013
336761  2231.000000   48.00000  -21.000000  2335.000000  -14.00000   2013
336762  2233.000000  318.00000   42.000000   112.000000   80.00000   2013
336763  2235.000000  123.00000  130.000000    59.000000  154.00000   2013
336764  2237.000000   43.00000   -8.000000  2345.000000   -8.00000   2013
336765  2240.000000   41.00000  -17.000000  2334.000000   -5.00000   2013
336766  2240.000000   52.00000  -20.000000  2347.000000  -10.00000   2013
336767  2241.000000   47.00000  -16.000000  2345.000000   -5.00000   2013
336768  2307.000000   33.00000    1.000000  2359.000000   12.00000   2013
336769  2349.000000  196.00000  -25.000000   325.000000  -10.00000   2013
336770  1349.109947  150.68646    6.895377  1502.054999   12.63907   2013
336771  1349.109947  150.68646    6.895377  1502.054999   12.63907   2013
336772  1349.109947  150.68646    6.895377  1502.054999   12.63907   2013
336773  1349.109947  150.68646    6.895377  1502.054999   12.63907   2013
336774  1349.109947  150.68646    6.895377  1502.054999   12.63907   2013
336775  1349.109947  150.68646    6.895377  1502.054999   12.63907   2013

[336776 rows x 20 columns]

In [39]:
FlightC5 = FlightC.assign(Column1=FlightC['Column1'].values, year=FlightC['year'].values, month=FlightC['month'].values, day=FlightC['day'].values, sched_dep_time=FlightC['sched_dep_time'].values, sched_arr_time=FlightC['sched_arr_time'].values, carrier=FlightC['carrier'].values, flight=FlightC['flight'].values, origin=FlightC['origin'].values, dest=FlightC['dest'].values, distance=FlightC['distance'].values, hour=FlightC['hour'].values, minute=FlightC['minute'].values, dep_time=FlightC2['dep_time'].values, air_time=FlightC2['air_time'].values, arr_delay=FlightC2['arr_delay'].values, arr_time=FlightC2['arr_time'].values, dep_delay=FlightC2['dep_delay'].values)
print(FlightC5)
#need to reassign columns

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

        flight origin dest  distance  hour  minute        time_hour  dep_time  \
0         1545    EWR  IAH      1400     5      15    1/1/2013 5:00       517
1         1714    LGA  IAH      1416     5      29    1/1/2013 5:00       533
2         1141    JFK  MIA      1089     5      40    1/1/2013 5:00       542
3          725    JFK  BQN      1576     5      45    1/1/2013 5:00       544
4          461    LGA  ATL       762     6       0    1/1/2013 6:00       554
5         1696    EWR  ORD       719     5      58    1/1/2013 5:00       554
6          507    EWR  FLL      1065     6       0    1/1/2013 6:00       555
7         5708    LGA  IAD       229     6       0    1/1/2013 6:00       557
8           79    JFK  MCO       944     6       0    1/1/2013 6:00       557
9          301    LGA  ORD       733     6       0    1/1/2013 6:00       558
10          49    JFK  PBI      1028     6       0    1/1/2013 6:00       558
11          71    JFK  TPA      1005     6       0    1/1/2013 6:00       558
12         194    JFK  LAX      2475     6       0    1/1/2013 6:00       558
13        1124    EWR  SFO      2565     6       0    1/1/2013 6:00       558
14         707    LGA  DFW      1389     6       0    1/1/2013 6:00       559
15        1806    JFK  BOS       187     5      59    1/1/2013 5:00       559
16        1187    EWR  LAS      2227     6       0    1/1/2013 6:00       559
17         371    LGA  FLL      1076     6       0    1/1/2013 6:00       600
18        4650    LGA  ATL       762     6       0    1/1/2013 6:00       600
19         343    EWR  PBI      1023     6       0    1/1/2013 6:00       601
20        1919    LGA  MSP      1020     6      10    1/1/2013 6:00       602
21        4401    LGA  DTW       502     6       5    1/1/2013 6:00       602
22        1895    EWR  MIA      1085     6      10    1/1/2013 6:00       606
23        1743    JFK  ATL       760     6      10    1/1/2013 6:00       606
24        1077    EWR  MIA      1085     6       7    1/1/2013 6:00       607
25        3768    EWR  ORD       719     6       0    1/1/2013 6:00       608
26         303    JFK  SFO      2586     6       0    1/1/2013 6:00       611
27         135    JFK  RSW      1074     6      10    1/1/2013 6:00       613
28         709    JFK  SJU      1598     6      15    1/1/2013 6:00       615
29         575    EWR  ATL       746     6      15    1/1/2013 6:00       615
...        ...    ...  ...       ...   ...     ...              ...       ...
336746    5489    LGA  CHO       305    21      25  9/30/2013 21:00      2123
336747    3833    EWR  CLT       529    21      29  9/30/2013 21:00      2127
336748      97    JFK  DEN      1626    21      30  9/30/2013 21:00      2128
336749    5048    LGA  RIC       292    20      59  9/30/2013 20:00      2129
336750    3621    JFK  DCA       213    21      40  9/30/2013 21:00      2131
336751     185    JFK  LAX      2475    21      40  9/30/2013 21:00      2140
336752    4509    EWR  PWM       284    21      29  9/30/2013 21:00      2142
336753    1103    JFK  SJU      1598    21      45  9/30/2013 21:00      2145
336754    1371    LGA  FLL      1076    21      37  9/30/2013 21:00      2147
336755     523    EWR  BOS       200    21      56  9/30/2013 21:00      2149
336756    3842    EWR  MHT       209    21      59  9/30/2013 21:00      2150
336757    3320    JFK  BUF       301    18      45  9/30/2013 18:00      2159
336758    5311    LGA  BGR       378    22       5  9/30/2013 22:00      2203
336759    3660    LGA  BNA       764    21      40  9/30/2013 21:00      2207
336760    4672    EWR  STL       872    20      59  9/30/2013 20:00      2211
336761     108    JFK  PWM       273    22      45  9/30/2013 22:00      2231
336762     471    EWR  SFO      2565    21      13  9/30/2013 21:00      2233
336763    1083    JFK  MCO       944    20       1  9/30/2013 20:00      2235
336764     234    JFK  BTV       266    22      45  9/30/2013 22:00      2237
336765    1816    JFK  SYR       209    22      45  9/30/2013 22:00      2240
336766    2002    JFK  BUF       301    22      50  9/30/2013 22:00      2240
336767     486    JFK  ROC       264    22      46  9/30/2013 22:00      2241
336768     718    JFK  BOS       187    22      55  9/30/2013 22:00      2307
336769     745    JFK  PSE      1617    23      59  9/30/2013 23:00      2349
336770    5274    LGA  BNA       764    18      42  9/30/2013 18:00      1349
336771    3393    JFK  DCA       213    14      55  9/30/2013 14:00      1349
336772    3525    LGA  SYR       198    22       0  9/30/2013 22:00      1349
336773    3461    LGA  BNA       764    12      10  9/30/2013 12:00      1349
336774    3572    LGA  CLE       419    11      59  9/30/2013 11:00      1349
336775    3531    LGA  RDU       431     8      40   9/30/2013 8:00      1349

        air_time  arr_delay  arr_time  dep_delay
0            227         11       830          2
1            227         20       850          4
2            160         33       923          2
3            183        -18      1004         -1
4            116        -25       812         -6
5            150         12       740         -4
6            158         19       913         -5
7             53        -14       709         -3
8            140         -8       838         -3
9            138          8       753         -2
10           149         -2       849         -2
11           158         -3       853         -2
12           345          7       924         -2
13           361        -14       923         -2
14           257         31       941         -1
15            44         -4       702          0
16           337         -8       854         -1
17           152         -7       851          0
18           134         12       837          0
19           147         -6       844          1
20           170         -8       812         -8
21           105         16       821         -3
22           152        -12       858         -4
23           128         -8       837         -4
24           157        -17       858          0
25           139         32       807          8
26           366         14       945         11
27           175          4       925          3
28           182        -21      1039          0
29           120         -9       833          0
...          ...        ...       ...        ...
336746        45        -24      2223         -2
336747        72         -9      2314         -2
336748       213        -31      2328         -2
336749        45         -2      2230         30
336750        36        -30      2225         -9
336751       298        -30        10          0
336752        47         11      2250         13
336753       192        -25       115          0
336754       139          3        30         10
336755        37        -23      2245         -7
336756        39        -16      2250         -9
336757        50        194      2344        194
336758        61          8      2339         -2
336759        97          7      2257         27
336760       120         57      2339         72
336761        48        -21      2335        -14
336762       318         42       112         80
336763       123        130        59        154
336764        43         -8      2345         -8
336765        41        -17      2334         -5
336766        52        -20      2347        -10
336767        47        -16      2345         -5
336768        33          1      2359         12
336769       196        -25       325        -10
336770       150          6      1502         12
336771       150          6      1502         12
336772       150          6      1502         12
336773       150          6      1502         12
336774       150          6      1502         12
336775       150          6      1502         12

[336776 rows x 19 columns]

In [40]:
FlightC5.dtypes

Column1            int64
year               int64
month              int64
day                int64
sched_dep_time     int64
sched_arr_time     int64
carrier           object
flight             int64
origin            object
dest              object
distance           int64
hour               int64
minute             int64
time_hour         object
dep_time           int64
air_time           int64
arr_delay          int64
arr_time           int64
dep_delay          int64
dtype: object

In [141]:
FlightC5['sched_dep_time'] + ['dep_delay'] > 1200

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

In [67]:
cols2 = ['precip', 'visib', 'temp', 'dewp', 'humid', 'pressure', 'wind_dir', 'wind_gust', 'wind_speed']
WeatherC2 = WeatherC[cols2].applymap(int)
print(WeatherC2)

       precip  visib  temp  dewp  humid  pressure  wind_dir  wind_gust  \
0           0     10    37    21     53      1013       230         11
1           0     10    37    21     53      1013       230         15
2           0     10    37    21     52      1012       230         14
3           0     10    37    23     54      1012       230         15
4           0     10    37    24     57      1012       240         17
5           0     10    39    26     59      1012       270         11
6           0     10    39    26     61      1012       250          9
7           0     10    39    28     64      1012       240         13
8           0     10    39    28     62      1012       250         14
9           0     10    39    28     64      1011       260         14
10          0     10    37    28     67      1012       240         13
11          0     10    39    28     64      1012       240         17
12          0     10    39    28     62      1012       250         11
13          0     10    39    28     62      1012       260         17
14          0     10    41    28     59      1012       260         15
15          0     10    41    26     57      1011       260         17
16          0     10    39    28     64      1017       270         18
17          0     10    39    28     64      1017       330         17
18          0     10    39    24     54      1010       280         15
19          0     10    37    24     57      1011       290         10
20          0     10    37    19     49      1012       300         15
21          0     10    35    19     49      1013       330         13
22          0     10    33    15     45      1014       310         14
23          0     10    33    12     42      1014       320         11
24          0     10    32    15     49      1015       310         17
25          0     10    30    12     48      1016       320         21
26          0     10    28    12     48      1016       320         21
27          0     10    28    10     48      1016       310         18
28          0     10    26    10     50      1016       310         17
29          0     10    26    10     52      1016       330         14
...       ...    ...   ...   ...    ...       ...       ...        ...
26100       0      2    42    37     81      1017        70         10
26101       0      1    39    37     93      1017        40         18
26102       0      1    41    39     92       999        40         15
26103       0      1    41    37     88       998       350          9
26104       0      2    41    39     93      1017        50         23
26105       0      3    42    39     88       997       330         17
26106       0      8    42    37     81      1017       320         19
26107       0      6    41    37     86      1017       310         22
26108       0     10    42    37     81      1017       320         18
26109       0     10    42    37     79      1003       300         10
26110       0     10    42    35     73      1005       310         19
26111       0     10    42    33     72      1005       320         13
26112       0     10    42    33     72      1007       250         10
26113       0     10    41    33     75      1008       240          9
26114       0     10    42    33     70      1008       270         10
26115       0     10    41    33     73      1008         0          0
26116       0     10    42    33     67      1009       250         11
26117       0     10    42    33     70      1010       230          7
26118       0     10    44    35     70      1011       240         13
26119       0     10    44    33     67      1012       260         13
26120       0     10    44    33     65      1013       260         15
26121       0     10    42    33     70      1017       330         18
26122       0     10    41    28     60      1017       340         15
26123       0     10    37    23     54      1015       330         25
26124       0     10    37    21     53      1016       340         19
26125       0     10    35    19     51      1017       340         15
26126       0     10    33    17     49      1018       330         19
26127       0     10    32    15     49      1019       340         17
26128       0     10    30    12     46      1019       320         19
26129       0     10    28    10     46      1020       330         21

       wind_speed
0              10
1              13
2              12
3              13
4              14
5              10
6               8
7              11
8              12
9              12
10             11
11             14
12             10
13             14
14             13
15             14
16             16
17             14
18             13
19              9
20             13
21             11
22             12
23             10
24             14
25             18
26             18
27             16
28             14
29             12
...           ...
26100           9
26101          16
26102          13
26103           8
26104          20
26105          14
26106          17
26107          19
26108          16
26109           9
26110          17
26111          11
26112           9
26113           8
26114           9
26115           0
26116          10
26117           6
26118          11
26119          11
26120          13
26121          16
26122          13
26123          21
26124          17
26125          13
26126          17
26127          14
26128          17
26129          18

[26130 rows x 9 columns]

In [68]:
WeatherC3 = WeatherC2.assign(origin=WeatherC['origin'].values, year=WeatherC['year'].values, month=WeatherC['month'].values, day=WeatherC['day'].values, hour=WeatherC['hour'], time_hour=WeatherC['time_hour'].values)
print(WeatherC3)

       precip  visib  temp  dewp  humid  pressure  wind_dir  wind_gust  \
0           0     10    37    21     53      1013       230         11
1           0     10    37    21     53      1013       230         15
2           0     10    37    21     52      1012       230         14
3           0     10    37    23     54      1012       230         15
4           0     10    37    24     57      1012       240         17
5           0     10    39    26     59      1012       270         11
6           0     10    39    26     61      1012       250          9
7           0     10    39    28     64      1012       240         13
8           0     10    39    28     62      1012       250         14
9           0     10    39    28     64      1011       260         14
10          0     10    37    28     67      1012       240         13
11          0     10    39    28     64      1012       240         17
12          0     10    39    28     62      1012       250         11
13          0     10    39    28     62      1012       260         17
14          0     10    41    28     59      1012       260         15
15          0     10    41    26     57      1011       260         17
16          0     10    39    28     64      1017       270         18
17          0     10    39    28     64      1017       330         17
18          0     10    39    24     54      1010       280         15
19          0     10    37    24     57      1011       290         10
20          0     10    37    19     49      1012       300         15
21          0     10    35    19     49      1013       330         13
22          0     10    33    15     45      1014       310         14
23          0     10    33    12     42      1014       320         11
24          0     10    32    15     49      1015       310         17
25          0     10    30    12     48      1016       320         21
26          0     10    28    12     48      1016       320         21
27          0     10    28    10     48      1016       310         18
28          0     10    26    10     50      1016       310         17
29          0     10    26    10     52      1016       330         14
...       ...    ...   ...   ...    ...       ...       ...        ...
26100       0      2    42    37     81      1017        70         10
26101       0      1    39    37     93      1017        40         18
26102       0      1    41    39     92       999        40         15
26103       0      1    41    37     88       998       350          9
26104       0      2    41    39     93      1017        50         23
26105       0      3    42    39     88       997       330         17
26106       0      8    42    37     81      1017       320         19
26107       0      6    41    37     86      1017       310         22
26108       0     10    42    37     81      1017       320         18
26109       0     10    42    37     79      1003       300         10
26110       0     10    42    35     73      1005       310         19
26111       0     10    42    33     72      1005       320         13
26112       0     10    42    33     72      1007       250         10
26113       0     10    41    33     75      1008       240          9
26114       0     10    42    33     70      1008       270         10
26115       0     10    41    33     73      1008         0          0
26116       0     10    42    33     67      1009       250         11
26117       0     10    42    33     70      1010       230          7
26118       0     10    44    35     70      1011       240         13
26119       0     10    44    33     67      1012       260         13
26120       0     10    44    33     65      1013       260         15
26121       0     10    42    33     70      1017       330         18
26122       0     10    41    28     60      1017       340         15
26123       0     10    37    23     54      1015       330         25
26124       0     10    37    21     53      1016       340         19
26125       0     10    35    19     51      1017       340         15
26126       0     10    33    17     49      1018       330         19
26127       0     10    32    15     49      1019       340         17
26128       0     10    30    12     46      1019       320         19
26129       0     10    28    10     46      1020       330         21

       wind_speed  day  hour  month origin         time_hour  year
0              10    1     0      1    EWR  12/31/2012 19:00  2013
1              13    1     1      1    EWR  12/31/2012 20:00  2013
2              12    1     2      1    EWR  12/31/2012 21:00  2013
3              13    1     3      1    EWR  12/31/2012 22:00  2013
4              14    1     4      1    EWR  12/31/2012 23:00  2013
5              10    1     6      1    EWR     1/1/2013 1:00  2013
6               8    1     7      1    EWR     1/1/2013 2:00  2013
7              11    1     8      1    EWR     1/1/2013 3:00  2013
8              12    1     9      1    EWR     1/1/2013 4:00  2013
9              12    1    10      1    EWR     1/1/2013 5:00  2013
10             11    1    11      1    EWR     1/1/2013 6:00  2013
11             14    1    12      1    EWR     1/1/2013 7:00  2013
12             10    1    13      1    EWR     1/1/2013 8:00  2013
13             14    1    14      1    EWR     1/1/2013 9:00  2013
14             13    1    15      1    EWR    1/1/2013 10:00  2013
15             14    1    16      1    EWR    1/1/2013 11:00  2013
16             16    1    17      1    EWR    1/1/2013 12:00  2013
17             14    1    18      1    EWR    1/1/2013 13:00  2013
18             13    1    19      1    EWR    1/1/2013 14:00  2013
19              9    1    20      1    EWR    1/1/2013 15:00  2013
20             13    1    21      1    EWR    1/1/2013 16:00  2013
21             11    1    22      1    EWR    1/1/2013 17:00  2013
22             12    1    23      1    EWR    1/1/2013 18:00  2013
23             10    2     0      1    EWR    1/1/2013 19:00  2013
24             14    2     1      1    EWR    1/1/2013 20:00  2013
25             18    2     2      1    EWR    1/1/2013 21:00  2013
26             18    2     3      1    EWR    1/1/2013 22:00  2013
27             16    2     4      1    EWR    1/1/2013 23:00  2013
28             14    2     5      1    EWR     1/2/2013 0:00  2013
29             12    2     6      1    EWR     1/2/2013 1:00  2013
...           ...  ...   ...    ...    ...               ...   ...
26100           9   29    18     12    LGA  12/29/2013 13:00  2013
26101          16   29    19     12    LGA  12/29/2013 14:00  2013
26102          13   29    20     12    LGA  12/29/2013 15:00  2013
26103           8   29    21     12    LGA  12/29/2013 16:00  2013
26104          20   29    22     12    LGA  12/29/2013 17:00  2013
26105          14   29    23     12    LGA  12/29/2013 18:00  2013
26106          17   30     0     12    LGA  12/29/2013 19:00  2013
26107          19   30     1     12    LGA  12/29/2013 20:00  2013
26108          16   30     2     12    LGA  12/29/2013 21:00  2013
26109           9   30     3     12    LGA  12/29/2013 22:00  2013
26110          17   30     4     12    LGA  12/29/2013 23:00  2013
26111          11   30     5     12    LGA   12/30/2013 0:00  2013
26112           9   30     6     12    LGA   12/30/2013 1:00  2013
26113           8   30     7     12    LGA   12/30/2013 2:00  2013
26114           9   30     8     12    LGA   12/30/2013 3:00  2013
26115           0   30     9     12    LGA   12/30/2013 4:00  2013
26116          10   30    10     12    LGA   12/30/2013 5:00  2013
26117           6   30    11     12    LGA   12/30/2013 6:00  2013
26118          11   30    12     12    LGA   12/30/2013 7:00  2013
26119          11   30    13     12    LGA   12/30/2013 8:00  2013
26120          13   30    14     12    LGA   12/30/2013 9:00  2013
26121          16   30    15     12    LGA  12/30/2013 10:00  2013
26122          13   30    16     12    LGA  12/30/2013 11:00  2013
26123          21   30    17     12    LGA  12/30/2013 12:00  2013
26124          17   30    18     12    LGA  12/30/2013 13:00  2013
26125          13   30    19     12    LGA  12/30/2013 14:00  2013
26126          17   30    20     12    LGA  12/30/2013 15:00  2013
26127          14   30    21     12    LGA  12/30/2013 16:00  2013
26128          17   30    22     12    LGA  12/30/2013 17:00  2013
26129          18   30    23     12    LGA  12/30/2013 18:00  2013

[26130 rows x 15 columns]

In [69]:
WeatherC3.dtypes

precip         int64
visib          int64
temp           int64
dewp           int64
humid          int64
pressure       int64
wind_dir       int64
wind_gust      int64
wind_speed     int64
day            int64
hour           int64
month          int64
origin        object
time_hour     object
year           int64
dtype: object

In [185]:
import datetime

In [186]:
from datetime import timedelta

In [188]:
#test out the code

YY = 2013
MM = 1
DD = 1
arr ='45'
arr2 = arr.zfill(4)
#print(arr2)
t = datetime.datetime.strptime(arr2, '%H%M')
print(t.hour, t.minute)
type(t.hour)
type(arr)

0 45

str

In [169]:
#datetime.datetime(YY, MM, DD, t.hour), int(t,min)

yy = 2013
mm = 9
dd = 23
arr3 = '2345'
arr4 = arr3.zfill(4)
print(arr4)
tt = datetime.datetime.strptime(arr4, '%H%M')
h = tt.hour
m = tt.minute

date = datetime.datetime(yy, mm, dd, h, m)
print(date)

date2 = date + datetime.timedelta(minutes=34)
print(date2)

2345
2013-09-23 23:45:00
2013-09-24 00:19:00

In [171]:
#convert datetime to seconds

(date-datetime.datetime(1970,1,1)).total_seconds()

#1.37 million seconds....

#could have done this in another window...

1379979900.0

In [182]:
(date-datetime.datetime(2014,1,1)).total_seconds()

-8554500.0

In [ ]:
#FlightC5 arr_time is the column I need to be manipulating...
#Well I need to be manipulating year, month, day, and arr_time
#this will help with the sorting of new column, rather than grouping by the five selected airports

In [41]:
FlightC5.head()

,Column1,year,month,day,sched_dep_time,sched_arr_time,carrier,flight,origin,dest,distance,hour,minute,time_hour,dep_time,air_time,arr_delay,arr_time,dep_delay
0,1,2013,1,1,515,819,UA,1545,EWR,IAH,1400,5,15,1/1/2013 5:00,517,227,11,830,2
1,2,2013,1,1,529,830,UA,1714,LGA,IAH,1416,5,29,1/1/2013 5:00,533,227,20,850,4
2,3,2013,1,1,540,850,AA,1141,JFK,MIA,1089,5,40,1/1/2013 5:00,542,160,33,923,2
3,4,2013,1,1,545,1022,B6,725,JFK,BQN,1576,5,45,1/1/2013 5:00,544,183,-18,1004,-1
4,5,2013,1,1,600,837,DL,461,LGA,ATL,762,6,0,1/1/2013 6:00,554,116,-25,812,-6

In [187]:
FlightC5['arr_time'].zfill(4)

AttributeError: 'Series' object has no attribute 'zfill'

In [194]:
m = FlightC5['arr_time'].apply(str)
#print(m)
type(m)

pandas.core.series.Series

In [190]:
FlightC5.dtypes

Column1            int64
year               int64
month              int64
day                int64
sched_dep_time     int64
sched_arr_time     int64
carrier           object
flight             int64
origin            object
dest              object
distance           int64
hour               int64
minute             int64
time_hour         object
dep_time           int64
air_time           int64
arr_delay          int64
arr_time           int64
dep_delay          int64
dtype: object

In [191]:
type('arr_time')

str

In [196]:
#FlightN2 = Flight.filter(['Column1', 'year', 'month', 'day', 'sched_dep_time', 'sched_arr_time', 'carrier', 'flight', 'origin', 'dest', 'distance', 'hour', 'minute', 'time_hour'], axis=1)

FlightC6 = FlightC5.filter(['Column1', 'year', 'month', 'day', 'sched_dep_time', 'sched_arr_time', 'carrier', 'carrier', 'flight', 'origin', 'dest', 'distance', 'hour', 'minute', 'time_hour', 'dep_time', 'air_time', 'arr_delay', 'dep_delay'])
print(FlightC6)

        Column1  year  month  day  sched_dep_time  sched_arr_time carrier  \
0             1  2013      1    1             515             819      UA
1             2  2013      1    1             529             830      UA
2             3  2013      1    1             540             850      AA
3             4  2013      1    1             545            1022      B6
4             5  2013      1    1             600             837      DL
5             6  2013      1    1             558             728      UA
6             7  2013      1    1             600             854      B6
7             8  2013      1    1             600             723      EV
8             9  2013      1    1             600             846      B6
9            10  2013      1    1             600             745      AA
10           11  2013      1    1             600             851      B6
11           12  2013      1    1             600             856      B6
12           13  2013      1    1             600             917      UA
13           14  2013      1    1             600             937      UA
14           15  2013      1    1             600             910      AA
15           16  2013      1    1             559             706      B6
16           17  2013      1    1             600             902      UA
17           18  2013      1    1             600             858      B6
18           19  2013      1    1             600             825      MQ
19           20  2013      1    1             600             850      B6
20           21  2013      1    1             610             820      DL
21           22  2013      1    1             605             805      MQ
22           23  2013      1    1             610             910      AA
23           24  2013      1    1             610             845      DL
24           25  2013      1    1             607             915      UA
25           26  2013      1    1             600             735      MQ
26           27  2013      1    1             600             931      UA
27           28  2013      1    1             610             921      B6
28           29  2013      1    1             615            1100      B6
29           30  2013      1    1             615             842      DL
...         ...   ...    ...  ...             ...             ...     ...
336746   336747  2013      9   30            2125            2247      EV
336747   336748  2013      9   30            2129            2323      EV
336748   336749  2013      9   30            2130            2359      B6
336749   336750  2013      9   30            2059            2232      EV
336750   336751  2013      9   30            2140            2255      MQ
336751   336752  2013      9   30            2140              40      AA
336752   336753  2013      9   30            2129            2239      EV
336753   336754  2013      9   30            2145             140      B6
336754   336755  2013      9   30            2137              27      B6
336755   336756  2013      9   30            2156            2308      UA
336756   336757  2013      9   30            2159            2306      EV
336757   336758  2013      9   30            1845            2030      9E
336758   336759  2013      9   30            2205            2331      EV
336759   336760  2013      9   30            2140            2250      MQ
336760   336761  2013      9   30            2059            2242      EV
336761   336762  2013      9   30            2245            2356      B6
336762   336763  2013      9   30            2113              30      UA
336763   336764  2013      9   30            2001            2249      B6
336764   336765  2013      9   30            2245            2353      B6
336765   336766  2013      9   30            2245            2351      B6
336766   336767  2013      9   30            2250               7      B6
336767   336768  2013      9   30            2246               1      B6
336768   336769  2013      9   30            2255            2358      B6
336769   336770  2013      9   30            2359             350      B6
336770   336771  2013      9   30            1842            2019      EV
336771   336772  2013      9   30            1455            1634      9E
336772   336773  2013      9   30            2200            2312      9E
336773   336774  2013      9   30            1210            1330      MQ
336774   336775  2013      9   30            1159            1344      MQ
336775   336776  2013      9   30             840            1020      MQ

       carrier  flight origin dest  distance  hour  minute        time_hour  \
0           UA    1545    EWR  IAH      1400     5      15    1/1/2013 5:00
1           UA    1714    LGA  IAH      1416     5      29    1/1/2013 5:00
2           AA    1141    JFK  MIA      1089     5      40    1/1/2013 5:00
3           B6     725    JFK  BQN      1576     5      45    1/1/2013 5:00
4           DL     461    LGA  ATL       762     6       0    1/1/2013 6:00
5           UA    1696    EWR  ORD       719     5      58    1/1/2013 5:00
6           B6     507    EWR  FLL      1065     6       0    1/1/2013 6:00
7           EV    5708    LGA  IAD       229     6       0    1/1/2013 6:00
8           B6      79    JFK  MCO       944     6       0    1/1/2013 6:00
9           AA     301    LGA  ORD       733     6       0    1/1/2013 6:00
10          B6      49    JFK  PBI      1028     6       0    1/1/2013 6:00
11          B6      71    JFK  TPA      1005     6       0    1/1/2013 6:00
12          UA     194    JFK  LAX      2475     6       0    1/1/2013 6:00
13          UA    1124    EWR  SFO      2565     6       0    1/1/2013 6:00
14          AA     707    LGA  DFW      1389     6       0    1/1/2013 6:00
15          B6    1806    JFK  BOS       187     5      59    1/1/2013 5:00
16          UA    1187    EWR  LAS      2227     6       0    1/1/2013 6:00
17          B6     371    LGA  FLL      1076     6       0    1/1/2013 6:00
18          MQ    4650    LGA  ATL       762     6       0    1/1/2013 6:00
19          B6     343    EWR  PBI      1023     6       0    1/1/2013 6:00
20          DL    1919    LGA  MSP      1020     6      10    1/1/2013 6:00
21          MQ    4401    LGA  DTW       502     6       5    1/1/2013 6:00
22          AA    1895    EWR  MIA      1085     6      10    1/1/2013 6:00
23          DL    1743    JFK  ATL       760     6      10    1/1/2013 6:00
24          UA    1077    EWR  MIA      1085     6       7    1/1/2013 6:00
25          MQ    3768    EWR  ORD       719     6       0    1/1/2013 6:00
26          UA     303    JFK  SFO      2586     6       0    1/1/2013 6:00
27          B6     135    JFK  RSW      1074     6      10    1/1/2013 6:00
28          B6     709    JFK  SJU      1598     6      15    1/1/2013 6:00
29          DL     575    EWR  ATL       746     6      15    1/1/2013 6:00
...        ...     ...    ...  ...       ...   ...     ...              ...
336746      EV    5489    LGA  CHO       305    21      25  9/30/2013 21:00
336747      EV    3833    EWR  CLT       529    21      29  9/30/2013 21:00
336748      B6      97    JFK  DEN      1626    21      30  9/30/2013 21:00
336749      EV    5048    LGA  RIC       292    20      59  9/30/2013 20:00
336750      MQ    3621    JFK  DCA       213    21      40  9/30/2013 21:00
336751      AA     185    JFK  LAX      2475    21      40  9/30/2013 21:00
336752      EV    4509    EWR  PWM       284    21      29  9/30/2013 21:00
336753      B6    1103    JFK  SJU      1598    21      45  9/30/2013 21:00
336754      B6    1371    LGA  FLL      1076    21      37  9/30/2013 21:00
336755      UA     523    EWR  BOS       200    21      56  9/30/2013 21:00
336756      EV    3842    EWR  MHT       209    21      59  9/30/2013 21:00
336757      9E    3320    JFK  BUF       301    18      45  9/30/2013 18:00
336758      EV    5311    LGA  BGR       378    22       5  9/30/2013 22:00
336759      MQ    3660    LGA  BNA       764    21      40  9/30/2013 21:00
336760      EV    4672    EWR  STL       872    20      59  9/30/2013 20:00
336761      B6     108    JFK  PWM       273    22      45  9/30/2013 22:00
336762      UA     471    EWR  SFO      2565    21      13  9/30/2013 21:00
336763      B6    1083    JFK  MCO       944    20       1  9/30/2013 20:00
336764      B6     234    JFK  BTV       266    22      45  9/30/2013 22:00
336765      B6    1816    JFK  SYR       209    22      45  9/30/2013 22:00
336766      B6    2002    JFK  BUF       301    22      50  9/30/2013 22:00
336767      B6     486    JFK  ROC       264    22      46  9/30/2013 22:00
336768      B6     718    JFK  BOS       187    22      55  9/30/2013 22:00
336769      B6     745    JFK  PSE      1617    23      59  9/30/2013 23:00
336770      EV    5274    LGA  BNA       764    18      42  9/30/2013 18:00
336771      9E    3393    JFK  DCA       213    14      55  9/30/2013 14:00
336772      9E    3525    LGA  SYR       198    22       0  9/30/2013 22:00
336773      MQ    3461    LGA  BNA       764    12      10  9/30/2013 12:00
336774      MQ    3572    LGA  CLE       419    11      59  9/30/2013 11:00
336775      MQ    3531    LGA  RDU       431     8      40   9/30/2013 8:00

        dep_time  air_time  arr_delay  dep_delay
0            517       227         11          2
1            533       227         20          4
2            542       160         33          2
3            544       183        -18         -1
4            554       116        -25         -6
5            554       150         12         -4
6            555       158         19         -5
7            557        53        -14         -3
8            557       140         -8         -3
9            558       138          8         -2
10           558       149         -2         -2
11           558       158         -3         -2
12           558       345          7         -2
13           558       361        -14         -2
14           559       257         31         -1
15           559        44         -4          0
16           559       337         -8         -1
17           600       152         -7          0
18           600       134         12          0
19           601       147         -6          1
20           602       170         -8         -8
21           602       105         16         -3
22           606       152        -12         -4
23           606       128         -8         -4
24           607       157        -17          0
25           608       139         32          8
26           611       366         14         11
27           613       175          4          3
28           615       182        -21          0
29           615       120         -9          0
...          ...       ...        ...        ...
336746      2123        45        -24         -2
336747      2127        72         -9         -2
336748      2128       213        -31         -2
336749      2129        45         -2         30
336750      2131        36        -30         -9
336751      2140       298        -30          0
336752      2142        47         11         13
336753      2145       192        -25          0
336754      2147       139          3         10
336755      2149        37        -23         -7
336756      2150        39        -16         -9
336757      2159        50        194        194
336758      2203        61          8         -2
336759      2207        97          7         27
336760      2211       120         57         72
336761      2231        48        -21        -14
336762      2233       318         42         80
336763      2235       123        130        154
336764      2237        43         -8         -8
336765      2240        41        -17         -5
336766      2240        52        -20        -10
336767      2241        47        -16         -5
336768      2307        33          1         12
336769      2349       196        -25        -10
336770      1349       150          6         12
336771      1349       150          6         12
336772      1349       150          6         12
336773      1349       150          6         12
336774      1349       150          6         12
336775      1349       150          6         12

[336776 rows x 19 columns]

In [198]:
FlightC7 = FlightC6.assign(arr_time=m.values)
FlightC7.head()

,Column1,year,month,day,sched_dep_time,sched_arr_time,carrier,carrier,flight,origin,dest,distance,hour,minute,time_hour,dep_time,air_time,arr_delay,dep_delay,arr_time
0,1,2013,1,1,515,819,UA,UA,1545,EWR,IAH,1400,5,15,1/1/2013 5:00,517,227,11,2,830
1,2,2013,1,1,529,830,UA,UA,1714,LGA,IAH,1416,5,29,1/1/2013 5:00,533,227,20,4,850
2,3,2013,1,1,540,850,AA,AA,1141,JFK,MIA,1089,5,40,1/1/2013 5:00,542,160,33,2,923
3,4,2013,1,1,545,1022,B6,B6,725,JFK,BQN,1576,5,45,1/1/2013 5:00,544,183,-18,-1,1004
4,5,2013,1,1,600,837,DL,DL,461,LGA,ATL,762,6,0,1/1/2013 6:00,554,116,-25,-6,812

In [199]:
FlightC7.dtypes

Column1            int64
year               int64
month              int64
day                int64
sched_dep_time     int64
sched_arr_time     int64
carrier           object
carrier           object
flight             int64
origin            object
dest              object
distance           int64
hour               int64
minute             int64
time_hour         object
dep_time           int64
air_time           int64
arr_delay          int64
dep_delay          int64
arr_time          object
dtype: object

In [200]:
FlightC7['arr_time'].zfill(4)

AttributeError: 'Series' object has no attribute 'zfill'

In [201]:
FlightC5.dtypes

Column1            int64
year               int64
month              int64
day                int64
sched_dep_time     int64
sched_arr_time     int64
carrier           object
flight             int64
origin            object
dest              object
distance           int64
hour               int64
minute             int64
time_hour         object
dep_time           int64
air_time           int64
arr_delay          int64
arr_time           int64
dep_delay          int64
dtype: object

In [204]:
#lets try to move on without zfill...

FlightC8 = FlightC5['year'] + FlightC5['day']
print(FlightC8)

0         2014
1         2014
2         2014
3         2014
4         2014
5         2014
6         2014
7         2014
8         2014
9         2014
10        2014
11        2014
12        2014
13        2014
14        2014
15        2014
16        2014
17        2014
18        2014
19        2014
20        2014
21        2014
22        2014
23        2014
24        2014
25        2014
26        2014
27        2014
28        2014
29        2014
          ...
336746    2043
336747    2043
336748    2043
336749    2043
336750    2043
336751    2043
336752    2043
336753    2043
336754    2043
336755    2043
336756    2043
336757    2043
336758    2043
336759    2043
336760    2043
336761    2043
336762    2043
336763    2043
336764    2043
336765    2043
336766    2043
336767    2043
336768    2043
336769    2043
336770    2043
336771    2043
336772    2043
336773    2043
336774    2043
336775    2043
Length: 336776, dtype: int64

In [205]:
FlightC9 = FlightC5['Column1'] + FlightC5['year'] + FlightC5['month'] + FlightC5['day'] + FlightC5['sched_dep_time'] + FlightC5['sched_arr_time'] + FlightC5['carrier'] + FlightC5['origin'] + FlightC5['dest'] + FlightC5['distance'] + FlightC5['hour'] + FlightC5['minute'] + FlightC5['time_hour'] + FlightC5['dep_time'] + FlightC5['air_time'] + FlightC5['arr_delay'] + FlightC5['dep_delay'] + FlightC5['arr_time']

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [5]:
Airline.dtypes

Unnamed: 0     int64
carrier       object
name          object
dtype: object

In [6]:
Airport.dtypes

Unnamed: 0      int64
faa            object
name           object
lat           float64
lon           float64
alt             int64
tz              int64
dst            object
tzone          object
dtype: object

In [7]:
PlaneC2 = PlaneC.to_csv
print(PlaneC2)

<bound method DataFrame.to_csv of      tailnum    year                     type                   manufacturer  \
0     N10156  2004.0  Fixed wing multi engine                        EMBRAER
1     N102UW  1998.0  Fixed wing multi engine               AIRBUS INDUSTRIE
2     N103US  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
3     N104UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
4     N10575  2002.0  Fixed wing multi engine                        EMBRAER
5     N105UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
6     N107US  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
7     N108UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
8     N109UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
9     N110UW  1999.0  Fixed wing multi engine               AIRBUS INDUSTRIE
10    N11106  2002.0  Fixed wing multi engine                        EMBRAER
11    N11107  2002.0  Fixed wing multi engine                        EMBRAER
12    N11109  2002.0  Fixed wing multi engine                        EMBRAER
13    N11113  2002.0  Fixed wing multi engine                        EMBRAER
14    N11119  2002.0  Fixed wing multi engine                        EMBRAER
15    N11121  2003.0  Fixed wing multi engine                        EMBRAER
16    N11127  2003.0  Fixed wing multi engine                        EMBRAER
17    N11137  2003.0  Fixed wing multi engine                        EMBRAER
18    N11140  2003.0  Fixed wing multi engine                        EMBRAER
19    N11150  2003.0  Fixed wing multi engine                        EMBRAER
20    N11155  2004.0  Fixed wing multi engine                        EMBRAER
21    N11164  2004.0  Fixed wing multi engine                        EMBRAER
22    N11165  2004.0  Fixed wing multi engine                        EMBRAER
23    N11176  2004.0  Fixed wing multi engine                        EMBRAER
24    N11181  2005.0  Fixed wing multi engine                        EMBRAER
25    N11184  2005.0  Fixed wing multi engine                        EMBRAER
26    N11187  2005.0  Fixed wing multi engine                        EMBRAER
27    N11189  2005.0  Fixed wing multi engine                        EMBRAER
28    N11191  2005.0  Fixed wing multi engine                        EMBRAER
29    N11192  2005.0  Fixed wing multi engine                        EMBRAER
...      ...     ...                      ...                            ...
3292  N984DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3293  N985AT  2001.0  Fixed wing multi engine                         BOEING
3294  N985DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3295  N986AT  2001.0  Fixed wing multi engine                         BOEING
3296  N986DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3297  N987AT  2001.0  Fixed wing multi engine                         BOEING
3298  N987DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3299  N988AT  2001.0  Fixed wing multi engine                         BOEING
3300  N988DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3301  N989AT  2001.0  Fixed wing multi engine                         BOEING
3302  N989DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3303  N990AT  2001.0  Fixed wing multi engine                         BOEING
3304  N990DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3305  N991AT     NaN  Fixed wing multi engine                         BOEING
3306  N991DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3307  N992AT  2002.0  Fixed wing multi engine                         BOEING
3308  N992DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3309  N993AT  2002.0  Fixed wing multi engine                         BOEING
3310  N993DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3311  N994AT  2002.0  Fixed wing multi engine                         BOEING
3312  N994DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION
3313  N995AT  2002.0  Fixed wing multi engine                         BOEING
3314  N995DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3315  N996AT  2002.0  Fixed wing multi engine                         BOEING
3316  N996DL  1991.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3317  N997AT  2002.0  Fixed wing multi engine                         BOEING
3318  N997DL  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS AIRCRAFT CO
3319  N998AT  2002.0  Fixed wing multi engine                         BOEING
3320  N998DL  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION
3321  N999DN  1992.0  Fixed wing multi engine  MCDONNELL DOUGLAS CORPORATION

          model  engines  seats     engine
0     EMB-145XR        2     55  Turbo-fan
1      A320-214        2    182  Turbo-fan
2      A320-214        2    182  Turbo-fan
3      A320-214        2    182  Turbo-fan
4     EMB-145LR        2     55  Turbo-fan
5      A320-214        2    182  Turbo-fan
6      A320-214        2    182  Turbo-fan
7      A320-214        2    182  Turbo-fan
8      A320-214        2    182  Turbo-fan
9      A320-214        2    182  Turbo-fan
10    EMB-145XR        2     55  Turbo-fan
11    EMB-145XR        2     55  Turbo-fan
12    EMB-145XR        2     55  Turbo-fan
13    EMB-145XR        2     55  Turbo-fan
14    EMB-145XR        2     55  Turbo-fan
15    EMB-145XR        2     55  Turbo-fan
16    EMB-145XR        2     55  Turbo-fan
17    EMB-145XR        2     55  Turbo-fan
18    EMB-145XR        2     55  Turbo-fan
19    EMB-145XR        2     55  Turbo-fan
20    EMB-145XR        2     55  Turbo-fan
21    EMB-145XR        2     55  Turbo-fan
22    EMB-145XR        2     55  Turbo-fan
23    EMB-145XR        2     55  Turbo-fan
24    EMB-145XR        2     55  Turbo-fan
25    EMB-145XR        2     55  Turbo-fan
26    EMB-145XR        2     55  Turbo-fan
27    EMB-145XR        2     55  Turbo-fan
28    EMB-145XR        2     55  Turbo-fan
29    EMB-145XR        2     55  Turbo-fan
...         ...      ...    ...        ...
3292      MD-88        2    142  Turbo-fan
3293    717-200        2    100  Turbo-fan
3294      MD-88        2    142  Turbo-fan
3295    717-200        2    100  Turbo-fan
3296      MD-88        2    142  Turbo-fan
3297    717-200        2    100  Turbo-fan
3298      MD-88        2    142  Turbo-fan
3299    717-200        2    100  Turbo-fan
3300      MD-88        2    142  Turbo-fan
3301    717-200        2    100  Turbo-fan
3302      MD-88        2    142  Turbo-fan
3303    717-200        2    100  Turbo-fan
3304      MD-88        2    142  Turbo-fan
3305    717-200        2    100  Turbo-fan
3306      MD-88        2    142  Turbo-fan
3307    717-200        2    100  Turbo-fan
3308      MD-88        2    142  Turbo-fan
3309    717-200        2    100  Turbo-fan
3310      MD-88        2    142  Turbo-fan
3311    717-200        2    100  Turbo-fan
3312      MD-88        2    142  Turbo-jet
3313    717-200        2    100  Turbo-fan
3314      MD-88        2    142  Turbo-fan
3315    717-200        2    100  Turbo-fan
3316      MD-88        2    142  Turbo-fan
3317    717-200        2    100  Turbo-fan
3318      MD-88        2    142  Turbo-fan
3319    717-200        2    100  Turbo-fan
3320      MD-88        2    142  Turbo-jet
3321      MD-88        2    142  Turbo-jet

[3322 rows x 8 columns]>

In [5]:
type(PlaneC)

pandas.core.frame.DataFrame

In [14]:
PlaneC3 = PlaneC2.to_excel

AttributeError: 'function' object has no attribute 'to_excel'

In [15]:
PlaneC4 = pd.read_csv('PlaneC2.csv')

FileNotFoundError: File b'PlaneC2.csv' does not exist

In [16]:
PlaneC5 = PlaneC.to_csv('PlaneC2.csv')

In [22]:
PlaneC.dtypes

tailnum          object
year            float64
type             object
manufacturer     object
model            object
engines           int64
seats             int64
engine           object
dtype: object

In [42]:
FlightC5.to_csv('FlightC5.csv')

In [70]:
#now weather...

WeatherC3.to_csv('WeatherC3.csv')

In [71]:
FlightC5.dtypes

Column1            int64
year               int64
month              int64
day                int64
sched_dep_time     int64
sched_arr_time     int64
carrier           object
flight             int64
origin            object
dest              object
distance           int64
hour               int64
minute             int64
time_hour         object
dep_time           int64
air_time           int64
arr_delay          int64
arr_time           int64
dep_delay          int64
dtype: object

In [74]:
WeatherC3.dtypes

precip         int64
visib          int64
temp           int64
dewp           int64
humid          int64
pressure       int64
wind_dir       int64
wind_gust      int64
wind_speed     int64
day            int64
hour           int64
month          int64
origin        object
time_hour     object
year           int64
dtype: object